// Story 12.4c AC9 — 🔴 THE PORT IS PROVED AGAINST TOOL 12, NOT ASSERTED.
//
// Every expectation in `fixtures/tool12-parity.json` is Tool 12's own output.
// Nothing here is hand-computed, and nothing here re-implements the reference:
// the fixture is generated by `apps/mobile/bench/12-4c/video_oracle.py`, which
// calls `scoring.py` / `phases.py` directly.
//
// The `capture` block goes further: its fire bits come from the real 73-minute
// V2 capture, decoded by FFmpeg, converted with the pinned numpy BT.709
// limited-range + nearest-chroma model and evaluated by Tool 9's own
// `zone_fires_on_frame`. So these 1061 rows exercise the SHIPPED config's 134
// rules — including its 9 hue-WRAP rules and 68 FULL-CIRCLE (h_tol = 180,
// low-saturation) rules — on real HUD-2.0 footage, rather than on inputs chosen
// to make the port look good.
//
// What this suite can and cannot close:
//   * it CAN close the scoring and phase semantics end to end, because those are
//     TypeScript's (AC0b) and they are what the fixture holds;
//   * it CANNOT close the fire bits themselves — those are produced in Kotlin by
//     `WardenCpuBaseline.evaluateYuv`, and the device half of that comparison is
//     `video_oracle.py compare` against a real device run (AC10), which belongs
//     to the epic-end device pass. What this suite does assert about them is
//     that the fixture's rules EXERCISE every band branch in both directions, so
//     the device comparison is not vacuous when it runs.

import fixture from "./fixtures/tool12-parity.json";
import {
  argmaxWithThreshold,
  hexToFires,
  scoreFromFires,
  type ClassifierShape,
  type RuleRef,
} from "../engineScoring";
import {
  createPhaseResolver,
  inMatchCall,
  resolvePhases,
  spansFromStates,
  type InMatchCall,
  type InternalPhaseState,
} from "../gameDetector";
import { aggregateSpanScores, identifySpanMap } from "../mapIdentifier";

interface FixtureRef {
  texel: number;
  owning_class: string;
  zone_id: string;
  kind: string;
  effective_weight: number;
  mode?: number;
  h_tol?: number;
}

const toRefs = (refs: FixtureRef[]): RuleRef[] =>
  refs.map((r) => ({
    texel: r.texel,
    owningClass: r.owning_class,
    zoneId: r.zone_id,
    kind: r.kind as RuleRef["kind"],
    effectiveWeight: r.effective_weight,
  }));

// The fixture is a JSON module, so TS infers a union of per-case literal shapes
// whose `map_zone_counts` keys differ between cases. One narrow cast at the
// boundary is clearer than widening the production type to please a fixture.
interface FixtureClassifierShape {
  hud_version: string;
  n_hud_zones: number;
  n_in_match_zones: number;
  map_zone_counts: Record<string, number>;
  identification_threshold: number;
}

const toShape = (raw: unknown): ClassifierShape => {
  const c = raw as FixtureClassifierShape;
  return {
    hudVersion: c.hud_version,
    nHudZones: c.n_hud_zones,
    nInMatchZones: c.n_in_match_zones,
    mapZoneCounts: c.map_zone_counts,
    identificationThreshold: c.identification_threshold,
  };
};

describe("scoring.py parity — the THREE distinct classifier formulas", () => {
  for (const testCase of fixture.scoring_cases) {
    describe(`${testCase.name}: ${testCase.note}`, () => {
      const refs = toRefs(testCase.refs as FixtureRef[]);
      const shape = toShape(testCase);

      testCase.frames.forEach((expected, i) => {
        it(`frame ${i} (fires=${expected.fires}) matches Tool 12`, () => {
          const scores = scoreFromFires(expected.fires, refs, shape);
          expect(scores.predHud).toBe(expected.pred_hud);
          expect(scores.hudConf).toBeCloseTo(expected.hud_conf, 12);
          expect(scores.predInMatch).toBe(expected.pred_in_match);
          expect(scores.inMatchConf).toBeCloseTo(expected.in_match_conf, 12);
          expect(scores.predMap).toBe(expected.pred_map);
          expect(scores.mapConf).toBeCloseTo(expected.map_conf, 12);
          expect(scores.mapScores).toEqual(expected.map_scores);
        });
      });
    });
  }

  it("in_match is HARD-BINARY — a split vote is not_in_match, never unknown", () => {
    // The trap this guards: `_argmax_with_threshold`'s `unknown` serves the HUD
    // and map classifiers only. Routing in_match through it would produce
    // `unknown` below 0.5, and the phase machine would then have an upstream
    // unknown that `phases.py` says explicitly does not exist.
    const three = fixture.scoring_cases.find((c) => c.name === "three_formulas")!;
    const refs = toRefs(three.refs as FixtureRef[]);
    const shape = toShape(three);
    const splitVote = three.frames.find((f) => f.in_match_conf > 0 && f.in_match_conf < 0.5);
    expect(splitVote).toBeDefined();
    expect(scoreFromFires(splitVote!.fires, refs, shape).predInMatch).toBe(
      "not_in_match"
    );
  });

  it("only an EMPTY in_match_detection array yields unknown, and it does not throw", () => {
    const empty = fixture.scoring_cases.find(
      (c) => c.name === "empty_detection_arrays"
    )!;
    const refs = toRefs(empty.refs as FixtureRef[]);
    const shape = toShape(empty);
    for (const frame of empty.frames) {
      const scores = scoreFromFires(frame.fires, refs, shape);
      expect(scores.predInMatch).toBe("unknown");
      expect(scores.predHud).toBe("unknown");
    }
  });

  it("map-ID sums RAW weights — a single 0.5-weighted zone does not clear 0.6", () => {
    const weighted = fixture.scoring_cases.find(
      (c) => c.name === "weighted_aggregate"
    )!;
    const refs = toRefs(weighted.refs as FixtureRef[]);
    const shape = toShape(weighted);
    // Row 0 fires ONE 0.5-weight zone. Normalized (0.5 / 1 zone = 0.5 …or
    // /2 zones = 0.25) it would still be below 0.6; the point is the RAW sum
    // being 0.5 and the verdict unknown, while row 1's two 0.5s make 1.0.
    expect(scoreFromFires(weighted.frames[0].fires, refs, shape).predMap).toBe(
      "unknown"
    );
    expect(scoreFromFires(weighted.frames[1].fires, refs, shape).predMap).toBe(
      "atlantis"
    );
    expect(scoreFromFires(weighted.frames[1].fires, refs, shape).mapConf).toBe(1);
  });

  it("argmax tie-breaks by zone count, then by the canonical label order", () => {
    // Frozen for Story 9.13's contract pin. A tie resolved differently changes
    // which map a segment is labelled while every individual score stays right.
    expect(
      argmaxWithThreshold(
        { ceres: 2, atlantis: 2 },
        { threshold: 0.6, orderedClasses: ["artefact", "atlantis", "ceres"], zoneCounts: { ceres: 2, atlantis: 2 } }
      ).label
    ).toBe("atlantis");
    expect(
      argmaxWithThreshold(
        { ceres: 2, atlantis: 2 },
        { threshold: 0.6, orderedClasses: ["artefact", "atlantis", "ceres"], zoneCounts: { ceres: 5, atlantis: 2 } }
      ).label
    ).toBe("ceres");
    // A score of exactly 0 is unknown even at threshold 0 — nothing fired.
    expect(
      argmaxWithThreshold(
        { ceres: 0 },
        { threshold: 0, orderedClasses: ["ceres"], zoneCounts: { ceres: 2 } }
      ).label
    ).toBe("unknown");
  });
});

describe("phases.py parity — doubt is first-class and doubt HOLDS", () => {
  for (const phaseCase of fixture.phase_cases) {
    it(`${phaseCase.name}: ${phaseCase.note}`, () => {
      const resolver = createPhaseResolver(phaseCase.score_screen_duration_ms);
      const internal: InternalPhaseState[] = [];
      phaseCase.frames.forEach((frame) => {
        const call = inMatchCall(frame.in_match_conf, {
          doubtMargin: phaseCase.doubt_margin,
        });
        expect(call).toBe(frame.call as InMatchCall);
        expect(resolver.push(frame.timestamp_ms, call)).toBe(frame.emitted);
        expect(resolver.state()).toBe(frame.internal);
        internal.push(resolver.state());
      });
      expect(spansFromStates(internal)).toEqual(
        phaseCase.spans.map((s) => ({ startFrame: s.start_frame, endFrame: s.end_frame }))
      );
    });
  }

  it("🔴 a doubtful frame mid-match does NOT split the span", () => {
    // The single most likely thing to get wrong, asserted on its own rather
    // than only inside the table above: the emitted timeline shows `doubt`, the
    // internal state holds `in_match`, and ONE span comes out.
    const held = fixture.phase_cases.find((c) => c.name === "doubt_holds_mid_match")!;
    const frames = held.frames.map((f) => ({
      timestampMs: f.timestamp_ms,
      call: inMatchCall(f.in_match_conf, { doubtMargin: held.doubt_margin }),
    }));
    const { emitted, internal } = resolvePhases(frames, held.score_screen_duration_ms);
    expect(emitted.filter((s) => s === "doubt").length).toBeGreaterThan(0);
    expect(internal).not.toContain("doubt");
    expect(spansFromStates(internal)).toHaveLength(1);
    // And the counterfactual: cutting spans from the EMITTED states — the
    // mistake this design exists to prevent — shreds that one match into three.
    const fromEmitted = spansFromStates(
      emitted.map((s) => (s === "doubt" ? "not_in_match" : s)) as InternalPhaseState[]
    );
    expect(fromEmitted.length).toBeGreaterThan(1);
  });
});

describe("the real capture — 1061 keyframes, the shipped 134 rules", () => {
  const capture = fixture.capture;
  const refs = toRefs(capture.refs as FixtureRef[]);
  const shape = toShape(capture);

  it("the fixture exercises every band branch in BOTH directions", () => {
    // Without this the wrap/full-circle coverage claim would be a hope. The
    // counts are the shipped config's: 57 normal, 9 wrap, 68 full-circle.
    expect(capture.rule_mode_counts).toEqual({
      normal: 57,
      wrap: 9,
      full_circle: 68,
    });
    expect(capture.n_rules).toBe(134);
    // All 9 wrap rules (E3 — `h_min > h_max` read as an interval crossing 0/1)
    // both fire and clear somewhere in the capture.
    expect(capture.wrap_rules_exercised_both_ways).toBe(9);
    // And the low-saturation full-circle rules, where h_tol = 180 leaves hue
    // unconstrained, are exercised in bulk too.
    expect(capture.full_circle_rules_exercised_both_ways).toBeGreaterThanOrEqual(50);
    const hTol180 = (capture.refs as FixtureRef[]).filter((r) => r.h_tol === 180);
    expect(hTol180).toHaveLength(68);
    expect(hTol180.every((r) => r.mode === 2)).toBe(true);
  });

  it("scores all 1061 keyframes exactly as Tool 12 does", () => {
    let checked = 0;
    for (const frame of capture.frames) {
      const scores = scoreFromFires(frame.fires, refs, shape);
      expect(scores.predHud).toBe(frame.pred_hud);
      expect(scores.hudConf).toBeCloseTo(frame.hud_conf, 12);
      expect(scores.predInMatch).toBe(frame.pred_in_match);
      expect(scores.inMatchConf).toBeCloseTo(frame.in_match_conf, 12);
      expect(scores.predMap).toBe(frame.pred_map);
      expect(scores.mapConf).toBeCloseTo(frame.map_conf, 12);
      checked++;
    }
    expect(checked).toBe(capture.frames.length);
    expect(checked).toBe(1061);
  });

  it("resolves the same phase timeline and the same spans", () => {
    const resolver = createPhaseResolver(capture.score_screen_duration_ms);
    const internal: InternalPhaseState[] = [];
    for (const frame of capture.frames) {
      const call = inMatchCall(frame.in_match_conf, {
        doubtMargin: capture.doubt_margin,
      });
      expect(call).toBe(frame.call);
      expect(resolver.push(frame.timestamp_ms, call)).toBe(frame.emitted);
      internal.push(resolver.state());
      expect(resolver.state()).toBe(frame.internal);
    }
    expect(spansFromStates(internal)).toEqual(
      capture.spans.map((s) => ({ startFrame: s.start_frame, endFrame: s.end_frame }))
    );
    // Real footage does contain doubt: two split votes over 73 minutes.
    expect(capture.frames.filter((f) => f.emitted === "doubt")).toHaveLength(2);
  });

  it("identifies the same map for every span — and no span is unknown", () => {
    // 🔴 THIS IS THE STORY'S WHOLE POINT, in one assertion: on HUD-2.0 footage
    // the v2 engine labels every detected match, where the v1 pHash path
    // produced `unknown` (epics-and-stories.md:2748). It is an IN-SAMPLE parity
    // result with no holdout — it is NOT an accuracy claim and does NOT touch
    // REL-006, which has no instrument until Story 9.16.
    const perFrameScores = capture.frames.map(
      (f) => scoreFromFires(f.fires, refs, shape).mapScores
    );
    const labels = capture.spans.map((span) => {
      const agg = aggregateSpanScores(perFrameScores, span.start_frame, span.end_frame);
      return identifySpanMap(agg, {
        identificationThreshold: capture.identification_threshold,
      });
    });
    expect(labels.map((l) => l.mapName)).toEqual(
      capture.matches.map((m) => m.map_id)
    );
    expect(labels.every((l) => l.mapName !== null)).toBe(true);
  });

  it("decodes the fire-bit hex the same way the native side encodes it", () => {
    // LSB-first, 4 bits per char. Three producers (Kotlin, the PC oracle,
    // pc_reference.py) and two consumers agree on this packing; a silent
    // endianness flip would move every rule to a different classifier.
    const first = capture.frames[0];
    const bits = hexToFires(first.fires, capture.n_rules);
    expect(bits).toHaveLength(134);
    const hudFires = bits.filter((b, i) => b && refs[i].kind === "hud_version").length;
    expect(hudFires / capture.n_hud_zones).toBeCloseTo(first.hud_conf, 12);
    // A truncated row must fail loudly rather than clearing trailing rules.
    expect(() => hexToFires(first.fires.slice(0, 10), capture.n_rules)).toThrow(
      /hex chars/
    );
  });
});
