package team.warden.mobile

// Story 12.2 AC12 — 🔴 THE NUMBER THE EPIC TURNS ON.
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// 12.1's headline is "on PC the CPU is 2x FASTER than the GPU at rule
// evaluation" (cv2.inRange 1.667 ms/frame vs GPU 3.253 ms/frame = 0.51x),
// because reaching ~800 texel fetches costs a 6.2 MB whole-frame upload. Story
// 12.3 cannot act on that without knowing whether it holds on Adreno — so this
// file is the device-side CPU arm of the comparison, decode excluded from BOTH
// sides.
//
// DELIBERATELY NOT routed through react-native-fast-opencv JSI: that re-opens
// Story 1.1's FROZEN spike and adds a variable to the one measurement the epic
// hinges on. ~100 lines of plain Kotlin buys a clean comparison.
//
// Same rects, same integer RGB2HSV_b, same inclusive integer bounds, same
// `count/area >= min_ratio`. The ONLY difference from the GPU arm is where the
// arithmetic happens.

object WardenCpuBaseline {

    /**
     * OpenCV's RGB2HSV_b, ported EXACTLY (integer arithmetic, hsv_shift = 12) —
     * the same conversion the .frag performs, so the two arms cannot disagree
     * for reasons unrelated to CPU-vs-GPU.
     *
     * Takes (b, g, r) POSITIONALLY, mirroring OpenCV's own
     * `int b = src[bidx], g = src[1], r = src[bidx^2]` for bidx=0.
     *
     * Returns H, S, V packed into one Int (h shl 16 or s shl 8 or v) to avoid
     * allocating 2 million IntArrays per frame — at 1920x1080 the allocation
     * would dominate the very measurement this exists to take.
     */
    fun rgb2hsvPacked(b: Int, g: Int, r: Int): Int {
        val v = maxOf(maxOf(b, g), r)
        val vmin = minOf(minOf(b, g), r)
        val diff = v - vmin

        val vr = if (v == r) -1 else 0
        val vg = if (v == g) -1 else 0

        // OpenCV precomputes these as tables via a float divide + round:
        //   sdiv_table[i]    = round((255 << 12) / i)
        //   hdiv_table180[i] = round((180 << 12) / (6 * i))
        // Recomputed per-pixel here so the CPU arm uses the SAME expression the
        // shader does; see AC8 — on the GPU these are float divides at ESSL
        // `highp`, and this arm is the reference they are checked against.
        val sdiv = if (v > 0) Math.floor((255 * 4096).toDouble() / v + 0.5).toInt() else 0
        val hdiv = if (diff > 0)
            Math.floor((180 * 4096).toDouble() / (6.0 * diff) + 0.5).toInt() else 0

        val s = (diff * sdiv + 2048) shr 12

        var h = (vr and (g - b)) +
            (vr.inv() and ((vg and (b - r + 2 * diff)) + (vg.inv() and (r - g + 4 * diff))))
        // Kotlin's `shr` on Int is an ARITHMETIC shift (sign-extending), matching
        // C++ and matching what the .frag asserts of ESSL's `>>`. `ushr` here
        // would silently produce enormous positive hues for the 9 wrap-branch
        // rules. (AC9 verifies the GPU side of this on Adreno.)
        h = (h * hdiv + 2048) shr 12
        if (h < 0) h += 180

        return (h shl 16) or (s shl 8) or v
    }

    /**
     * Evaluate all rules over one BGRA frame. Returns the per-rule fire bits.
     *
     * `bgra` is the SAME buffer the GPU arm uploads — B,G,R,A per pixel, row
     * major, `width * 4` bytes per row. Feeding both arms identical bytes is
     * what makes the comparison about the engine rather than about the decode.
     */
    fun evaluate(
        bgra: ByteArray,
        width: Int,
        height: Int,
        packed: WardenPackedRules,
    ): BooleanArray {
        val out = BooleanArray(packed.nRules)
        val tex = packed.texture
        for (i in 0 until packed.nRules) {
            val base = i * 3 * 4
            val rx = tex[base + 0].toInt()
            val ry = tex[base + 1].toInt()
            val rw = tex[base + 2].toInt()
            val rh = tex[base + 3].toInt()

            val hLo = tex[base + 4].toInt()
            val hHi = tex[base + 5].toInt()
            val sLo = tex[base + 6].toInt()
            val sHi = tex[base + 7].toInt()

            val vLo = tex[base + 8].toInt()
            val vHi = tex[base + 9].toInt()
            val minRatio = tex[base + 10]
            val mode = tex[base + 11].toInt()

            val area = rw * rh

            // Hue sub-interval bounds for the wrap branch: [wlo,179] u [0,whi].
            // FLOORED mod, matching Python's `%` and GLSL's `mod()` — h_lo is
            // packed RAW and can be negative, and Kotlin's `%` truncates.
            val wlo = Math.floorMod(hLo, 180)
            val whi = Math.floorMod(hHi, 180)

            var count = 0
            var k = 0
            val n = minOf(area, MAX_RECT_TEXELS)
            while (k < n) {
                val dy = k / rw
                val dx = k - dy * rw
                val off = ((ry + dy) * width + (rx + dx)) * 4
                val b = bgra[off].toInt() and 0xFF
                val g = bgra[off + 1].toInt() and 0xFF
                val r = bgra[off + 2].toInt() and 0xFF

                val hsv = rgb2hsvPacked(b, g, r)
                val hh = (hsv ushr 16) and 0xFFFF
                val ss = (hsv ushr 8) and 0xFF
                val vv = hsv and 0xFF

                val hueOk = when (mode) {
                    MODE_FULL_CIRCLE -> true
                    MODE_WRAP -> hh >= wlo || hh <= whi
                    else -> hh in hLo..hHi
                }
                // cv2.inRange is INCLUSIVE on both bounds.
                if (hueOk && ss >= sLo && ss <= sHi && vv >= vLo && vv <= vHi) count++
                k++
            }

            val ratio = if (area > 0) count.toFloat() / area.toFloat() else 0.0f
            // `>=`, not `>` — matching zone_fires_on_frame and the shader's
            // step(min_ratio, ratio). A 0-area rect yields ratio 0.0 and is fed
            // through the same test rather than special-cased.
            out[i] = ratio >= minRatio
        }
        return out
    }
}
