package team.warden.mobile

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

// Story 12.2 — ReactPackage exposing WardenDetectionEngineModule.
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
// Registered in MainApplication.kt by the plugin's anchor patch, which THROWS on
// drift (a silently-skipped registration presents as "the native module is null"
// three layers from the cause).
class WardenDetectionEnginePackage : ReactPackage {
    override fun createNativeModules(
        reactContext: ReactApplicationContext,
    ): List<NativeModule> = listOf(WardenDetectionEngineModule(reactContext))

    override fun createViewManagers(
        reactContext: ReactApplicationContext,
    ): List<ViewManager<*, *>> = emptyList()
}
