package team.warden.mobile

import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.modules.core.DeviceEventManagerModule
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicReference

// Story 12.2 — the RN bridge. A THIN TRIGGER, nothing else.
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// AC0a's closing clause: "the engine Kotlin MUST be written RN-agnostic (a plain
// class plus a thin trigger), so the measurement code and the future runtime
// module are the same code." Every line of engine logic lives in
// WardenDetectionEngine / WardenRulePacker / WardenKeyframeDecoder /
// WardenCpuBaseline / WardenEngineBench, none of which import React Native. This
// file only marshals arguments and hands back JSON.
//
// Legacy bridge ReactPackage + @ReactMethod + Promise, matching the Story 1.2
// precedent (WardenProcessingModule). NOT a TurboModule: there is no codegen spec
// anywhere in the repo, and amendment 5d's real constraint is THREAD affinity,
// not the module system (AC16). Recorded as an explicit decision per Dev Notes.
//
// AC18b — sole access is via apps/mobile/src/shared/services/detectionEngine.ts.
// No feature module imports NativeModules.WardenDetectionEngine directly.
class WardenDetectionEngineModule(
    private val reactContext: ReactApplicationContext,
) : ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String = "WardenDetectionEngine"

    /**
     * Story 12.4c AC1/AC0a — **THE PRODUCTION DETECTION CALL.** One crossing per
     * session; the per-keyframe loop never leaves Kotlin.
     *
     * Resolves with [WardenSessionAnalyzer]'s report as a JSON string: the rule
     * index (`refs`) and one fire-bit row per keyframe. Scoring and phase
     * resolution are the TypeScript side's (AC0b), so nothing here interprets a
     * bit.
     *
     * Progress arrives as [EVENT_PROGRESS] device events carrying the same
     * `requestId`, because a multi-minute call with a single 0 -> 100 jump would
     * regress the one thing the user actually watches (AC7).
     *
     * Cancellable via [cancelAnalysis] with the same `requestId`: a user can
     * leave the screen mid-run, and a codec left holding a 2 GB file open is not
     * an option. Cancellation is COOPERATIVE — polled once per keyframe — which
     * bounds the latency at one keyframe (~8 ms) and keeps the decoder's own
     * `use {}` teardown on the normal path.
     */
    @ReactMethod
    fun analyzeSession(
        requestId: String,
        videoPath: String,
        configJson: String,
        limit: Int,
        promise: Promise,
    ) {
        // A session analysis and a bench run would contend for the decoder, the
        // machine's clocks and (for the bench) a fixed set of artifact filenames.
        // The analysis takes its OWN latch and additionally refuses while a bench
        // is in flight, rather than sharing one: the bench's rejection message is
        // about corrupted measurements, which is not what a user pressing
        // "process" needs to be told.
        if (benchInFlight.get()) {
            promise.reject(
                "WARDEN_BENCH_BUSY",
                "a bench run is in flight; a session analysis would contend with it " +
                    "for the decoder and the machine's sustained clocks"
            )
            return
        }
        if (!analysisInFlight.compareAndSet(false, true)) {
            promise.reject(
                "WARDEN_ANALYSIS_BUSY",
                "a session analysis is already in flight (request ${activeRequestId.get()}). " +
                    "The pipeline runs one session at a time; a second concurrent decode " +
                    "would halve the throughput of both and double peak memory."
            )
            return
        }
        activeRequestId.set(requestId)
        cancelRequested.set(false)

        Thread({
            try {
                val report = WardenSessionAnalyzer(videoPath, configJson).analyze(
                    limit = limit,
                    onProgress = { done, total -> emitProgress(requestId, done, total) },
                    isCancelled = { cancelRequested.get() },
                )
                promise.resolve(report.toString())
            } catch (cancelled: WardenAnalysisCancelledException) {
                // A distinct code, because "the user left the screen" is not a
                // failure the pipeline should mark the session `error` for.
                promise.reject(WardenSessionAnalyzer.CANCELLED, cancelled.message, cancelled)
            } catch (t: Throwable) {
                val code =
                    if (t.message?.contains(WardenSessionAnalyzer.UNSUPPORTED_GEOMETRY) == true)
                        WardenSessionAnalyzer.UNSUPPORTED_GEOMETRY
                    else "WARDEN_ANALYSIS_FAILED"
                promise.reject(code, t.message, t)
            } finally {
                // 🔴 The latch is released in `finally` on EVERY path — including
                // cancellation and an unsupported-geometry throw. A stuck latch
                // presents as "the app will never process another video again",
                // which is indistinguishable from a dead native module.
                cancelRequested.set(false)
                activeRequestId.set(null)
                analysisInFlight.set(false)
            }
        }, "warden-session-analysis").start()
    }

    /**
     * Request cancellation of the in-flight analysis.
     *
     * Resolves `true` when the request matched the run in flight, `false` when
     * there was nothing to cancel or a DIFFERENT run is in flight — never
     * rejects, and never cancels somebody else's run because a stale screen
     * unmounted late.
     */
    @ReactMethod
    fun cancelAnalysis(requestId: String, promise: Promise) {
        val active = activeRequestId.get()
        if (active != null && active == requestId) {
            cancelRequested.set(true)
            promise.resolve(true)
        } else {
            promise.resolve(false)
        }
    }

    private fun emitProgress(requestId: String, done: Int, total: Int) {
        try {
            val payload = Arguments.createMap().apply {
                putString("requestId", requestId)
                putInt("keyframesDone", done)
                putInt("keyframesTotal", total)
            }
            reactContext
                .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
                .emit(EVENT_PROGRESS, payload)
        } catch (t: Throwable) {
            // Progress is advisory. A dead JS context (the app was killed while
            // the FGS kept us alive) must not abort an analysis that is otherwise
            // fine, and must not replace the real error on the way out.
            Log.w("WardenEngineBridge", "progress emit failed: ${t.message}")
        }
    }

    /**
     * NativeEventEmitter calls these on the JS side. On a LEGACY bridge module
     * they are not provided for you, and their absence logs
     * "`new NativeEventEmitter()` was called with a non-null argument without the
     * required `addListener` method" on every subscribe — a warning that reads
     * like a broken module. There is no per-listener state to keep: the emitter
     * is fire-and-forget and the run's lifetime is owned by [analyzeSession].
     */
    @ReactMethod
    fun addListener(@Suppress("UNUSED_PARAMETER") eventName: String) = Unit

    @ReactMethod
    fun removeListeners(@Suppress("UNUSED_PARAMETER") count: Double) = Unit

    /**
     * Runs the bench off the JS thread and resolves with the report JSON.
     *
     * Runs on a plain worker thread and never touches the RN thread. Pre-12.4b
     * that was AC16's finding about EGL thread affinity; with the GPU arm gone the
     * reason is simply that a multi-minute decode must not block JS.
     *
     * Story 12.4c dropped the inert 4th argument (`cpuFrames`) — see
     * [WardenEngineBench.runAll].
     */
    @ReactMethod
    fun runBench(mode: String, video: String?, limit: Int, promise: Promise) {
        // 🔴 REVIEW 2026-09-15: two overlapping runs both wrote report_<mode>.json,
        // parity_fires.json, rules_lut_device.f32 and timing_fires_*.json into the
        // same directory — interleaved artifacts, and two runs contending for the
        // machine while each claims to measure sustained clocks. A bench is a
        // singleton by nature. (Pre-12.4b each also spawned its own EGL context;
        // the artifact collision and the clock contention outlive the GPU arm.)
        if (analysisInFlight.get()) {
            promise.reject(
                "WARDEN_ANALYSIS_BUSY",
                "a session analysis is in flight; benching against it would measure " +
                    "two decoders competing for the same hardware"
            )
            return
        }
        if (!benchInFlight.compareAndSet(false, true)) {
            promise.reject(
                "WARDEN_BENCH_BUSY",
                "a bench run is already in flight; its artifacts and its GPU timings " +
                    "would both be corrupted by a second concurrent run"
            )
            return
        }
        Thread({
            try {
                val report = WardenEngineBench(reactContext.applicationContext)
                    .runAll(mode, video, limit)
                promise.resolve(report.toString())
            } catch (t: Throwable) {
                promise.reject("WARDEN_BENCH_FAILED", t.message, t)
            } finally {
                benchInFlight.set(false)
            }
        }, "warden-bench-bridge").start()
    }

    /**
     * The device profile — cheap enough to call from JS without a full bench run.
     *
     * 🔴 STORY 12.4b RE-POINTED THIS AT A GL-FREE PROFILE. It used to open an
     * offscreen EGL context purely to read GL_RENDERER / GL_VERSION and compile-probe
     * `GL_OES_EGL_image_external_essl3`, because Path Z's availability turned on
     * them. architecture.md Decision #13 rejected the GPU engine, so there is no
     * context to create and no extension whose absence changes anything.
     *
     * What it reports now is what the BOUND path rests on: SoC, API level, thermal
     * state, and the MediaCodec decoder's identity and colour formats — the last of
     * which decides whether `COLOR_FormatYUV420Flexible`, and therefore
     * WardenColorConvert, works on this device at all.
     *
     * Still off the JS thread, still safe to call repeatedly, and now genuinely
     * cheap: it allocates nothing and touches no GPU. Passing a null video path
     * keeps it off the decoder entirely; Story 12.4c decides whether the production
     * caller wants the `mediacodec` block.
     */
    @ReactMethod
    fun describeDevice(promise: Promise) {
        Thread({
            try {
                val bench = WardenEngineBench(reactContext.applicationContext)
                promise.resolve(bench.deviceProfile(null).toString())
            } catch (t: Throwable) {
                promise.reject("WARDEN_DEVICE_PROBE_FAILED", t.message, t)
            }
        }, "warden-device-probe").start()
    }

    companion object {
        /**
         * Process-wide guard: the bench owns a fixed set of artifact filenames and
         * the machine's sustained clocks, so exactly one run may be in flight.
         * [WardenEngineBenchActivity] takes the same latch.
         */
        @JvmStatic
        val benchInFlight = AtomicBoolean(false)

        /**
         * Story 12.4c — the production analysis's own latch, process-wide for the
         * same reason: one decoder, one set of sustained clocks. Separate from
         * [benchInFlight] so each side can say WHY it refused, and so a crashed
         * bench can never make the shipped pipeline unusable (or vice versa).
         */
        @JvmStatic
        val analysisInFlight = AtomicBoolean(false)

        private val activeRequestId = AtomicReference<String?>(null)
        private val cancelRequested = AtomicBoolean(false)

        /** Device-event name for analysis progress. Mirrored in detectionEngine.ts. */
        const val EVENT_PROGRESS = "WardenDetectionEngineProgress"
    }
}
