package team.warden.mobile

import android.opengl.EGL14
import android.opengl.EGLConfig
import android.opengl.EGLContext
import android.opengl.EGLDisplay
import android.opengl.EGLSurface
import android.opengl.GLES30
import android.util.Log

// Story 12.2 — EGL/GLES plumbing shared by the engine and the bench.
// Generated by apps/mobile/plugins/with-detection-engine.js; the tracked source
// is apps/mobile/plugins/kotlin/. Do NOT edit the prebuild-generated copy —
// `expo prebuild --clean` erases it and git never sees it (AC18a).
//
// RN-agnostic by construction (AC0a): nothing in this file imports React
// Native, so the measurement code and the future runtime module are the same
// code.

private const val TAG = "WardenGl"

/** A GL call failed. Carries the enum symbolically — 0x502 tells you nothing. */
class WardenGlException(message: String) : RuntimeException(message)

object WardenGlUtil {

    fun glErrorString(code: Int): String = when (code) {
        GLES30.GL_NO_ERROR -> "GL_NO_ERROR"
        GLES30.GL_INVALID_ENUM -> "GL_INVALID_ENUM"
        GLES30.GL_INVALID_VALUE -> "GL_INVALID_VALUE"
        GLES30.GL_INVALID_OPERATION -> "GL_INVALID_OPERATION"
        GLES30.GL_INVALID_FRAMEBUFFER_OPERATION -> "GL_INVALID_FRAMEBUFFER_OPERATION"
        GLES30.GL_OUT_OF_MEMORY -> "GL_OUT_OF_MEMORY"
        else -> "0x%04X".format(code)
    }

    /**
     * AC7 — GL failures are SILENT BY NATURE. Assert the plumbing before
     * trusting a single number.
     *
     * 12.1's most expensive lesson was a GL_RGBA8UI-vs-GL_RGBA8 mismatch that
     * raised nothing, returned uninitialized memory that looked like plausible
     * detections (0.35 / 0.31 / 0.05), and read as "the port is broken" rather
     * than "the format is wrong". It cost a full accuracy run. Every state
     * transition in this port is followed by a check.
     */
    fun checkGl(where: String) {
        // Drain the whole error queue: GL keeps a set of flags, and reading one
        // leaves the others set to mislead the NEXT check.
        var first = GLES30.GL_NO_ERROR
        val all = StringBuilder()
        while (true) {
            val e = GLES30.glGetError()
            if (e == GLES30.GL_NO_ERROR) break
            if (first == GLES30.GL_NO_ERROR) first = e
            all.append(glErrorString(e)).append(' ')
            if (all.length > 200) break // pathological driver; do not spin
        }
        if (first != GLES30.GL_NO_ERROR) {
            throw WardenGlException("GL error after $where: ${all.toString().trim()}")
        }
    }

    fun compileShader(type: Int, source: String, label: String): Int {
        val id = GLES30.glCreateShader(type)
        if (id == 0) throw WardenGlException("glCreateShader returned 0 for $label")
        GLES30.glShaderSource(id, source)
        GLES30.glCompileShader(id)
        val status = IntArray(1)
        GLES30.glGetShaderiv(id, GLES30.GL_COMPILE_STATUS, status, 0)
        if (status[0] == 0) {
            val log = GLES30.glGetShaderInfoLog(id)
            GLES30.glDeleteShader(id)
            throw WardenGlException("$label failed to compile:\n$log")
        }
        return id
    }

    fun linkProgram(vertexSrc: String, fragmentSrc: String): Int {
        val vs = compileShader(GLES30.GL_VERTEX_SHADER, vertexSrc, "vertex shader")
        val fs: Int
        try {
            fs = compileShader(GLES30.GL_FRAGMENT_SHADER, fragmentSrc, "fragment shader")
        } catch (t: Throwable) {
            GLES30.glDeleteShader(vs)
            throw t
        }
        val program = GLES30.glCreateProgram()
        if (program == 0) {
            GLES30.glDeleteShader(vs); GLES30.glDeleteShader(fs)
            throw WardenGlException("glCreateProgram returned 0")
        }
        GLES30.glAttachShader(program, vs)
        GLES30.glAttachShader(program, fs)
        GLES30.glLinkProgram(program)
        // Shaders are reference-counted by the program; detach+delete now so a
        // later failure cannot leak them.
        GLES30.glDetachShader(program, vs); GLES30.glDeleteShader(vs)
        GLES30.glDetachShader(program, fs); GLES30.glDeleteShader(fs)
        val status = IntArray(1)
        GLES30.glGetProgramiv(program, GLES30.GL_LINK_STATUS, status, 0)
        if (status[0] == 0) {
            val log = GLES30.glGetProgramInfoLog(program)
            GLES30.glDeleteProgram(program)
            throw WardenGlException("program failed to link:\n$log")
        }
        return program
    }
}

/**
 * An offscreen EGL context on the CALLING thread.
 *
 * AC16 — this is the object that makes amendment 5d's re-derivation concrete.
 * EGL contexts are **thread-bound**: `eglMakeCurrent` binds a context to the
 * thread that calls it, and every GL call must come from that thread. That is a
 * different constraint from "the JSI binding cannot cross the headless context
 * boundary", which is what architecture.md:2047 currently rests on.
 *
 * A pbuffer surface is used rather than a window surface precisely to prove the
 * point: no Activity, no SurfaceView, no UI thread is required — the context can
 * live entirely on a worker thread, which is what a Foreground Service host
 * needs.
 */
class WardenEglContext private constructor(
    private val display: EGLDisplay,
    private val context: EGLContext,
    private val surface: EGLSurface,
    val ownerThreadId: Long,
    val ownerThreadName: String,
) {
    companion object {
        /** Creates and makes current an offscreen context on THIS thread. */
        fun createOffscreen(width: Int = 1, height: Int = 1): WardenEglContext {
            val display = EGL14.eglGetDisplay(EGL14.EGL_DEFAULT_DISPLAY)
            if (display == EGL14.EGL_NO_DISPLAY) {
                throw WardenGlException("eglGetDisplay failed")
            }
            val version = IntArray(2)
            if (!EGL14.eglInitialize(display, version, 0, version, 1)) {
                throw WardenGlException("eglInitialize failed")
            }
            // EGL_PBUFFER_BIT + ES2_BIT: ES3 contexts are requested via
            // EGL_CONTEXT_CLIENT_VERSION 3 and advertise ES2_BIT in the config
            // (there is no EGL_OPENGL_ES3_BIT in base EGL 1.4).
            val attribs = intArrayOf(
                EGL14.EGL_RENDERABLE_TYPE, EGL14.EGL_OPENGL_ES2_BIT,
                EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,
                EGL14.EGL_RED_SIZE, 8,
                EGL14.EGL_GREEN_SIZE, 8,
                EGL14.EGL_BLUE_SIZE, 8,
                EGL14.EGL_ALPHA_SIZE, 8,
                EGL14.EGL_DEPTH_SIZE, 0,
                EGL14.EGL_STENCIL_SIZE, 0,
                EGL14.EGL_NONE
            )
            val configs = arrayOfNulls<EGLConfig>(1)
            val numConfigs = IntArray(1)
            if (!EGL14.eglChooseConfig(display, attribs, 0, configs, 0, 1, numConfigs, 0) ||
                numConfigs[0] == 0
            ) {
                EGL14.eglTerminate(display)
                throw WardenGlException("eglChooseConfig found no RGBA8 pbuffer config")
            }
            val ctxAttribs = intArrayOf(EGL14.EGL_CONTEXT_CLIENT_VERSION, 3, EGL14.EGL_NONE)
            val context = EGL14.eglCreateContext(
                display, configs[0], EGL14.EGL_NO_CONTEXT, ctxAttribs, 0
            )
            if (context == EGL14.EGL_NO_CONTEXT) {
                EGL14.eglTerminate(display)
                throw WardenGlException("eglCreateContext failed for ES 3 (error 0x%04X)".format(EGL14.eglGetError()))
            }
            val surfAttribs = intArrayOf(
                EGL14.EGL_WIDTH, width, EGL14.EGL_HEIGHT, height, EGL14.EGL_NONE
            )
            val surface = EGL14.eglCreatePbufferSurface(display, configs[0], surfAttribs, 0)
            if (surface == EGL14.EGL_NO_SURFACE) {
                EGL14.eglDestroyContext(display, context)
                EGL14.eglTerminate(display)
                throw WardenGlException("eglCreatePbufferSurface failed")
            }
            if (!EGL14.eglMakeCurrent(display, surface, surface, context)) {
                EGL14.eglDestroySurface(display, surface)
                EGL14.eglDestroyContext(display, context)
                EGL14.eglTerminate(display)
                throw WardenGlException("eglMakeCurrent failed")
            }
            val t = Thread.currentThread()
            Log.i(TAG, "EGL context current on thread '${t.name}' (id=${t.id}), EGL ${version[0]}.${version[1]}")
            return WardenEglContext(display, context, surface, t.id, t.name)
        }
    }

    /** AC1 — the device profile, read from a CURRENT context (AC2's requirement). */
    fun describe(): Map<String, String> = mapOf(
        "GL_VENDOR" to (GLES30.glGetString(GLES30.GL_VENDOR) ?: ""),
        "GL_RENDERER" to (GLES30.glGetString(GLES30.GL_RENDERER) ?: ""),
        "GL_VERSION" to (GLES30.glGetString(GLES30.GL_VERSION) ?: ""),
        "GL_SHADING_LANGUAGE_VERSION" to
            (GLES30.glGetString(GLES30.GL_SHADING_LANGUAGE_VERSION) ?: ""),
        "GL_EXTENSIONS" to (GLES30.glGetString(GLES30.GL_EXTENSIONS) ?: ""),
    )

    fun extensions(): Set<String> =
        (GLES30.glGetString(GLES30.GL_EXTENSIONS) ?: "").split(" ")
            .filter { it.isNotBlank() }.toSet()

    fun hasExtension(name: String): Boolean = extensions().contains(name)

    fun release() {
        EGL14.eglMakeCurrent(
            display, EGL14.EGL_NO_SURFACE, EGL14.EGL_NO_SURFACE, EGL14.EGL_NO_CONTEXT
        )
        EGL14.eglDestroySurface(display, surface)
        EGL14.eglDestroyContext(display, context)
        EGL14.eglReleaseThread()
        EGL14.eglTerminate(display)
    }
}
