package team.warden.mobile

import android.graphics.SurfaceTexture
import android.media.MediaCodec
import android.media.MediaCodecInfo
import android.media.MediaExtractor
import android.media.MediaFormat
import android.os.Handler
import android.os.HandlerThread
import android.util.Log
import android.view.Surface
import java.nio.ByteBuffer

// Story 12.2 AC0b — keyframe-only decode. `-skip_frame nokey` has NO MediaCodec
// equivalent flag; this is the analogue, and it is the largest NEW engineering
// surface in the story (everything else is a port).
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// AC0b verdict: **Option A + Option C control** (Stephane, 2026-09-15), with
// Option A AMENDED ON EVIDENCE — see below.
//   A  — as specified: MediaExtractor.seekTo(t, SEEK_TO_NEXT_SYNC) in a loop,
//        feeding only sync samples. **ABANDONED, MEASURED DEFECT**: on the 2.3 GB
//        / 4419 s capture this device's `seekTo` stops advancing after the SECOND
//        sync sample, yielding 2 keyframes against a ground truth of 1061.
//   A' — what shipped: a SINGLE FORWARD PASS over the sample table, queueing only
//        samples flagged SAMPLE_FLAG_SYNC and skipping the rest with `advance()`.
//        NOTE: `advance()` is NOT free and is NOT metadata-only -- see
//        countSyncSamplesByScan. This is a CLOSER analogue of
//        `-skip_frame nokey` than the seek loop, because FFmpeg does not seek
//        either — it demuxes every packet and tells the decoder to skip
//        non-keyframes. It also removes the per-keyframe seek + flush +
//        END_OF_STREAM round-trip entirely, and its correctness does not depend
//        on seeking working at all.
//   C  — the ffmpeg-kit control (WardenEngineBench), running 12.1's LITERAL
//        `-skip_frame nokey` on device for a directly comparable decode number.
//   B  — full decode + BUFFER_FLAG_KEY_FRAME filtering was NOT taken: it decodes
//        everything, which is the `select='eq(pict_type,I)'` mistake 12.1
//        measured at 5.4x slower on PC for zero decode saving.
//
// 🔴 THE COUNT ASSERTION EARNED ITS KEEP. The decoded keyframe count is asserted
// against a ground-truth sample-table scan (NOT against the seek scan, which is
// the thing that was wrong). Had the loop trusted the seek scan, the bench would
// have reported a perfectly self-consistent `2 == 2` and a beautiful
// ms/keyframe figure computed over two frames. 12.1's analogue caught a
// CFR-duplication regression the same way.

private const val TAG = "WardenDecoder"

/** One decoded keyframe's payload, in whichever form the colour path needs. */
class WardenKeyframe(
    val presentationTimeUs: Long,
    val width: Int,
    val height: Int,
    /** Path P only: Y/U/V planes + their strides. Null on the Surface path. */
    val planes: Array<ByteBuffer>? = null,
    val rowStrides: IntArray? = null,
    val pixelStrides: IntArray? = null,
)

data class WardenDecoderProfile(
    val codecName: String,
    val isHardwareAccelerated: Boolean,
    val mime: String,
    val width: Int,
    val height: Int,
    val durationUs: Long,
    val syncSampleCount: Int,
    val supportedColorFormats: List<Int>,
)

class WardenKeyframeDecoder(
    private val path: String,
    private val toSurface: Surface?,
) : AutoCloseable {

    private val extractor = MediaExtractor()
    private var codec: MediaCodec? = null
    private var trackIndex = -1
    private lateinit var format: MediaFormat

    var profile: WardenDecoderProfile? = null
        private set

    /** Accumulated nanoseconds spent inside decode, for the AC11 stage split. */
    var decodeNs: Long = 0
        private set

    init {
        extractor.setDataSource(path)
        for (i in 0 until extractor.trackCount) {
            val f = extractor.getTrackFormat(i)
            if (f.getString(MediaFormat.KEY_MIME)?.startsWith("video/") == true) {
                trackIndex = i
                format = f
                break
            }
        }
        require(trackIndex >= 0) { "no video track in $path" }
        extractor.selectTrack(trackIndex)
    }

    /**
     * AC0b's binding assertion + AC1's decoder profile.
     *
     * Walks the sync-sample index WITHOUT decoding anything, which is both the
     * ground truth for the keyframe count and the PTS list the decode loop
     * consumes.
     *
     * 🔴 REVIEW 2026-09-15: that walk is a **62 s full-file read**, not an index
     * scan (see [countSyncSamplesByScan]). It used to run unconditionally, so an
     * `all` run paid it TWICE — once here via `deviceProfile`, once in the timing
     * block — and only the second was timed and reported, silently under-reporting
     * ~62 s of a run whose headline deliverable is 35 s. Callers that already hold
     * the ground truth now pass it in via [knownSyncCount]; callers that want the
     * profile WITHOUT the scan pass [scanSyncSamples] = false.
     *
     * @param scanSyncSamples run the 62 s ground-truth walk. When false,
     *   [WardenDecoderProfile.syncSampleCount] carries [knownSyncCount] verbatim.
     * @param knownSyncCount a previously measured ground truth, or -1 for unknown.
     */
    fun probe(
        scanSyncSamples: Boolean = true,
        knownSyncCount: Int = -1,
    ): WardenDecoderProfile {
        val syncCount = if (scanSyncSamples) countSyncSamplesByScan() else knownSyncCount
        val mime = format.getString(MediaFormat.KEY_MIME)!!
        val codecName: String
        val hw: Boolean
        val colorFormats: List<Int>
        // Instantiating the codec is the only way to learn its NAME and whether
        // it is hardware-accelerated; MediaCodecList's "preferred" answer can
        // differ from what createDecoderByType actually hands back.
        val probeCodec = MediaCodec.createDecoderByType(mime)
        try {
            codecName = probeCodec.name
            val info: MediaCodecInfo = probeCodec.codecInfo
            hw = if (android.os.Build.VERSION.SDK_INT >= 29) info.isHardwareAccelerated else
                // Pre-29 heuristic: AOSP software decoders carry these prefixes.
                !(codecName.startsWith("OMX.google.") || codecName.startsWith("c2.android."))
            colorFormats = info.getCapabilitiesForType(mime).colorFormats.toList()
        } finally {
            probeCodec.release()
        }
        val p = WardenDecoderProfile(
            codecName = codecName,
            isHardwareAccelerated = hw,
            mime = mime,
            width = format.getInteger(MediaFormat.KEY_WIDTH),
            height = format.getInteger(MediaFormat.KEY_HEIGHT),
            durationUs = if (format.containsKey(MediaFormat.KEY_DURATION))
                format.getLong(MediaFormat.KEY_DURATION) else -1L,
            syncSampleCount = syncCount,
            supportedColorFormats = colorFormats,
        )
        profile = p
        Log.i(TAG, "decoder=$codecName hw=$hw sync samples=$syncCount")
        return p
    }

    /**
     * 🔴 Ground-truth sync-sample count, by walking the sample table.
     *
     * The seek-based scan AC0b Option A prescribes — `seekTo(t + 1,
     * SEEK_TO_NEXT_SYNC)` in a loop — is NOT reliable on this file/device.
     * MEASURED: it terminates after **2** sync samples on the 2.3 GB / 4419 s
     * capture, against an ffprobe ground truth of **1061** at a dead-regular
     * 4.1667 s GOP. `MediaExtractor.seekTo` simply stops advancing past the
     * second sync point here.
     *
     * That is precisely why AC0b made the count assertion binding rather than
     * decorative: had the decode loop trusted the seek scan, the bench would have
     * reported a perfectly self-consistent `2 == 2` and a beautiful ms/keyframe
     * figure computed over two frames.
     *
     * 🔴 CORRECTED 2026-09-15 — THIS WALK IS **NOT** CHEAP AND **NOT**
     * METADATA-ONLY. An earlier version of this comment claimed `advance()`
     * merely parses the sample table. That is false:
     * `NuMediaExtractor::fetchTrackSamples` READS SAMPLE DATA on every
     * `advance()` as well as on every `seekTo`, in batches of up to
     * `mMaxFetchCount = 8` for video tracks. So this walk pulls the whole 2.3 GB
     * through the extractor.
     *
     * MEASURED COST: **62 s**. It is a bench-time correctness assertion and
     * **MUST NEVER RUN IN PRODUCTION** — it alone would cost nearly twice the
     * entire 35 s analysis. Story 12.4 must take the keyframe index from
     * [syncSamplePtsListBySeek] (2.3 s) or from a direct `stss` read, never from
     * here.
     */
    fun countSyncSamplesByScan(): Int {
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        var n = 0
        while (extractor.sampleTime >= 0) {
            if (extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC != 0) n++
            if (!extractor.advance()) break
        }
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        return n
    }

    /**
     * DIAGNOSTIC — does `seekTo` work when given ABSOLUTE targets?
     *
     * The incremental form (`seekTo(lastPts + 1, SEEK_TO_NEXT_SYNC)`) stops
     * advancing after the second sync sample on this file. Before accepting the
     * much more expensive single-pass demux as the only option, this checks
     * whether seeking is broken outright or only in that incremental pattern —
     * the difference is worth ~an order of magnitude on the headline decode
     * number, so it is worth one experiment rather than an assumption.
     */
    fun seekProbe(gopUs: Long, n: Int): List<Long> {
        val out = ArrayList<Long>(n)
        for (k in 0 until n) {
            extractor.seekTo(k * gopUs, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            out.add(extractor.sampleTime)
        }
        return out
    }

    /**
     * DIAGNOSTIC (§6 of the keyframe-decode-perf research) — where do the 33 ms go?
     *
     * The research derives, WITHOUT instrumentation, that ~25.7 ms of the 32.9 ms
     * seek-strategy cost is `flush()` + the `END_OF_STREAM` drain + pipeline
     * restart, and only ~4.3 ms is actual decoding. That derivation rests on
     * `250 x 0.234 ms` of demux in strategy A-prime, which in turn rests on the
     * 62.1 s full sample-table walk. It is arithmetic on two measurements, not a
     * measurement — so it is falsifiable, and this falsifies or confirms it
     * before a single line of the decode loop is rewritten.
     *
     * Runs the CURRENT strategy-A loop unchanged in structure, timing each stage
     * separately. The prediction under test: **flush alone lands in 15-25 ms.**
     * If it does not, the decomposition is wrong and the rewrite is unjustified.
     */
    fun decodeProbe(ptsList: LongArray, n: Int): Map<String, Any> {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()

        val seekNs = ArrayList<Long>(n)
        val flushNs = ArrayList<Long>(n)
        val queueToOutNs = ArrayList<Long>(n)
        var tryAgainCount = 0L
        var tryAgainNs = 0L
        var decoded = 0

        val readBefore = procSelfIoReadBytes()
        val target = minOf(n, ptsList.size)
        val wall0 = System.nanoTime()

        for (idx in 0 until target) {
            val pts = ptsList[idx]

            var t = System.nanoTime()
            extractor.seekTo(pts, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            seekNs.add(System.nanoTime() - t)

            // (1) flush() ALONE — the headline number this probe exists for.
            t = System.nanoTime()
            c.flush()
            flushNs.add(System.nanoTime() - t)

            var sampleQueued = false
            var eosQueued = false
            var got = false
            var spins = 0
            var queuedAt = 0L

            while (!got) {
                if (!eosQueued) {
                    val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                    if (inIdx >= 0) {
                        if (!sampleQueued) {
                            val buf = c.getInputBuffer(inIdx)!!
                            val size = extractor.readSampleData(buf, 0)
                            if (size < 0) {
                                c.queueInputBuffer(inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                                eosQueued = true
                            } else {
                                // (2) clock starts when the IDR enters the codec.
                                queuedAt = System.nanoTime()
                                c.queueInputBuffer(
                                    inIdx, 0, size, extractor.sampleTime,
                                    MediaCodec.BUFFER_FLAG_KEY_FRAME
                                )
                                sampleQueued = true
                            }
                        } else {
                            c.queueInputBuffer(inIdx, 0, 0, pts, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                            eosQueued = true
                        }
                    }
                }
                // (3) every INFO_TRY_AGAIN_LATER is a potential TIMEOUT_US-long sleep.
                val t2 = System.nanoTime()
                val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
                when {
                    outIdx >= 0 -> {
                        val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                        if (info.size > 0 || (toSurface != null && !eos)) {
                            if (queuedAt != 0L) queueToOutNs.add(System.nanoTime() - queuedAt)
                            c.releaseOutputBuffer(outIdx, false)
                            decoded++
                            got = true
                        } else {
                            c.releaseOutputBuffer(outIdx, false)
                            if (eos) got = true
                        }
                    }
                    outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                        tryAgainCount++
                        tryAgainNs += System.nanoTime() - t2
                        if (++spins > MAX_SPINS) throw IllegalStateException("probe stalled at $idx")
                    }
                }
            }
        }
        val wallNs = System.nanoTime() - wall0
        val readAfter = procSelfIoReadBytes()

        fun med(v: List<Long>): Double {
            if (v.isEmpty()) return 0.0
            val s = v.sorted(); val m = s.size / 2
            return (if (s.size % 2 == 1) s[m].toDouble() else (s[m - 1] + s[m]) / 2.0) / 1e6
        }
        fun mean(v: List<Long>) = if (v.isEmpty()) 0.0 else v.sum() / 1e6 / v.size

        return linkedMapOf(
            "keyframes" to decoded,
            "wall_ms_per_keyframe" to wallNs / 1e6 / maxOf(1, decoded),
            "seek_ms_median" to med(seekNs),
            "seek_ms_mean" to mean(seekNs),
            "flush_ms_median" to med(flushNs),
            "flush_ms_mean" to mean(flushNs),
            "flush_ms_max" to (flushNs.maxOrNull() ?: 0L) / 1e6,
            "queue_to_first_output_ms_median" to med(queueToOutNs),
            "queue_to_first_output_ms_mean" to mean(queueToOutNs),
            "try_again_count_total" to tryAgainCount,
            "try_again_per_keyframe" to tryAgainCount.toDouble() / maxOf(1, decoded),
            "try_again_ms_total" to tryAgainNs / 1e6,
            "try_again_ms_per_keyframe" to tryAgainNs / 1e6 / maxOf(1, decoded),
            "timeout_us_used" to TIMEOUT_US,
            "read_bytes_delta" to (readAfter - readBefore),
            "read_mb_per_keyframe" to (readAfter - readBefore) / 1048576.0 / maxOf(1, decoded),
            "prediction_under_test" to
                "research §2 derives flush+drain ~= 25.7 ms/kf and real decode ~= 4.3 ms. " +
                "If flush_ms_median is NOT in 15-25 ms, the decomposition is refuted.",
        )
    }

    /**
     * `flush()` back-to-back on an otherwise idle codec, for contrast with the
     * in-loop figure. If the in-loop flush is expensive but the idle flush is
     * cheap, the cost is draining in-flight work rather than the HFI round trip
     * itself — a different fix.
     */
    fun flushOnlyProbe(reps: Int): Map<String, Any> {
        configureCodec()
        val c = codec!!
        val ns = ArrayList<Long>(reps)
        for (i in 0 until reps) {
            val t = System.nanoTime()
            c.flush()
            ns.add(System.nanoTime() - t)
        }
        val s = ns.sorted()
        return linkedMapOf(
            "reps" to reps,
            "idle_flush_ms_median" to s[s.size / 2] / 1e6,
            "idle_flush_ms_mean" to ns.sum() / 1e6 / ns.size,
            "idle_flush_ms_max" to s.last() / 1e6,
        )
    }

    /** Bytes this process has actually read from storage. -1 if unreadable. */
    private fun procSelfIoReadBytes(): Long = try {
        java.io.File("/proc/self/io").readLines()
            .firstOrNull { it.startsWith("read_bytes:") }
            ?.substringAfter(':')?.trim()?.toLong() ?: -1L
    } catch (t: Throwable) { -1L }

    /**
     * The keyframe PTS list, built with ABSOLUTE `SEEK_TO_CLOSEST_SYNC` seeks.
     *
     * MEASURED on this device: `SEEK_TO_CLOSEST_SYNC` with an absolute target is
     * correct and costs ~2.9 ms, while the incremental
     * `SEEK_TO_NEXT_SYNC(lastPts + 1)` pattern stops advancing after the second
     * sync sample. So seeking is not broken — that ONE pattern is.
     *
     * The GOP is estimated from the first two keyframes and then stepped. Any
     * step that fails to advance is treated as the end of a REGULAR GOP
     * assumption, not as the end of the file: the caller still asserts the
     * resulting count against the ground-truth sample-table scan, so an irregular
     * GOP shows up as a mismatch rather than as silently-missing keyframes.
     */
    fun syncSamplePtsListBySeek(maxCount: Int = 100_000): LongArray {
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
        val first = extractor.sampleTime
        if (first < 0) return LongArray(0)
        // Probe the second keyframe to learn the GOP rather than assuming one.
        var gop = -1L
        var probe = 100_000L
        while (probe < 60_000_000L) {
            extractor.seekTo(first + probe, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            val t = extractor.sampleTime
            if (t > first) { gop = t - first; break }
            probe *= 2
        }
        if (gop <= 0) return longArrayOf(first)

        val out = ArrayList<Long>()
        out.add(first)
        var last = first
        var k = 1L
        while (out.size < maxCount) {
            // Seek to the MIDPOINT past the last keyframe: CLOSEST_SYNC then
            // resolves to the next one even if the GOP drifts by up to half a
            // period, which a naive exact-multiple step would not tolerate.
            extractor.seekTo(first + k * gop, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            val t = extractor.sampleTime
            if (t < 0 || t <= last) break
            out.add(t)
            last = t
            k++
        }
        return out.toLongArray()
    }

    /**
     * AC0b Option A — decode by SEEKING to each keyframe.
     *
     * Per keyframe: absolute seek, flush, queue the sample, queue END_OF_STREAM
     * to force the pipeline to drain, collect. Measured against [decodeKeyframes]
     * (the single-pass demux) so the report can state which analogue of
     * `-skip_frame nokey` is actually faster on this device rather than assuming.
     */
    fun decodeKeyframesBySeek(
        ptsList: LongArray,
        limit: Int = 0,
        onFrame: (WardenKeyframe) -> Unit,
    ): Int {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        var decoded = 0
        val target = if (limit > 0) minOf(limit, ptsList.size) else ptsList.size
        val t0 = System.nanoTime()

        for (idx in 0 until target) {
            val pts = ptsList[idx]
            extractor.seekTo(pts, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            // 🔴 REVIEW 2026-09-15 — VERIFY WHERE THE SEEK ACTUALLY LANDED.
            //
            // This loop used to queue whatever `extractor.sampleTime` happened to
            // be after the seek, then increment `decoded`. If the seek landed on a
            // different sync sample — or, worse, on the SAME one as the previous
            // iteration — the same frame was decoded N times and counted as N
            // distinct keyframes, inflating the divisor of every ms_per_keyframe
            // figure while the per-rule fire rows silently repeated under
            // different `pts_us` keys.
            //
            // That is not hypothetical on this device: countSyncSamplesByScan's
            // KDoc documents a `seekTo` here that stops advancing after two sync
            // points. `syncSamplePtsListBySeek` already guards it
            // (`if (t < 0 || t <= last) break`); the decode loop did not. And
            // `keyframe_count_matches` could never catch it, because a repeated
            // landing still increments `decoded` toward `syncCount`.
            val landed = extractor.sampleTime
            if (landed != pts) {
                throw IllegalStateException(
                    "keyframe $idx: seekTo($pts, SEEK_TO_CLOSEST_SYNC) landed on " +
                        "sampleTime=$landed. The decode loop consumes a PTS list built " +
                        "by syncSamplePtsListBySeek, so a mismatch means the extractor " +
                        "is not addressing the sync sample that list names — every " +
                        "downstream per-keyframe figure would be computed over the " +
                        "wrong set of frames."
                )
            }
            if ((extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC) == 0) {
                throw IllegalStateException(
                    "keyframe $idx (pts=$pts): the sample the extractor landed on is " +
                        "NOT flagged SAMPLE_FLAG_SYNC. Decoding a non-sync sample in " +
                        "isolation is undefined — it would reference frames the decoder " +
                        "never saw."
                )
            }
            c.flush()
            // NB: no start() after flush() — see decodeKeyframes.
            var sampleQueued = false
            var eosQueued = false
            var got = false
            var spins = 0
            while (!got) {
                if (!eosQueued) {
                    val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                    if (inIdx >= 0) {
                        if (!sampleQueued) {
                            val buf = c.getInputBuffer(inIdx)!!
                            val size = extractor.readSampleData(buf, 0)
                            if (size < 0) {
                                c.queueInputBuffer(inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                                eosQueued = true
                            } else {
                                c.queueInputBuffer(
                                    inIdx, 0, size, extractor.sampleTime,
                                    MediaCodec.BUFFER_FLAG_KEY_FRAME
                                )
                                sampleQueued = true
                            }
                        } else {
                            c.queueInputBuffer(inIdx, 0, 0, pts, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                            eosQueued = true
                        }
                    }
                }
                val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
                when {
                    outIdx >= 0 -> {
                        val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                        if (info.size > 0 || (toSurface != null && !eos)) {
                            val kf = if (toSurface != null) {
                                WardenKeyframe(info.presentationTimeUs, profileWidth(), profileHeight())
                            } else {
                                imageToKeyframe(c, outIdx, info.presentationTimeUs)
                            }
                            decodeNs = System.nanoTime() - t0
                            c.releaseOutputBuffer(outIdx, toSurface != null)
                            onFrame(kf)
                            decoded++
                            got = true
                        } else {
                            c.releaseOutputBuffer(outIdx, false)
                            if (eos) {
                                throw IllegalStateException(
                                    "keyframe $idx (pts=$pts) drained to END_OF_STREAM with no " +
                                        "decoded frame — that sync point did not decode standalone."
                                )
                            }
                        }
                    }
                    outIdx == MediaCodec.INFO_TRY_AGAIN_LATER ->
                        if (++spins > MAX_SPINS) throw IllegalStateException(
                            "no output for keyframe $idx (pts=$pts) after $MAX_SPINS polls"
                        )
                }
            }
        }
        // 🔴 Same nesting caveat as decodeKeyframes: decodeNs is assigned from t0
        // (loop entry) and snapshotted BEFORE onFrame(), so every GL stage of
        // frames 0..N-2 is inside it. Use timingRun's `decode_excluding_gl` /
        // `gl_total` for a disjoint split.
        return decoded
    }

    private fun configureCodec() {
        val mime = format.getString(MediaFormat.KEY_MIME)!!
        val c = MediaCodec.createDecoderByType(mime)
        if (toSurface == null) {
            // Path P — flexible YUV 4:2:0 so getOutputImage() hands back planes
            // with device-reported strides. NEVER assume rowStride == width.
            format.setInteger(
                MediaFormat.KEY_COLOR_FORMAT,
                MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible
            )
        }
        c.configure(format, toSurface, null, 0)
        c.start()
        codec = c
    }

    /**
     * Decode every keyframe, invoking [onFrame] for each.
     *
     * Returns the number of keyframes decoded. The caller asserts it against
     * [WardenDecoderProfile.syncSampleCount].
     *
     * @param limit stop after this many keyframes (0 = all). Used for warm-up
     *   runs and for the AC3 single-frame diff.
     */
    fun decodeKeyframes(limit: Int = 0, onFrame: (WardenKeyframe) -> Unit): Int {
        // SINGLE FORWARD PASS, sync-filtered — the true `-skip_frame nokey`
        // analogue, and a closer one than the seek loop it replaces.
        //
        // FFmpeg's `-skip_frame nokey` does NOT seek: it demuxes every packet and
        // instructs the decoder to skip non-keyframes. This does exactly that —
        // `advance()` walks past non-sync samples without decoding them, and only
        // sync samples are queued. Consecutive IDR frames decode back-to-back
        // with no flush, so the per-keyframe seek + flush + END_OF_STREAM
        // round-trip disappears entirely.
        //
        // It also sidesteps the measured `seekTo` defect (see
        // countSyncSamplesByScan): correctness here does not depend on seeking
        // working at all.
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        var decoded = 0
        var inputDone = false
        var spins = 0

        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        val t0 = System.nanoTime()

        while (true) {
            if (limit > 0 && decoded >= limit) break

            if (!inputDone) {
                val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                if (inIdx >= 0) {
                    // Skip forward to the next sync sample.
                    // 🔴 `advance()` is NOT metadata-only: NuMediaExtractor reads
                    // sample DATA on each call (up to 8 samples at a time). That
                    // is why this single-pass strategy measured 62.8 ms/keyframe
                    // against the seek strategy's 32.9 — it drags the whole file
                    // through the extractor to reach 1 sample in 250.
                    // 🔴 REVIEW 2026-09-15: `if (!advance()) break` used to exit
                    // this skip loop with a NON-SYNC sample still current, which
                    // was then queued tagged BUFFER_FLAG_KEY_FRAME; `advance()`
                    // failed again on the next pass and the SAME sample was
                    // re-queued forever. `exhausted` turns that into the
                    // end-of-stream it actually is.
                    var exhausted = false
                    while (extractor.sampleTime >= 0 &&
                        extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC == 0
                    ) {
                        if (!extractor.advance()) { exhausted = true; break }
                    }
                    if (exhausted || extractor.sampleTime < 0) {
                        c.queueInputBuffer(
                            inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM
                        )
                        inputDone = true
                    } else {
                        val buf = c.getInputBuffer(inIdx)!!
                        val size = extractor.readSampleData(buf, 0)
                        if (size < 0) {
                            c.queueInputBuffer(
                                inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM
                            )
                            inputDone = true
                        } else {
                            c.queueInputBuffer(
                                inIdx, 0, size, extractor.sampleTime,
                                MediaCodec.BUFFER_FLAG_KEY_FRAME
                            )
                            extractor.advance()
                        }
                    }
                }
            }

            val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
            when {
                outIdx >= 0 -> {
                    spins = 0
                    val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                    if (info.size > 0 || (toSurface != null && !eos)) {
                        val kf = if (toSurface != null) {
                            WardenKeyframe(info.presentationTimeUs, profileWidth(), profileHeight())
                        } else {
                            imageToKeyframe(c, outIdx, info.presentationTimeUs)
                        }
                        decodeNs = System.nanoTime() - t0
                        c.releaseOutputBuffer(outIdx, toSurface != null)
                        onFrame(kf)
                        decoded++
                    } else {
                        c.releaseOutputBuffer(outIdx, false)
                    }
                    if (eos) break
                }
                outIdx == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED ->
                    Log.i(TAG, "output format changed: ${c.outputFormat}")
                outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                    // 🔴 REVIEW 2026-09-15: the spin budget used to be checked ONLY
                    // once `inputDone`, so a codec holding every input buffer
                    // (dequeueInputBuffer returning -1) while producing no output
                    // span forever at 10 ms a turn, with nothing to break the loop.
                    // decodeKeyframesBySeek already checked unconditionally.
                    if (++spins > MAX_SPINS_BEFORE_EOS && !inputDone) {
                        throw IllegalStateException(
                            "decoder produced no output for $MAX_SPINS_BEFORE_EOS " +
                                "consecutive polls with input still pending ($decoded " +
                                "keyframes so far). Input buffers are all in flight and " +
                                "nothing is coming back — the pipeline is wedged."
                        )
                    }
                    if (inputDone && spins > MAX_SPINS) {
                        throw IllegalStateException(
                            "decoder stalled after end-of-stream with $decoded keyframes " +
                                "decoded and no further output after $MAX_SPINS polls."
                        )
                    }
                }
            }
        }
        // 🔴 decodeNs accumulates the WALL time spent inside this loop up to the
        // last delivered frame. The caller's per-stage GL timings are taken in
        // onFrame(), which runs INSIDE that window, so they are NESTED in
        // decodeNs — it is not a disjoint stage. That is why a naive
        // `decode + upload + resolve + shader + readback` sum EXCEEDS the wall it
        // claims to decompose (measured: stage_total 35.125 vs wall 33.428 on
        // Path Z). WardenEngineBench.timingRun now also emits
        // `decode_excluding_gl` / `gl_total` / `gl_share_of_wall`; quote THOSE.
        // The engine's real share of the wall is ~6% (Path Z) / ~7% (Path P),
        // NOT the ~1% that the nested figures implied.
        return decoded
    }

    private fun profileWidth() = format.getInteger(MediaFormat.KEY_WIDTH)
    private fun profileHeight() = format.getInteger(MediaFormat.KEY_HEIGHT)

    /**
     * Coded frame geometry, for callers that have no buffer to measure.
     *
     * Path Z never sees a plane or a pixel count, so this is the only thing its
     * AC7 geometry assertion can key on — see
     * [WardenDetectionEngine.requireZeroCopyGeometry].
     */
    val frameWidth: Int get() = profileWidth()
    val frameHeight: Int get() = profileHeight()

    /**
     * Path P — copy the three planes out of the codec's Image.
     *
     * The copy is REAL and is exactly what Path P costs relative to Path Z; it is
     * timed inside decodeNs and reported, not hidden.
     */
    private fun imageToKeyframe(c: MediaCodec, outIdx: Int, ptsUs: Long): WardenKeyframe {
        val img = c.getOutputImage(outIdx)
            ?: throw IllegalStateException(
                "getOutputImage returned null — the codec is not in a flexible YUV " +
                    "colour format, so Path P cannot read planes."
            )
        val planes = img.planes
        val w = img.width
        val h = img.height
        val out = Array(3) { i ->
            val src = planes[i].buffer
            val copy = ByteBuffer.allocateDirect(src.remaining())
            copy.put(src); copy.position(0)
            copy
        }
        val rowStrides = IntArray(3) { planes[it].rowStride }
        val pixelStrides = IntArray(3) { planes[it].pixelStride }
        img.close()
        return WardenKeyframe(ptsUs, w, h, out, rowStrides, pixelStrides)
    }

    override fun close() {
        try { codec?.stop() } catch (_: Throwable) {}
        codec?.release(); codec = null
        extractor.release()
    }

    companion object {
        private const val TIMEOUT_US = 10_000L
        private const val MAX_SPINS = 500

        /**
         * Spin budget BEFORE end-of-stream has been queued.
         *
         * Generous relative to [MAX_SPINS] because the single-pass strategy can
         * legitimately go a while without output while the extractor skips
         * hundreds of non-sync samples — but finite, so a codec that is holding
         * every input buffer and returning nothing cannot hang the run forever
         * (at TIMEOUT_US = 10 ms a poll, this caps the wedge at ~20 s).
         */
        private const val MAX_SPINS_BEFORE_EOS = 2000
    }
}

/**
 * Path Z's SurfaceTexture host.
 *
 * AC16 — SurfaceTexture.updateTexImage() has THREAD AFFINITY: it must be called
 * on the thread that owns the EGL context the texture belongs to. That is the
 * concrete constraint amendment 5d needs re-derived, and it is a property of the
 * GL context, not of the JS context.
 */
class WardenSurfaceTextureHost(texId: Int) : AutoCloseable {
    private val lock = Object()
    private var pendingFrames = 0
    val surfaceTexture = SurfaceTexture(texId)
    val surface: Surface
    private val stMatrix = FloatArray(16)

    /**
     * Dedicated Looper thread for the frame-available callback.
     *
     * 🔴 REVIEW 2026-09-15: `setOnFrameAvailableListener(listener)` with no
     * Handler binds to `Looper.myLooper()`, falling back to
     * `Looper.getMainLooper()` when the calling thread has none. The bench runs on
     * a plain `Thread` with no Looper, so EVERY frame notification was
     * round-tripping through the **main** thread — contended when `runBench()` is
     * called from JS with a live RN UI, idle when launched from the bench
     * Activity, so the two entry points were not measuring the same
     * `upload_or_bind`. That figure (0.367 ms) is the base of AC13(a). The old
     * timeout message asserted the opposite ("the listener fires on the thread
     * that created the SurfaceTexture"), which would have sent the next debugger
     * the wrong way.
     */
    private val callbackThread = HandlerThread("warden-st-frame").apply { start() }

    val surfaceTextureTimestampNs: Long get() = surfaceTexture.timestamp

    init {
        surfaceTexture.setOnFrameAvailableListener(
            { synchronized(lock) { pendingFrames++; lock.notifyAll() } },
            Handler(callbackThread.looper)
        )
        surface = Surface(surfaceTexture)
    }

    fun setDefaultBufferSize(w: Int, h: Int) = surfaceTexture.setDefaultBufferSize(w, h)

    /**
     * Blocks until the decoder has posted a frame, then binds it. Returns the ST
     * matrix.
     *
     * @param expectPtsUs the presentation timestamp of the keyframe this bind is
     *   supposed to deliver, or null to skip the check. REVIEW 2026-09-15:
     *   `frameAvailable` used to be a LATCH rather than a counter, and
     *   `getTimestamp()` was never compared against anything — so a coalesced or
     *   dropped frame was undetectable, and on Path Z there was no independent
     *   signal at all that the bound texture was the keyframe being timed.
     */
    fun awaitAndBind(timeoutMs: Long = 2000, expectPtsUs: Long? = null): FloatArray {
        synchronized(lock) {
            val deadline = System.currentTimeMillis() + timeoutMs
            while (pendingFrames == 0) {
                val remaining = deadline - System.currentTimeMillis()
                if (remaining <= 0) {
                    throw IllegalStateException(
                        "SurfaceTexture frame did not arrive within ${timeoutMs}ms. The " +
                            "listener runs on this host's own Looper thread " +
                            "(warden-st-frame), so the producer — MediaCodec — is what " +
                            "did not deliver."
                    )
                }
                lock.wait(remaining)
            }
            if (pendingFrames > 1) {
                // BufferQueue coalescing: updateTexImage() takes the NEWEST buffer,
                // so the frames in between are dropped and the timing attributed to
                // this bind covers more than one decode.
                Log.w(
                    TAG, "SurfaceTexture coalesced $pendingFrames frames before this bind; " +
                        "the bound texture is the newest, not the oldest"
                )
            }
            pendingFrames = 0
        }
        surfaceTexture.updateTexImage()
        if (expectPtsUs != null) {
            // SurfaceTexture timestamps are nanoseconds in the producer's
            // timebase, which for MediaCodec is the sample presentation time.
            val gotUs = surfaceTexture.timestamp / 1000L
            if (gotUs != expectPtsUs) {
                throw IllegalStateException(
                    "Path Z bound the WRONG frame: expected pts ${expectPtsUs}us but " +
                        "SurfaceTexture.getTimestamp() reports ${gotUs}us. Every per-rule " +
                        "decision and every ms/keyframe figure from this run would be " +
                        "attributed to a keyframe that is not the one that was decoded."
                )
            }
        }
        surfaceTexture.getTransformMatrix(stMatrix)
        return stMatrix
    }

    override fun close() {
        surface.release()
        surfaceTexture.release()
        callbackThread.quitSafely()
    }

    private companion object {
        const val TAG = "WardenStHost"
    }
}
