package team.warden.mobile

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.util.concurrent.atomic.AtomicBoolean

// Story 12.2 — the RN bridge. A THIN TRIGGER, nothing else.
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// AC0a's closing clause: "the engine Kotlin MUST be written RN-agnostic (a plain
// class plus a thin trigger), so the measurement code and the future runtime
// module are the same code." Every line of engine logic lives in
// WardenDetectionEngine / WardenRulePacker / WardenKeyframeDecoder /
// WardenCpuBaseline / WardenEngineBench, none of which import React Native. This
// file only marshals arguments and hands back JSON.
//
// Legacy bridge ReactPackage + @ReactMethod + Promise, matching the Story 1.2
// precedent (WardenProcessingModule). NOT a TurboModule: there is no codegen spec
// anywhere in the repo, and amendment 5d's real constraint is THREAD affinity,
// not the module system (AC16). Recorded as an explicit decision per Dev Notes.
//
// AC18b — sole access is via apps/mobile/src/shared/services/detectionEngine.ts.
// No feature module imports NativeModules.WardenDetectionEngine directly.
class WardenDetectionEngineModule(
    private val reactContext: ReactApplicationContext,
) : ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String = "WardenDetectionEngine"

    /**
     * Runs the bench off the JS thread and resolves with the report JSON.
     *
     * Runs on a plain worker thread and never touches the RN thread. Pre-12.4b
     * that was AC16's finding about EGL thread affinity; with the GPU arm gone the
     * reason is simply that a multi-minute decode must not block JS.
     */
    @ReactMethod
    fun runBench(mode: String, video: String?, limit: Int, cpuFrames: Int, promise: Promise) {
        // 🔴 REVIEW 2026-09-15: two overlapping runs both wrote report_<mode>.json,
        // parity_fires.json, rules_lut_device.f32 and timing_fires_*.json into the
        // same directory — interleaved artifacts, and two runs contending for the
        // machine while each claims to measure sustained clocks. A bench is a
        // singleton by nature. (Pre-12.4b each also spawned its own EGL context;
        // the artifact collision and the clock contention outlive the GPU arm.)
        if (!benchInFlight.compareAndSet(false, true)) {
            promise.reject(
                "WARDEN_BENCH_BUSY",
                "a bench run is already in flight; its artifacts and its GPU timings " +
                    "would both be corrupted by a second concurrent run"
            )
            return
        }
        Thread({
            try {
                val report = WardenEngineBench(reactContext.applicationContext)
                    .runAll(mode, video, limit, cpuFrames)
                promise.resolve(report.toString())
            } catch (t: Throwable) {
                promise.reject("WARDEN_BENCH_FAILED", t.message, t)
            } finally {
                benchInFlight.set(false)
            }
        }, "warden-bench-bridge").start()
    }

    /**
     * The device profile — cheap enough to call from JS without a full bench run.
     *
     * 🔴 STORY 12.4b RE-POINTED THIS AT A GL-FREE PROFILE. It used to open an
     * offscreen EGL context purely to read GL_RENDERER / GL_VERSION and compile-probe
     * `GL_OES_EGL_image_external_essl3`, because Path Z's availability turned on
     * them. architecture.md Decision #13 rejected the GPU engine, so there is no
     * context to create and no extension whose absence changes anything.
     *
     * What it reports now is what the BOUND path rests on: SoC, API level, thermal
     * state, and the MediaCodec decoder's identity and colour formats — the last of
     * which decides whether `COLOR_FormatYUV420Flexible`, and therefore
     * WardenColorConvert, works on this device at all.
     *
     * Still off the JS thread, still safe to call repeatedly, and now genuinely
     * cheap: it allocates nothing and touches no GPU. Passing a null video path
     * keeps it off the decoder entirely; Story 12.4c decides whether the production
     * caller wants the `mediacodec` block.
     */
    @ReactMethod
    fun describeDevice(promise: Promise) {
        Thread({
            try {
                val bench = WardenEngineBench(reactContext.applicationContext)
                promise.resolve(bench.deviceProfile(null).toString())
            } catch (t: Throwable) {
                promise.reject("WARDEN_DEVICE_PROBE_FAILED", t.message, t)
            }
        }, "warden-device-probe").start()
    }

    companion object {
        /**
         * Process-wide guard: the bench owns a fixed set of artifact filenames and
         * the machine's sustained clocks, so exactly one run may be in flight.
         * [WardenEngineBenchActivity] takes the same latch.
         */
        @JvmStatic
        val benchInFlight = AtomicBoolean(false)
    }
}
