package team.warden.mobile

import java.nio.ByteBuffer

// Story 12.4b — the CPU YUV->BGR colour conversion.
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// 🔴 THIS FILE IS A SUBSTITUTION, NOT AN ADDITION.
//
// Until this story, the ONLY thing that bridged the decoder's YUV planes to
// WardenCpuBaseline.evaluate()'s B,G,R,A bytes on the video path was
// RESOLVE_YUV_FRAG — a GPU shader, in WardenDetectionEngine.kt, the file
// Story 12.4b deletes. architecture.md Decision #13 binds a CPU engine; a CPU
// engine with no colour conversion has no pixels. Deleting the shader without
// this file first is how you get a detection engine that decodes perfectly and
// evaluates nothing.
//
//   MediaCodec -> YUV420Flexible -> [ THIS FILE ] -> WardenCpuBaseline -> fires
//
// 🔴 THE CONSTANTS ARE LOAD-BEARING AND WERE NEARLY WRONG TWICE.
//
// Story 12.2 found TWO silent colour bugs (bench/12-2/REPORT.md §6) and ended up
// proving the shader's coefficients EXHAUSTIVELY OFFLINE over all 2^24
// (Y, Cb, Cr) triples (`ac3_numpy_reference.py verify-constants`). They are
// transcribed here VERBATIM from RESOLVE_YUV_FRAG. Do NOT re-derive them from a
// formula you remember — that is precisely how both earlier bugs happened. The
// four-decimal chroma coefficients are the ITU-R BT.709 PUBLISHED values, which
// are NOT the exact primaries-derived ones (0.1873 vs 0.18732427,
// 0.4681 vs 0.46812427; red and blue ARE exact at four decimals). That rounding
// is the whole of their error: bounded at ONE unit, on GREEN only, over 0.179%
// of the domain — and FFmpeg ships the same published values, so this is
// agreement WITH FFmpeg rather than deviation from it.
//
// Guarded three ways, because a constant that is only guarded by a comment is
// not guarded:
//   - `colorConvert.test.ts` holds these literals against the numpy reference's
//     transcription of them (cross-language, runs in CI);
//   - `ac3_numpy_reference.py verify-constants` re-proves them over the whole
//     2^24 domain offline;
//   - `WardenEngineBench.colorConstantsCheck()` re-computes all 2^24 triples ON
//     DEVICE with THIS code and compares the digest to the pinned numpy one —
//     which is the only one of the three that can catch a wrong OPERATOR.
//
// 🔴 DOUBLE, NOT FLOAT, AND THAT IS A DECISION.
//
// The shader ran at ESSL `highp float` (fp32). This runs at fp64, which makes it
// BIT-IDENTICAL to `ac3_numpy_reference.shader_model` — the pinned reference —
// instead of merely close to it. MEASURED over the full 2^24 domain on PC:
// fp32 and fp64 disagree on 109 triples of 16,777,216 (0.00065%), max 1 unit —
// i.e. 275x LESS often than the published-rounding error the constants already
// carry, and in the same 1-unit envelope. Choosing fp64 removes the entire
// question rather than answering it, and it is free here because AC0b converts
// ~800 texels per keyframe, not 2,073,600.
object WardenColorConvert {

    // Transcribed VERBATIM from WardenDetectionEngine.RESOLVE_YUV_FRAG (deleted
    // by this story) and held in lockstep with ac3_numpy_reference.py by
    // colorConvert.test.ts.
    //
    //   Y' = (Y - 16) / 219, C = (C - 128) / 224   (limited -> full range)
    //   R = Y' + 1.5748*Cr
    //   G = Y' - 0.1873*Cb - 0.4681*Cr             (bt709)
    //   B = Y' + 1.8556*Cb
    //
    // 🔴 The 68 low-saturation rules (s_center <= 8, h_tol = 180) are immune to a
    // MATRIX error and MAXIMALLY exposed to a RANGE error — the range term is the
    // one that shifts S by ~19.7 units mean. The /219 and /224 matter more here
    // than the matrix does.
    const val Y_OFFSET = 16.0
    const val Y_SCALE = 219.0
    const val C_OFFSET = 128.0
    const val C_SCALE = 224.0

    const val KR_CR = 1.5748
    const val KG_CB = 0.1873
    const val KG_CR = 0.4681
    const val KB_CB = 1.8556

    /**
     * One (Y, Cb, Cr) triple -> B,G,R packed into one Int
     * (`b shl 16 or (g shl 8) or r`).
     *
     * Packed rather than returned as an IntArray for the same reason
     * [WardenCpuBaseline.rgb2hsvPacked] packs: this is called once per rule texel
     * and an allocation per call would dominate the very cost the CPU arm exists
     * to keep small.
     *
     * The operation ORDER mirrors the shader line for line, including its final
     * `floor(clamp(x, 0, 1) * 255 + 0.5)`. That rounding is not cosmetic: the
     * mega-shader recovered integers with `floor(texel * 255 + 0.5)`, so a value
     * left off the 8-bit lattice would have been rounded a SECOND time and could
     * land one unit off. WardenCpuBaseline reads 8-bit integers directly, so the
     * second rounding is gone — but the first one is what the pinned reference
     * does, and parity is measured against the reference.
     */
    fun yuvToBgrPacked(y: Int, cb: Int, cr: Int): Int {
        val yn = (y.toDouble() - Y_OFFSET) / Y_SCALE
        val cbn = (cb.toDouble() - C_OFFSET) / C_SCALE
        val crn = (cr.toDouble() - C_OFFSET) / C_SCALE

        // Left-to-right, matching both the shader and numpy's evaluation of
        // `yn - KG_CB*cbn - KG_CR*crn` as `(yn - KG_CB*cbn) - KG_CR*crn`.
        val r = yn + KR_CR * crn
        val g = yn - KG_CB * cbn - KG_CR * crn
        val b = yn + KB_CB * cbn

        return (quantize(b) shl 16) or (quantize(g) shl 8) or quantize(r)
    }

    /** GLSL's `floor(clamp(v, 0.0, 1.0) * 255.0 + 0.5)`, exactly. */
    private fun quantize(v: Double): Int {
        val c = if (v < 0.0) 0.0 else if (v > 1.0) 1.0 else v
        return Math.floor(c * 255.0 + 0.5).toInt()
    }
}

/**
 * One decoded keyframe's YUV 4:2:0 planes, addressable per pixel.
 *
 * 🔴 EVERY LAYOUT IS READ THROUGH ITS OWN STRIDES. THERE IS NO FAST PATH.
 *
 * `COLOR_FormatYUV420Flexible` is a FAMILY, not a layout, and Story 12.2's GPU
 * upload learned that the expensive way. Its semi-planar branch keyed only on
 * `uPixelStride == 2 && vPixelStride == 2` and then uploaded `planes[1]` as the
 * interleaved base, IGNORING `planes[2]`:
 *
 *   NV12 (`U V U V …`)  planes[1] starts at Cb  -> pairs are (U0,V0)   correct
 *   NV21 (`V U V U …`)  planes[1] starts at Cb, which is offset 1, and the byte
 *                       after it is the NEXT COLUMN's Cr -> frame-wide chroma
 *                       shift, silent, on the path the report recommends
 *                       shipping *because* it is exact.
 *
 * That bug was patched during 12.2's review (by proving `u.get(1) == v.get(0)`
 * before taking the branch) but it stayed LATENT on the reference device, which
 * hands back NV12. The CPU port cannot inherit it, because the CPU port has
 * nothing to inherit it FROM: `android.media.Image` guarantees `planes[1]` is U
 * (Cb) and `planes[2]` is V (Cr) whatever the interleaving, and reading each
 * through its OWN `rowStride`/`pixelStride` is correct for NV12, NV21 and fully
 * planar I420 alike. The layout is CLASSIFIED and REPORTED ([layoutName]) rather
 * than inferred and acted on — the AC1 requirement is that no untested layout is
 * silently taken, and the way to guarantee that is to have no layout-specific
 * branch at all.
 *
 * Costs nothing here: a stride multiply-add per texel, over ~800 texels.
 */
class WardenYuvFrame(
    private val yPlane: ByteBuffer,
    private val yRowStride: Int,
    private val yPixelStride: Int,
    private val uPlane: ByteBuffer,
    private val uRowStride: Int,
    private val uPixelStride: Int,
    private val vPlane: ByteBuffer,
    private val vRowStride: Int,
    private val vPixelStride: Int,
    val width: Int,
    val height: Int,
) {

    /** Chroma plane dimensions for 4:2:0. */
    val chromaWidth: Int = (width + 1) / 2
    val chromaHeight: Int = (height + 1) / 2

    init {
        require(width > 0 && height > 0) { "degenerate frame geometry ${width}x$height" }
        requireSpans("Y", yPlane, yRowStride, yPixelStride, width, height)
        requireSpans("U", uPlane, uRowStride, uPixelStride, chromaWidth, chromaHeight)
        requireSpans("V", vPlane, vRowStride, vPixelStride, chromaWidth, chromaHeight)
    }

    private fun requireSpans(
        what: String,
        buf: ByteBuffer,
        rowStride: Int,
        pixelStride: Int,
        w: Int,
        h: Int,
    ) {
        require(rowStride > 0 && pixelStride > 0) {
            "$what plane has rowStride=$rowStride pixelStride=$pixelStride; both must be positive"
        }
        // The LAST addressable byte, not a row-count product: a semi-planar plane
        // legitimately ends at its own last sample, one byte short of `h*rowStride`.
        // Requiring the product here is the off-by-one that rejected every real
        // NV12 frame in 12.2 and fell to a 25x-slower path.
        val need = (h - 1).toLong() * rowStride + (w - 1).toLong() * pixelStride + 1L
        // LIMIT, not capacity: absolute `get(i)` throws at `limit()`, so a buffer
        // with limit < capacity would pass a capacity check here and then throw
        // part-way through an evaluation. And [bgrAt] indexes from 0, so a
        // non-zero position would silently shift every sample.
        require(buf.position() == 0) {
            "$what plane has position ${buf.position()}; offsets are computed from 0"
        }
        require(buf.limit() >= need) {
            "$what plane holds ${buf.limit()} bytes but ${w}x$h at rowStride=$rowStride " +
                "pixelStride=$pixelStride addresses up to $need. A short plane reads " +
                "whatever is next in the decoder's allocation and calls it chroma."
        }
    }

    /**
     * 🔴 AC1/trap 4 — ASSERT the geometry, never rescale it.
     *
     * Zone coordinates are calibrated at `reference_resolution` 1920x1080 and
     * `clampRect` is applied CPU-side at pack time, so a frame of another size is
     * not a frame that needs resampling — it is a frame whose rects mean nothing.
     * Path Z had no such assertion and silently nearest-neighbour rescaled, which
     * is how AC13's comparison became "a rescaled frame against a crash".
     */
    fun requireGeometry(expectedWidth: Int, expectedHeight: Int) {
        if (width != expectedWidth || height != expectedHeight) {
            throw IllegalArgumentException(
                "keyframe geometry is ${width}x$height but the rules were packed for " +
                    "${expectedWidth}x$expectedHeight. Rule rects are calibrated at the " +
                    "reference resolution; rescaling would evaluate every rect against " +
                    "resampled pixels and produce plausible-looking wrong detections."
            )
        }
    }

    /**
     * The B,G,R at (x, y), packed as [WardenColorConvert.yuvToBgrPacked] packs it.
     *
     * 🔴 NEAREST-NEIGHBOUR CHROMA, DELIBERATELY. `x / 2, y / 2` is exactly
     * RESOLVE_YUV_FRAG's `ivec2 pc = ivec2(p.x / 2, p.y / 2)`. The residual
     * dS ~ 2.46 against FFmpeg's `rgb24` is a chroma-upsampling POLICY difference
     * (nearest vs swscale's interpolation), <= 3 units of 255 — NOT a matrix
     * error. Do NOT "improve" this to bilinear: it changes the fire bits, breaks
     * AC3's parity, and diverges from lut.py / Tool 12, which Story 9.16
     * re-points at this engine.
     */
    fun bgrAt(x: Int, y: Int): Int {
        val luma = yPlane.get(y * yRowStride + x * yPixelStride).toInt() and 0xFF
        val cx = x / 2
        val cy = y / 2
        val cb = uPlane.get(cy * uRowStride + cx * uPixelStride).toInt() and 0xFF
        val cr = vPlane.get(cy * vRowStride + cx * vPixelStride).toInt() and 0xFF
        return WardenColorConvert.yuvToBgrPacked(luma, cb, cr)
    }

    /**
     * DIAGNOSTIC ONLY — the whole frame as B,G,R,A bytes, row-major.
     *
     * This is the `framediff` instrument: a full converted frame, dumped so it
     * can be diffed per pixel against FFmpeg's `rgb24` off-device. It is NOT on
     * any measured path and NOT what the engine uses — AC0b converts rule regions
     * only, ~800 texels instead of 2,073,600 (~2,600x less work), which is
     * available precisely because there is no longer a shader that needs a whole
     * texture. Calling this per keyframe would hand back the cost the GPU arm was
     * rejected for.
     */
    fun convertFrameToBgra(): ByteArray {
        val out = ByteArray(width * height * 4)
        var off = 0
        for (y in 0 until height) {
            for (x in 0 until width) {
                val bgr = bgrAt(x, y)
                out[off] = ((bgr ushr 16) and 0xFF).toByte()
                out[off + 1] = ((bgr ushr 8) and 0xFF).toByte()
                out[off + 2] = (bgr and 0xFF).toByte()
                out[off + 3] = 0xFF.toByte()
                off += 4
            }
        }
        return out
    }

    /**
     * Which 4:2:0 layout the decoder actually handed back.
     *
     * REPORTED, never branched on. AC1 asks for NV12, NV21 and I420 to be handled
     * "explicitly"; [bgrAt] handles all three by construction, and this exists so
     * a report says WHICH one was measured instead of leaving the reader to
     * assume the reference device's.
     *
     * 🔴 A VALUE TEST, OVER THE WHOLE PLANE, AND IT CAN SAY "DON'T KNOW".
     * `imageToKeyframe` copies each plane into its own buffer, so shared memory
     * cannot be observed here (and `android.media.Image` exposes no public way to
     * observe it either). What survives the copy is the interleaving: in NV12
     * every `u[2k+1]` IS `v[2k]`; in NV21 every `v[2k+1]` IS `u[2k]`. 12.2's review
     * tested ONE byte of that, which is true for any layout on a flat-chroma
     * frame (black intro frames: every byte 128) — and the 12.4b report's "NV12"
     * came from exactly such a frame. When both hypotheses hold over the whole
     * plane the frame cannot discriminate, and this returns
     * [LAYOUT_INDETERMINATE] so the caller tries a later frame.
     */
    fun layoutName(): String {
        if (uPixelStride == 1 && vPixelStride == 1) return "I420 (fully planar)"
        if (uPixelStride == 2 && vPixelStride == 2) {
            val nv12 = interleaves(uPlane, vPlane)
            val nv21 = interleaves(vPlane, uPlane)
            return when {
                nv12 && nv21 -> LAYOUT_INDETERMINATE
                nv12 -> "NV12 (semi-planar, U V U V)"
                nv21 -> "NV21 (semi-planar, V U V U)"
                else -> "semi-planar, U and V in separate allocations"
            }
        }
        return "pixelStride u=$uPixelStride v=$vPixelStride (read through strides regardless)"
    }

    /** True when every `first[2k+1] == second[2k]` over the addressable chroma span. */
    private fun interleaves(first: ByteBuffer, second: ByteBuffer): Boolean {
        val n = minOf(first.limit() - 1, second.limit())
        if (n <= 0) return false
        var k = 0
        while (k < n) {
            if (first.get(k + 1) != second.get(k)) return false
            k += 2
        }
        return true
    }

    companion object {
        const val LAYOUT_INDETERMINATE =
            "semi-planar, order indeterminate on this frame (uniform chroma)"

        /** Build from a [WardenKeyframe] the decoder just produced. */
        fun of(kf: WardenKeyframe): WardenYuvFrame {
            val planes = kf.planes
            val rows = kf.rowStrides
            val pix = kf.pixelStrides
            return WardenYuvFrame(
                planes[0], rows[0], pix[0],
                planes[1], rows[1], pix[1],
                planes[2], rows[2], pix[2],
                kf.width, kf.height,
            )
        }
    }
}
