package team.warden.mobile

import org.json.JSONObject
import java.nio.ByteBuffer
import java.nio.ByteOrder

// Story 12.2 AC5 — the Kotlin port of apps/tooling/tools/keyframe_engine_bench/lut.py.
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// This file is the parity contract. The CPU pre-resolves each rule's OpenCV
// INTEGER band bounds exactly as tools/common/zones.py does, and the shader
// compares against those bounds inclusively. **Parity comes from NOT re-deriving
// the band on the GPU.**
//
// Task 4 cross-checks the texture this produces BYTE-FOR-BYTE against lut.py's
// output for the shipped config (reference: 7200 bytes, sha256
// b8287e084937dff08ee9a36bdb144e7d09b4bb414bab88d5fee6ee1b2b7f62c5). That check
// is cheap and removes an entire class of divergence before any GPU work.

/** Must match MAX_RULES in lut.py and the 150-wide rules texture in the .frag. */
const val MAX_RULES = 150

/**
 * Must stay in LOCKSTEP with MAX_RECT_TEXELS in keyframe_engine_bench.frag.
 * Above the cap the shader's loop truncates while `ratio` still divides by the
 * full area, so a rule SILENTLY UNDER-FIRES instead of failing — a parity break
 * that presents as a wrong number, not an error. [packRules] rejects any rect
 * above it, which is what makes the truncation unreachable rather than unlikely.
 */
const val MAX_RECT_TEXELS = 4096

/**
 * Padding texels (rules n..149) get this min_ratio. A ratio is definitionally in
 * [0, 1], so `step(2.0, ratio)` can never fire. Zero would be a landmine: a
 * zeroed rule has area 0 -> ratio 0.0 and min_ratio 0.0, and `step(0,0) == 1`,
 * so every padding texel would read back as FIRED.
 */
private const val PAD_MIN_RATIO = 2.0f

/**
 * The default a zone with no `min_ratio` gets.
 *
 * Pinned to `HsvBand.min_ratio: float = 0.3` in
 * `apps/tooling/tools/keyframe_engine_bench/lut.py:207`. If that dataclass
 * default ever changes, this must change with it — a divergence here reappears
 * as an AC5 LUT hash mismatch, which is the whole point of that check.
 */
private const val PY_DEFAULT_MIN_RATIO = 0.3

const val MODE_NORMAL = 0
const val MODE_WRAP = 1
const val MODE_FULL_CIRCLE = 2

private const val N_ROWS = 3

// zones.py:32-33 — one OpenCV H unit = 2 user degrees; S/V are 0-100 user.
private const val H_CV_TO_USER = 360.0 / 180.0
private const val SV_CV_TO_USER = 100.0 / 255.0

/** Texel index -> the zone it came from. CPU-side aggregation depends on this order. */
data class WardenRuleRef(
    val texel: Int,
    val owningClass: String,
    val zoneId: String,
    /** `hud_version` | `in_match` | `map` — selects which of the THREE classifier formulas the fire feeds. */
    val kind: String,
    val effectiveWeight: Double,
)

data class WardenPackedRules(
    /** (MAX_RULES * 3 * 4) float32, row-major [rule][row][channel] — GL-upload-ready. */
    val texture: FloatArray,
    val refs: List<WardenRuleRef>,
    val nRules: Int,
) {
    /** Little-endian float32 bytes — the exact form lut.py's ndarray.tobytes() produces. */
    fun toByteArray(): ByteArray {
        val bb = ByteBuffer.allocate(texture.size * 4).order(ByteOrder.LITTLE_ENDIAN)
        for (f in texture) bb.putFloat(f)
        return bb.array()
    }
}

/** Resolved integer band bounds for one zone. */
data class WardenBandBounds(
    val hLo: Int, val hHi: Int,
    val sLo: Int, val sHi: Int,
    val vLo: Int, val vHi: Int,
    val mode: Int,
)

object WardenRulePacker {

    /**
     * Python's `round()` — round-half-to-EVEN (banker's rounding).
     *
     * This is load-bearing, not pedantry. `resolve_band_bounds` does
     * `int(round(h_c ± h_t))`, hue centers routinely land on `.0`/`.5`, and
     * 31 of the 134 shipped rules end up with bands ASYMMETRIC about their
     * center precisely because of this rounding. `Math.round` (half-UP) would
     * shift those bounds by one and break parity on exactly the rules that are
     * hardest to notice.
     *
     * `Math.rint` is round-half-to-even and matches Python 3's `round()` bit for
     * bit. Kotlin's `kotlin.math.round` delegates here on the JVM, but this is
     * spelled out explicitly so nobody "simplifies" it to `Math.round`.
     */
    private fun pyRound(x: Double): Int = Math.rint(x).toInt()

    /** Python's `%` on floats — FLOORED (result takes the divisor's sign). */
    private fun flooredMod(a: Double, b: Double): Double {
        val r = a % b
        return if (r != 0.0 && (r < 0.0) != (b < 0.0)) r + b else r
    }

    /**
     * User-space hue CENTER -> OpenCV space, wrapped into [0, 180).
     * The `% 180` is correct for a POSITION on the circle.
     */
    fun hueCenterUserToCv(hUser: Double): Double = flooredMod(hUser / H_CV_TO_USER, 180.0)

    fun svUserToCv(vUser: Double): Double = vUser / SV_CV_TO_USER

    /**
     * User-space hue TOLERANCE -> OpenCV space, clamped to [0, 90].
     *
     * **THE #1 SHADER-PORT TRAP.** Unlike the center, this does NOT mod by 180:
     * a tolerance is a MAGNITUDE, not a position, and modding it silently
     * collapses wide bands (h_tol=380 -> 10). Values >= 90 CV units saturate the
     * full circle and are CLAMPED, not wrapped — which is what puts the 68
     * `h_tol=180` low-saturation rules on the full-circle branch.
     */
    fun hueTolUserToCv(tolUser: Double): Double =
        (tolUser / H_CV_TO_USER).coerceIn(0.0, 90.0)

    fun svTolUserToCv(tolUser: Double): Double =
        (tolUser / SV_CV_TO_USER).coerceIn(0.0, 255.0)

    /** One zone's HSV band -> integer bounds + branch mode. Mirrors resolve_band_bounds. */
    fun resolveBandBounds(hsv: JSONObject): WardenBandBounds {
        val hC = hueCenterUserToCv(hsv.getDouble("h_center"))
        val sC = svUserToCv(hsv.getDouble("s_center"))
        val vC = svUserToCv(hsv.getDouble("v_center"))
        val hT = hueTolUserToCv(hsv.getDouble("h_tol"))
        val sT = svTolUserToCv(hsv.getDouble("s_tol"))
        val vT = svTolUserToCv(hsv.getDouble("v_tol"))

        // h_lo/h_hi are RAW — possibly negative or > 179. The shader derives
        // mod(h, 180) itself for the wrap branch, and GLSL's mod() is floored
        // like Python's %, so the two sub-intervals reconstruct exactly.
        val hLo = pyRound(hC - hT)
        val hHi = pyRound(hC + hT)
        val sLo = maxOf(0, pyRound(sC - sT))
        val sHi = minOf(255, pyRound(sC + sT))
        val vLo = maxOf(0, pyRound(vC - vT))
        val vHi = minOf(255, pyRound(vC + vT))

        // Branch order mirrors band_inrange_ratio EXACTLY: full-circle is tested
        // FIRST, so a band that is both >= 180 wide AND out of [0,179] is
        // full-circle, not wrap. Reversing these two tests changes the answer.
        val mode = when {
            (hHi - hLo) >= 180 -> MODE_FULL_CIRCLE
            hLo < 0 || hHi > 179 -> MODE_WRAP
            else -> MODE_NORMAL
        }
        return WardenBandBounds(hLo, hHi, sLo, sHi, vLo, vHi, mode)
    }

    /**
     * Bridge the labeled-dir naming (`v2.0`) and the schema/config enum (`v2`):
     * lowercase + strip a single trailing `.0`. Idempotent. Mirrors
     * roi_detection_tester.py:108 `_normalize_hud`.
     */
    fun normalizeHud(s: String): String {
        val out = s.trim().lowercase()
        return if (out.endsWith(".0")) out.dropLast(2) else out
    }

    /** Rect clipped fully inside (h, w). A fully off-frame rect returns 0 area. */
    fun clampRect(x: Int, y: Int, w: Int, h: Int, frameW: Int, frameH: Int): IntArray {
        val xStart = maxOf(0, minOf(x, frameW))
        val yStart = maxOf(0, minOf(y, frameH))
        val xEnd = maxOf(xStart, minOf(x + w, frameW))
        val yEnd = maxOf(yStart, minOf(y + h, frameH))
        return intArrayOf(xStart, yStart, xEnd - xStart, yEnd - yStart)
    }

    /**
     * Canonical texel order: HUD-version zones, then in_match zones, then map
     * zones in config insertion order. Mirrors Tool 9's `evaluate_frame` order so
     * the two are trivially comparable.
     *
     * `JSONObject` does not preserve insertion order, so map names are taken from
     * the RAW JSON text via [orderedMapNames] rather than from `keys()` — an
     * ordering difference here would silently permute every map rule's texel
     * index and destroy parity while every individual rule stayed correct.
     */
    private fun iterZones(config: JSONObject, rawJson: String): List<Triple<JSONObject, String, String>> {
        val out = ArrayList<Triple<JSONObject, String, String>>()
        // HUD zones' owning_class is the NORMALIZED hud_version ("v2"), NOT the
        // literal "hud_version" — roi_detection_tester.py:449 passes
        // `_normalize_hud(hud_version)`. The pair (owning_class, zone_id) is the
        // `zone_fires` key the parity comparison joins on, so getting this wrong
        // would make every HUD rule fail to match a PC row while the rule itself
        // evaluated perfectly.
        val hudClass = normalizeHud(config.getString("hud_version"))
        val hud = config.getJSONArray("hud_version_detection")
        for (i in 0 until hud.length()) {
            out.add(Triple(hud.getJSONObject(i), hudClass, "hud_version"))
        }
        val im = config.getJSONArray("in_match_detection")
        for (i in 0 until im.length()) {
            out.add(Triple(im.getJSONObject(i), "in_match", "in_match"))
        }
        val maps = config.getJSONObject("minimap_identification").getJSONObject("maps")
        for (name in orderedMapNames(rawJson)) {
            val zones = maps.getJSONObject(name).getJSONArray("zones")
            for (i in 0 until zones.length()) {
                out.add(Triple(zones.getJSONObject(i), name, "map"))
            }
        }
        return out
    }

    /**
     * Map names in the order they appear in the config TEXT.
     *
     * REL-005 preserves config insertion order on the Python side (dicts are
     * ordered); org.json's JSONObject is a HashMap and is not. Scanning the raw
     * text for the `"maps"` object's direct children is the only way to recover
     * the same order without a second JSON library.
     *
     * 🔴 REVIEW 2026-09-15: the anchor used to be a bare
     * `rawJson.indexOf("\"maps\"")`, i.e. the FIRST occurrence of that literal
     * anywhere in the file — a string value, a key in an unrelated object, a
     * `$comment`. Walking the wrong object silently permutes every map rule's
     * texel index (each rule individually correct, the ORDER wrong), which is
     * precisely the failure this function exists to prevent, relocated to the
     * anchor. It now anchors on `"minimap_identification"` first and takes the
     * `"maps"` key inside it, and refuses to guess when that key appears twice.
     */
    fun orderedMapNames(rawJson: String): List<String> {
        val section = rawJson.indexOf("\"minimap_identification\"")
        require(section >= 0) { "config has no minimap_identification" }
        val anchor = rawJson.indexOf("\"maps\"", section)
        require(anchor >= 0) { "config has no minimap_identification.maps" }
        require(rawJson.indexOf("\"maps\"", anchor + 1) < 0) {
            "the literal \"maps\" appears more than once after " +
                "\"minimap_identification\"; the text scan cannot tell which object " +
                "carries the map order, and guessing permutes every map rule's texel " +
                "index. Disambiguate the config."
        }
        val open = rawJson.indexOf('{', anchor)
        require(open >= 0) { "malformed maps object" }
        val names = ArrayList<String>()
        var depth = 0
        var i = open
        var inString = false
        var escaped = false
        var pendingKeyStart = -1
        while (i < rawJson.length) {
            val c = rawJson[i]
            if (inString) {
                when {
                    escaped -> escaped = false
                    c == '\\' -> escaped = true
                    c == '"' -> {
                        inString = false
                        // A string that closes at depth 1 and is followed by ':'
                        // is a direct child key of `maps`.
                        if (depth == 1 && pendingKeyStart >= 0) {
                            var j = i + 1
                            while (j < rawJson.length && rawJson[j].isWhitespace()) j++
                            if (j < rawJson.length && rawJson[j] == ':') {
                                names.add(rawJson.substring(pendingKeyStart, i))
                            }
                        }
                        pendingKeyStart = -1
                    }
                }
            } else {
                when (c) {
                    '"' -> { inString = true; escaped = false; pendingKeyStart = i + 1 }
                    '{' -> depth++
                    '}' -> { depth--; if (depth == 0) return names }
                }
            }
            i++
        }
        throw IllegalArgumentException("unterminated maps object in config")
    }

    /**
     * MapConfig JSON -> a GL-upload-ready (150, 3, 4) float32 rules texture.
     *
     * Every rect is clamped HERE, CPU-side. Clamping in the packer is part of the
     * parity contract, not a nicety: Tool 9 clamps before evaluating and
     * `band_inrange_ratio` divides by the CLAMPED mask.size, not the declared
     * width x height. A naive `count / (w*h)` in the shader would diverge the
     * moment a zone is drawn off-edge. (Latent today: 0 of the 134 shipped rects
     * exceed 1920x1080.)
     *
     * `weight` / `weight_override` deliberately NEVER enter the texture — all
     * scoring and phase resolution stay CPU-side. They travel on [WardenRuleRef].
     */
    fun packRules(rawJson: String, frameW: Int, frameH: Int): WardenPackedRules {
        val config = JSONObject(rawJson)
        val zones = iterZones(config, rawJson)
        val nRules = zones.size
        require(nRules <= MAX_RULES) {
            "config carries $nRules rules but the rules texture is $MAX_RULES wide " +
                "(AC5). Widen MAX_RULES here, in lut.py and in the .frag together."
        }

        val texture = FloatArray(MAX_RULES * N_ROWS * 4)
        // Pre-fill every padding texel's min_ratio with the unreachable value.
        for (i in 0 until MAX_RULES) {
            texture[(i * N_ROWS + 2) * 4 + 2] = PAD_MIN_RATIO
        }

        val refs = ArrayList<WardenRuleRef>(nRules)
        for ((i, entry) in zones.withIndex()) {
            val (z, owningClass, kind) = entry
            val r = clampRect(
                z.getInt("x"), z.getInt("y"), z.getInt("width"), z.getInt("height"),
                frameW, frameH
            )
            val area = r[2] * r[3]
            require(area <= MAX_RECT_TEXELS) {
                "zone ${z.getString("id")} ($owningClass) clamps to ${r[2]}x${r[3]} = " +
                    "$area px, but the shader's per-rect loop is capped at " +
                    "MAX_RECT_TEXELS=$MAX_RECT_TEXELS. Above the cap the loop truncates " +
                    "while `ratio` still divides by the full area, so the rule SILENTLY " +
                    "UNDER-FIRES instead of failing — a parity break, not an error."
            }
            val b = resolveBandBounds(z.getJSONObject("hsv"))

            val base = i * N_ROWS * 4
            texture[base + 0] = r[0].toFloat()
            texture[base + 1] = r[1].toFloat()
            texture[base + 2] = r[2].toFloat()
            texture[base + 3] = r[3].toFloat()

            texture[base + 4] = b.hLo.toFloat()
            texture[base + 5] = b.hHi.toFloat()
            texture[base + 6] = b.sLo.toFloat()
            texture[base + 7] = b.sHi.toFloat()

            texture[base + 8] = b.vLo.toFloat()
            texture[base + 9] = b.vHi.toFloat()
            // min_ratio from the zone, falling back to the SAME default the Python
            // reference uses — never a class default of our own invention.
            //
            // 🔴 REVIEW 2026-09-15: this was `z.getDouble("min_ratio")`, which
            // THROWS JSONException on a zone that omits the key, while
            // `lut.py:207` reads `z.band.min_ratio` whose dataclass default is
            // 0.3. A config exercising that default would have killed the whole
            // bench — including AC5's byte-for-byte LUT cross-check, the very
            // check designed to catch a Kotlin/Python packing divergence, because
            // the Kotlin side died before producing any bytes to compare.
            texture[base + 10] = z.optDouble("min_ratio", PY_DEFAULT_MIN_RATIO).toFloat()
            texture[base + 11] = b.mode.toFloat()

            val weightOverride =
                if (z.isNull("weight_override")) null else z.getDouble("weight_override")
            val effectiveWeight = weightOverride ?: z.optDouble("weight", 1.0)

            refs.add(WardenRuleRef(i, owningClass, z.getString("id"), kind, effectiveWeight))
        }
        return WardenPackedRules(texture, refs, nRules)
    }

    /**
     * (1, 150, 4) RGBA8 readback -> one bool per rule.
     *
     * Threshold is `> 127`, NEVER `== 255`: the shader writes 1.0/0.0 and an
     * exact-equality test would be hostage to any driver's rounding of 1.0 to
     * 254. (AC6.)
     */
    fun decodeResults(rgba8: ByteArray, nRules: Int): BooleanArray {
        require(rgba8.size >= nRules * 4) {
            "readback holds ${rgba8.size / 4} texels, need at least $nRules"
        }
        return BooleanArray(nRules) { (rgba8[it * 4].toInt() and 0xFF) > 127 }
    }
}
