package team.warden.mobile

import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

// Story 12.4c — THE PRODUCTION DETECTION ENTRY POINT (AC0a / AC1).
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// 🔴 THIS IS NOT THE BENCH. WardenEngineBench measures; this one answers.
//
// AC0a verdict: **Option A with events** — ONE per-session native call that
// decodes every keyframe, evaluates the rules and hands back the whole fire-bit
// timeline, with progress pushed as RN device events and cooperative
// cancellation. Option B (a per-keyframe `nextKeyframe()` bridge) was rejected
// without measuring it, on the arithmetic: the whole engine costs 0.651 ms/kf
// (12.4b) and the rule evaluation it exists to serve is ~1% of the wall
// (12.3 Decision #13), so paying 1061 legacy-bridge crossings — each marshalling
// a JSON string, on a non-Turbo, non-JSI bridge — to save part of 1% cannot pay
// for itself. It would also break the decode PIPELINE 12.4a built: k = 8
// keyframes are in flight inside one decode loop, and a JS round trip per
// keyframe would serialise exactly what 12.4a un-serialised (4.27x).
//
// 🔴 WHAT THIS DELIBERATELY DOES *NOT* DO: scoring and phase resolution.
// AC0b puts those in TypeScript (`engineScoring.ts` / `gameDetector.ts`), so
// this returns FIRE BITS plus the rule index (`refs`) they are indexed by, and
// nothing that interprets them. Reasons, recorded:
//   * jest is the project's only test surface — there are NO Kotlin tests in
//     this repo at all (Decision #ES-6) — and the ported logic is ~390 lines of
//     branchy policy with a fixture-driven parity obligation against Tool 12.
//   * detection POLICY (what counts as a match, what "doubt" means) is product
//     semantics; the layer that owns the product owns it.
//   * the cost is one array of 134 bits per keyframe — 34 hex chars, ~36 kB for
//     a 73-minute capture, crossing the bridge ONCE. The hot loop stays native.
//
// Fire bits are hex, 4 per char, LSB first — [WardenEngineBench.bitsToHex]'s
// packing, which `pc_reference.py` and `video_oracle.py` already speak, so a
// device dump drops straight into the PC parity comparison.

private const val TAG = "WardenAnalyzer"

/** Thrown when the caller cancelled the run. Distinct so the bridge can map it. */
class WardenAnalysisCancelledException(message: String) : RuntimeException(message)

/**
 * Per-session keyframe analysis: video + config -> per-keyframe fire bits.
 *
 * One instance per run. Not reusable and not thread-safe: it owns a decoder and
 * a codec for the duration of [analyze].
 */
class WardenSessionAnalyzer(
    private val videoPath: String,
    private val configJson: String,
) {

    /**
     * Decode every keyframe and evaluate the packed rules over it.
     *
     * @param limit 0 = the whole capture; > 0 caps the keyframe count (dev/debug).
     * @param onProgress called with (decoded, total) at most [PROGRESS_STEPS]
     *   times plus once at the end. Never called from the JS thread.
     * @param isCancelled polled once per keyframe; true aborts with
     *   [WardenAnalysisCancelledException] after releasing the codec.
     */
    fun analyze(
        limit: Int,
        onProgress: (Int, Int) -> Unit,
        isCancelled: () -> Boolean,
    ): JSONObject {
        require(File(videoPath).exists()) { "video not found: $videoPath" }

        val config = JSONObject(configJson)
        val refRes = config.getJSONObject("reference_resolution")
        val refW = refRes.getInt("width")
        val refH = refRes.getInt("height")

        // Packing is cheap (no allocation per frame) and it is the first thing
        // that can reject a config, so it happens before the decoder is opened:
        // a malformed config should not cost a MediaCodec instance.
        val packed = WardenRulePacker.packRules(configJson, refW, refH)
        val hudVersion = WardenRulePacker.normalizeHud(config.getString("hud_version"))

        val out = JSONObject()
        out.put("story", "12.4c")
        out.put("kind", "session-analysis")
        out.put("generated_at", System.currentTimeMillis())
        out.put("video", File(videoPath).name)
        out.put("hud_version", hudVersion)
        out.put("n_rules", packed.nRules)
        out.put("reference_resolution", JSONObject().put("width", refW).put("height", refH))
        out.put("refs", refsJson(packed))

        val frames = JSONArray()
        var decoded = 0
        var layout = WardenYuvFrame.LAYOUT_INDETERMINATE
        var layoutAttempts = 0
        val wall0 = System.nanoTime()
        var engineNs = 0L
        var lastEngineNs = 0L
        var decodeNs = 0L
        var indexMs = 0.0

        WardenKeyframeDecoder(videoPath).use { dec ->
            // 🔴 NEVER the 62 s ground-truth walk. `probe(scanSyncSamples = false)`
            // is the production shape (Story 12.4a AC3); the sample-table scan is a
            // BENCH-ONLY correctness assertion and it is a FULL-FILE READ.
            val profile = dec.probe(scanSyncSamples = false, knownSyncCount = -1)
            out.put(
                "decoder",
                JSONObject()
                    .put("codec_name", profile.codecName)
                    .put("is_hardware_accelerated", profile.isHardwareAccelerated)
                    .put("mime", profile.mime)
                    .put("width", profile.width)
                    .put("height", profile.height)
                    .put("duration_us", profile.durationUs)
            )

            // Geometry is asserted HERE, once, against the format — before any
            // decode — so an unsupported capture fails with a sentence about the
            // capture rather than 1061 identical per-frame assertion failures out
            // of `evaluateYuv`. Rule rects are calibrated at reference_resolution
            // and are NEVER rescaled (12.4b trap 4).
            if (profile.width != refW || profile.height != refH) {
                throw IllegalStateException(
                    "$UNSUPPORTED_GEOMETRY: the capture is ${profile.width}x${profile.height} " +
                        "but the detection config is calibrated for ${refW}x$refH. Zone " +
                        "coordinates are absolute at the reference resolution, so rescaling " +
                        "would evaluate every rule against resampled pixels and produce " +
                        "plausible-looking wrong detections. Re-record at ${refW}x$refH or " +
                        "ship a config calibrated for this resolution."
                )
            }

            val tIndex = System.nanoTime()
            val ptsList = dec.syncSamplePtsListBySeek()
            indexMs = (System.nanoTime() - tIndex) / 1e6
            check(ptsList.isNotEmpty()) {
                "no sync samples found in ${File(videoPath).name} — nothing to analyse"
            }

            // 🔴 THE INDEX IS SEEK-DERIVED AND THEREFORE A HYPOTHESIS, NOT A COUNT.
            // `syncSamplePtsListBySeek` estimates the GOP from the first two
            // keyframes and steps it, stopping the moment a step fails to advance.
            // On an irregular-GOP capture that stops EARLY, and the honest
            // ground truth (`countSyncSamplesByScan`) is a 62 s full-file read that
            // MUST NEVER SHIP. So the coverage is reported instead of asserted: the
            // TS caller warns when the index stops well short of the duration, and
            // a truncated analysis is visible in the artifact rather than silent.
            val lastPts = ptsList.last()
            val gopUs = if (ptsList.size > 1) ptsList[1] - ptsList[0] else 0L
            val uncoveredUs = profile.durationUs - lastPts
            out.put(
                "keyframe_index",
                JSONObject()
                    .put("source", "syncSamplePtsListBySeek (seek-derived; the 62 s sample-table walk never ships)")
                    .put("n_pts", ptsList.size)
                    .put("index_ms", indexMs)
                    .put("first_pts_us", ptsList.first())
                    .put("last_pts_us", lastPts)
                    .put("estimated_gop_us", gopUs)
                    .put("duration_us", profile.durationUs)
                    .put("uncovered_tail_us", uncoveredUs)
                    .put(
                        "covers_duration",
                        gopUs <= 0L || uncoveredUs <= 2L * gopUs
                    )
            )

            val total = if (limit > 0) minOf(limit, ptsList.size) else ptsList.size
            var nextProgressAt = 0
            onProgress(0, total)

            decoded = dec.decodeKeyframesBySeek(ptsList, limit) { kf ->
                // Checked BEFORE the work, so a cancel taken during the previous
                // keyframe's decode does not pay for one more evaluation.
                if (isCancelled()) {
                    throw WardenAnalysisCancelledException(
                        "$CANCELLED: cancelled after ${frames.length()} of $total keyframes"
                    )
                }
                val e0 = System.nanoTime()
                val frame = WardenYuvFrame.of(kf)
                val bits = WardenCpuBaseline.evaluateYuv(frame, packed)
                lastEngineNs = System.nanoTime() - e0
                engineNs += lastEngineNs

                frames.put(
                    JSONObject()
                        .put("pts_us", kf.presentationTimeUs)
                        .put("fires", WardenEngineBench.bitsToHex(bits))
                )

                // Diagnostic only, and BOUNDED: layoutName() walks a whole chroma
                // plane, and the leading frames of a capture are often flat black,
                // which cannot discriminate NV12 from NV21. A handful of attempts
                // answers it in practice; paying it per keyframe for a label would
                // not be worth one millisecond of a multi-minute run.
                if (layout == WardenYuvFrame.LAYOUT_INDETERMINATE &&
                    layoutAttempts < MAX_LAYOUT_ATTEMPTS
                ) {
                    layoutAttempts++
                    layout = frame.layoutName()
                }

                val n = frames.length()
                if (n >= nextProgressAt || n == total) {
                    onProgress(n, total)
                    nextProgressAt = n + maxOf(1, total / PROGRESS_STEPS)
                }
            }
            decodeNs = dec.decodeNs
            out.put("decoder_flush_calls", dec.flushCalls)
            out.put("decoder_output_format_changes", dec.outputFormatChanges)
            out.put("keyframes_expected", total)
            out.put("keyframe_count_matches", decoded == total)
        }

        val wallNs = System.nanoTime() - wall0
        check(decoded > 0) {
            "decoded 0 keyframes from ${File(videoPath).name} — nothing was analysed"
        }

        out.put("n_keyframes", decoded)
        out.put("decoder_chroma_layout", layout)
        out.put("frames", frames)
        out.put(
            "timing",
            JSONObject()
                .put("wall_ms", wallNs / 1e6)
                .put("keyframe_index_ms", indexMs)
                .put("ms_per_keyframe_wall", wallNs / 1e6 / decoded)
                // Same nesting caveat the bench carries: `decodeNs` is assigned from
                // loop entry and snapshotted BEFORE onFrame, so it contains the
                // engine work of every frame but the last.
                .put("ms_per_keyframe_decode_excluding_engine",
                     (decodeNs - (engineNs - lastEngineNs)) / 1e6 / decoded)
                .put("ms_per_keyframe_engine", engineNs / 1e6 / decoded)
                .put(
                    "note",
                    "Wall-clock, on the production path. NOT a PERF-002 measurement — " +
                        "that is Story 12.4d's, end to end, on the reference device."
                )
        )
        Log.i(
            TAG,
            "analysed $decoded keyframes of ${File(videoPath).name} in " +
                "${"%.0f".format(wallNs / 1e6)} ms (engine ${"%.3f".format(engineNs / 1e6 / decoded)} ms/kf)"
        )
        return out
    }

    private fun refsJson(packed: WardenPackedRules): JSONArray {
        val arr = JSONArray()
        // 🔴 THE ORDER IS THE CONTRACT. `refs` is what the TS side aggregates by —
        // never positional arithmetic — and misaligning texel order is the failure
        // 12.2 lost a full parity run to (a transpose that "produced
        // plausible-looking detections from garbage" and passed every self-test).
        for (r in packed.refs) {
            arr.put(
                JSONObject()
                    .put("texel", r.texel)
                    .put("owning_class", r.owningClass)
                    .put("zone_id", r.zoneId)
                    .put("kind", r.kind)
                    .put("effective_weight", r.effectiveWeight)
            )
        }
        return arr
    }

    companion object {
        /** Progress callbacks per run, excluding the initial and final ones. */
        private const val PROGRESS_STEPS = 100
        private const val MAX_LAYOUT_ATTEMPTS = 8

        /**
         * Error-message prefixes the bridge maps onto reject codes, and the TS
         * seam maps onto user-facing outcomes. Kept as constants because a
         * message that is matched on is an API.
         */
        const val UNSUPPORTED_GEOMETRY = "WARDEN_UNSUPPORTED_GEOMETRY"
        const val CANCELLED = "WARDEN_ANALYSIS_CANCELLED"
    }
}
