package team.warden.mobile

import android.graphics.ImageFormat
import android.media.MediaCodec
import android.media.MediaCodecInfo
import android.media.MediaExtractor
import android.media.MediaFormat
import android.os.Handler
import android.os.HandlerThread
import android.util.Log
import java.nio.ByteBuffer

// Story 12.2 AC0b — keyframe-only decode. `-skip_frame nokey` has NO MediaCodec
// equivalent flag; this is the analogue, and it is the largest NEW engineering
// surface in the story (everything else is a port).
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// 🔴 WHAT IS ACTUALLY BOUND — CORRECTED 2026-09-17 BY STORY 12.4a (AC8).
//
// This header used to say A' was "what shipped". **IT IS NOT, AND IT NEVER WAS
// THE FASTER PATH.** architecture.md Decision #13 binds **STRATEGY A**, and the
// two were measured head to head on the same frames:
//
//   A  — **SHIPPED AND BOUND: 32.937 ms/kf.** ABSOLUTE
//        `MediaExtractor.seekTo(pts, SEEK_TO_CLOSEST_SYNC)` per keyframe, over
//        the PTS list built by [syncSamplePtsListBySeek]. Implemented by
//        [decodeKeyframesBySeek]. **This is the function to change.**
//   A' — **RETAINED FOR COMPARISON ONLY: 62.820 ms/kf — the SLOWER path.**
//        A single forward pass over the sample table, queueing only samples
//        flagged SAMPLE_FLAG_SYNC and skipping the rest with `advance()`.
//        Implemented by [decodeKeyframes]. It has no flush and no per-keyframe
//        EOS and is STILL ~2x slower, because `advance()` is NOT free and is NOT
//        metadata-only: `NuMediaExtractor::fetchTrackSamples` reads sample DATA
//        on every advance(), in batches of up to 8, so A' drags the whole 2.3 GB
//        through the extractor to reach one sample in 250. See
//        [countSyncSamplesByScan]. **Do not "simplify" toward A'.**
//   C  — the ffmpeg-kit control (WardenEngineBench), running 12.1's LITERAL
//        `-skip_frame nokey` on device for a directly comparable decode number.
//   B  — full decode + BUFFER_FLAG_KEY_FRAME filtering was NOT taken: it decodes
//        everything, which is the `select='eq(pict_type,I)'` mistake 12.1
//        measured at 5.4x slower on PC for zero decode saving.
//
// Carry **32.937 / 62.820**, NOT the 33.68 / 116.45 pair that was corrected
// during 12.2's delivery.
//
// A SEPARATE, NARROWER CLAIM THAT REMAINS TRUE: the *incremental* seek pattern
// `seekTo(lastPts + 1, SEEK_TO_NEXT_SYNC)` in a loop IS broken on this device —
// MEASURED at 2 sync samples against a ground truth of 1061
// (`device_seektest.json` -> `ac0b_prescribed_incremental_scan`). Absolute
// `SEEK_TO_CLOSEST_SYNC` is fine. Seeking is not broken; that ONE pattern is.
//
// 🔴 THE COUNT ASSERTION EARNED ITS KEEP. The decoded keyframe count is asserted
// against a ground-truth sample-table scan (NOT against the seek scan, which is
// the thing that was wrong). Had the loop trusted the seek scan, the bench would
// have reported a perfectly self-consistent `2 == 2` and a beautiful
// ms/keyframe figure computed over two frames. 12.1's analogue caught a
// CFR-duplication regression the same way.

private const val TAG = "WardenDecoder"

/** One decoded keyframe's payload, in whichever form the colour path needs. */
class WardenKeyframe(
    val presentationTimeUs: Long,
    val width: Int,
    val height: Int,
    /** Y/U/V planes + their strides, as the codec reported them. */
    val planes: Array<ByteBuffer>,
    val rowStrides: IntArray,
    val pixelStrides: IntArray,
)

data class WardenDecoderProfile(
    val codecName: String,
    val isHardwareAccelerated: Boolean,
    val mime: String,
    val width: Int,
    val height: Int,
    val durationUs: Long,
    val syncSampleCount: Int,
    val supportedColorFormats: List<Int>,
)

class WardenKeyframeDecoder(
    private val path: String,
) : AutoCloseable {

    private val extractor = MediaExtractor()
    private var codec: MediaCodec? = null
    private var trackIndex = -1
    private lateinit var format: MediaFormat

    var profile: WardenDecoderProfile? = null
        private set

    /** Accumulated nanoseconds spent inside decode, for the AC11 stage split. */
    var decodeNs: Long = 0
        private set

    /**
     * Every `MediaCodec.flush()` this decoder has actually issued. Incremented at
     * both remaining call sites (`decodeProbe`, `flushOnlyProbe`) and at none
     * other. Story 12.4b removed the third — `decodeKeyframesBySeekSurfaceLegacy`,
     * the Surface-only pre-12.4a loop — with the Surface path itself, so **no
     * decode path this app ships calls `flush()` any more**. The two that remain
     * are bench INSTRUMENTS whose structure is load-bearing: `decodeProbe` is the
     * A/B that measured the flush at 14.5 ms in the first place.
     *
     * 🔴 Added by the 2026-09-17 review because `pipelineProbe` used to report
     * `"flush_calls" to 0` as a LITERAL — an assertion about the code dressed as a
     * measurement. Stories 12.4b/c/d inherit this loop, and if a `flush()` were ever
     * reintroduced the artifact that exists to prove AC2 would have gone on
     * reporting zero. Now it is observed.
     */
    var flushCalls: Int = 0
        private set

    /**
     * How many times `dequeueOutputBuffer` reported `INFO_OUTPUT_FORMAT_CHANGED`
     * during the last pipelined decode. Added by the 2026-09-17 review: the drain
     * `when` had no `else`, so this sentinel — which essentially every decoder
     * raises at least once before its first frame — was silently swallowed AND
     * escaped the wedge counter. One is normal; more than one on a fixed-geometry
     * capture means the stream changed format mid-run, which the geometry checks
     * downstream would otherwise report several frames later and out of context.
     */
    var outputFormatChanges: Int = 0
        private set

    init {
        extractor.setDataSource(path)
        for (i in 0 until extractor.trackCount) {
            val f = extractor.getTrackFormat(i)
            if (f.getString(MediaFormat.KEY_MIME)?.startsWith("video/") == true) {
                trackIndex = i
                format = f
                break
            }
        }
        require(trackIndex >= 0) { "no video track in $path" }
        extractor.selectTrack(trackIndex)
    }

    /**
     * AC0b's binding assertion + AC1's decoder profile.
     *
     * Walks the sync-sample index WITHOUT decoding anything, which is both the
     * ground truth for the keyframe count and the PTS list the decode loop
     * consumes.
     *
     * 🔴 REVIEW 2026-09-15: that walk is a **62 s full-file read**, not an index
     * scan (see [countSyncSamplesByScan]). It used to run unconditionally, so an
     * `all` run paid it TWICE — once here via `deviceProfile`, once in the timing
     * block — and only the second was timed and reported, silently under-reporting
     * ~62 s of a run whose headline deliverable is 35 s. Callers that already hold
     * the ground truth now pass it in via [knownSyncCount]; callers that want the
     * profile WITHOUT the scan pass [scanSyncSamples] = false.
     *
     * 🔴 STORY 12.4a AC3 — [scanSyncSamples] DEFAULTS TO `false` AS OF 2026-09-17.
     * It used to default to `true`, so the 62 s walk was what you got unless you
     * knew to ask for anything else. Today nothing in production reaches it only
     * because [WardenDetectionEngineModule.describeDevice] happens to pass a null
     * video path — that is a coincidence, not a guarantee, and Story 12.4c wires a
     * real path in. Opting IN is now the only way to pay 62 s.
     *
     * @param scanSyncSamples run the 62 s ground-truth walk. **BENCH ONLY.** When
     *   false, [WardenDecoderProfile.syncSampleCount] carries [knownSyncCount]
     *   verbatim.
     * @param knownSyncCount a previously measured ground truth, or -1 for unknown.
     */
    fun probe(
        scanSyncSamples: Boolean = false,
        knownSyncCount: Int = -1,
    ): WardenDecoderProfile {
        val syncCount = if (scanSyncSamples) countSyncSamplesByScan() else knownSyncCount
        val mime = format.getString(MediaFormat.KEY_MIME)!!
        val codecName: String
        val hw: Boolean
        val colorFormats: List<Int>
        // Instantiating the codec is the only way to learn its NAME and whether
        // it is hardware-accelerated; MediaCodecList's "preferred" answer can
        // differ from what createDecoderByType actually hands back.
        val probeCodec = MediaCodec.createDecoderByType(mime)
        try {
            codecName = probeCodec.name
            val info: MediaCodecInfo = probeCodec.codecInfo
            hw = if (android.os.Build.VERSION.SDK_INT >= 29) info.isHardwareAccelerated else
                // Pre-29 heuristic: AOSP software decoders carry these prefixes.
                !(codecName.startsWith("OMX.google.") || codecName.startsWith("c2.android."))
            colorFormats = info.getCapabilitiesForType(mime).colorFormats.toList()
        } finally {
            probeCodec.release()
        }
        val p = WardenDecoderProfile(
            codecName = codecName,
            isHardwareAccelerated = hw,
            mime = mime,
            width = format.getInteger(MediaFormat.KEY_WIDTH),
            height = format.getInteger(MediaFormat.KEY_HEIGHT),
            durationUs = if (format.containsKey(MediaFormat.KEY_DURATION))
                format.getLong(MediaFormat.KEY_DURATION) else -1L,
            syncSampleCount = syncCount,
            supportedColorFormats = colorFormats,
        )
        profile = p
        Log.i(TAG, "decoder=$codecName hw=$hw sync samples=$syncCount")
        return p
    }

    /**
     * 🔴 Ground-truth sync-sample count, by walking the sample table.
     *
     * The seek-based scan AC0b Option A prescribes — `seekTo(t + 1,
     * SEEK_TO_NEXT_SYNC)` in a loop — is NOT reliable on this file/device.
     * MEASURED: it terminates after **2** sync samples on the 2.3 GB / 4419 s
     * capture, against an ffprobe ground truth of **1061** at a dead-regular
     * 4.1667 s GOP. `MediaExtractor.seekTo` simply stops advancing past the
     * second sync point here.
     *
     * That is precisely why AC0b made the count assertion binding rather than
     * decorative: had the decode loop trusted the seek scan, the bench would have
     * reported a perfectly self-consistent `2 == 2` and a beautiful ms/keyframe
     * figure computed over two frames.
     *
     * 🔴 CORRECTED 2026-09-15 — THIS WALK IS **NOT** CHEAP AND **NOT**
     * METADATA-ONLY. An earlier version of this comment claimed `advance()`
     * merely parses the sample table. That is false:
     * `NuMediaExtractor::fetchTrackSamples` READS SAMPLE DATA on every
     * `advance()` as well as on every `seekTo`, in batches of up to
     * `mMaxFetchCount = 8` for video tracks. So this walk pulls the whole 2.3 GB
     * through the extractor.
     *
     * MEASURED COST: **62 s**. It is a bench-time correctness assertion and
     * **MUST NEVER RUN IN PRODUCTION** — it alone would cost nearly twice the
     * entire 35 s analysis. Story 12.4 must take the keyframe index from
     * [syncSamplePtsListBySeek] (2.3 s) or from a direct `stss` read, never from
     * here.
     */
    // 🔴🔴 BENCH-ONLY GROUND TRUTH. 62 SECONDS. NEVER CALL THIS FROM A SHIPPING
    // PATH — Story 12.4a AC3, architecture.md Decision #13. It is reachable from
    // `all` / `timing` / `seektest` in WardenEngineBench and from NOWHERE ELSE;
    // [probe] will not run it unless you explicitly pass scanSyncSamples = true.
    // The production keyframe index is [syncSamplePtsListBySeek] (2.290 s).
    fun countSyncSamplesByScan(): Int {
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        var n = 0
        while (extractor.sampleTime >= 0) {
            if (extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC != 0) n++
            if (!extractor.advance()) break
        }
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        return n
    }

    /**
     * DIAGNOSTIC — does `seekTo` work when given ABSOLUTE targets?
     *
     * The incremental form (`seekTo(lastPts + 1, SEEK_TO_NEXT_SYNC)`) stops
     * advancing after the second sync sample on this file. Before accepting the
     * much more expensive single-pass demux as the only option, this checks
     * whether seeking is broken outright or only in that incremental pattern —
     * the difference is worth ~an order of magnitude on the headline decode
     * number, so it is worth one experiment rather than an assumption.
     */
    fun seekProbe(gopUs: Long, n: Int): List<Long> {
        val out = ArrayList<Long>(n)
        for (k in 0 until n) {
            extractor.seekTo(k * gopUs, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            out.add(extractor.sampleTime)
        }
        return out
    }

    /**
     * 🔴 AC0b OPTION A **EXACTLY AS THE STORY PRESCRIBES IT**, so the amendment
     * that rejected it finally has evidence.
     *
     * Story 12.2 amended AC0b on the claim that the incremental scan —
     * `seekTo(lastPts + 1, SEEK_TO_NEXT_SYNC)` in a loop — "stops advancing after
     * the second sync sample, reporting 2 keyframes against a ground truth of
     * 1061". That claim drove the shipped decode strategy and is inherited by
     * Story 12.4, and it had **no archived artifact**: `keyframe-decode-perf-
     * research.md` records it as *"Non résolu"*, and [seekProbe] — the mode
     * REPORT.md §10 advertised as covering this — measures ABSOLUTE
     * `SEEK_TO_CLOSEST_SYNC` seeks, i.e. the strategy that works, not the one
     * under dispute. Archiving that would have looked like evidence and been none.
     *
     * This runs the disputed pattern and nothing else. Whatever it returns is the
     * answer: a short list vindicates the amendment, a full one means AC0b Option
     * A was fine and the shipped strategy was chosen on a misdiagnosis. Both are
     * worth knowing before 12.4 inherits the decision.
     *
     * @param maxSteps hard cap so a pathological file cannot hang the probe.
     */
    fun incrementalNextSyncScan(maxSteps: Int = 4000): List<Long> {
        val out = ArrayList<Long>()
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_NEXT_SYNC)
        var last = -1L
        var steps = 0
        while (steps++ < maxSteps) {
            val t = extractor.sampleTime
            // The AC's own termination rule: "verify the seek loop terminates
            // (advance past the returned sampleTime)".
            if (t < 0 || t <= last) break
            out.add(t)
            last = t
            extractor.seekTo(last + 1, MediaExtractor.SEEK_TO_NEXT_SYNC)
        }
        return out
    }

    /**
     * DIAGNOSTIC (§6 of the keyframe-decode-perf research) — where do the 33 ms go?
     *
     * The research derives, WITHOUT instrumentation, that ~25.7 ms of the 32.9 ms
     * seek-strategy cost is `flush()` + the `END_OF_STREAM` drain + pipeline
     * restart, and only ~4.3 ms is actual decoding. That derivation rests on
     * `250 x 0.234 ms` of demux in strategy A-prime, which in turn rests on the
     * 62.1 s full sample-table walk. It is arithmetic on two measurements, not a
     * measurement — so it is falsifiable, and this falsifies or confirms it
     * before a single line of the decode loop is rewritten.
     *
     * Runs the CURRENT strategy-A loop unchanged in structure, timing each stage
     * separately. The prediction under test: **flush alone lands in 15-25 ms.**
     * If it does not, the decomposition is wrong and the rewrite is unjustified.
     */
    fun decodeProbe(ptsList: LongArray, n: Int): Map<String, Any> {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()

        val seekNs = ArrayList<Long>(n)
        val flushNs = ArrayList<Long>(n)
        val queueToOutNs = ArrayList<Long>(n)
        var tryAgainCount = 0L
        var tryAgainNs = 0L
        var decoded = 0

        val readBefore = procSelfIoReadBytes()
        val target = minOf(n, ptsList.size)
        val wall0 = System.nanoTime()

        for (idx in 0 until target) {
            val pts = ptsList[idx]

            var t = System.nanoTime()
            extractor.seekTo(pts, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            seekNs.add(System.nanoTime() - t)

            // (1) flush() ALONE — the headline number this probe exists for.
            t = System.nanoTime()
            flushCalls++; c.flush()
            flushNs.add(System.nanoTime() - t)

            var sampleQueued = false
            var eosQueued = false
            var got = false
            var spins = 0
            var queuedAt = 0L

            while (!got) {
                if (!eosQueued) {
                    val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                    if (inIdx >= 0) {
                        if (!sampleQueued) {
                            val buf = c.getInputBuffer(inIdx)!!
                            val size = extractor.readSampleData(buf, 0)
                            if (size < 0) {
                                c.queueInputBuffer(inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                                eosQueued = true
                            } else {
                                // (2) clock starts when the IDR enters the codec.
                                queuedAt = System.nanoTime()
                                c.queueInputBuffer(
                                    inIdx, 0, size, extractor.sampleTime,
                                    MediaCodec.BUFFER_FLAG_KEY_FRAME
                                )
                                sampleQueued = true
                            }
                        } else {
                            c.queueInputBuffer(inIdx, 0, 0, pts, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                            eosQueued = true
                        }
                    }
                }
                // (3) every INFO_TRY_AGAIN_LATER is a potential TIMEOUT_US-long sleep.
                val t2 = System.nanoTime()
                val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
                when {
                    outIdx >= 0 -> {
                        val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                        if (info.size > 0) {
                            if (queuedAt != 0L) queueToOutNs.add(System.nanoTime() - queuedAt)
                            c.releaseOutputBuffer(outIdx, false)
                            decoded++
                            got = true
                        } else {
                            c.releaseOutputBuffer(outIdx, false)
                            if (eos) got = true
                        }
                    }
                    outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                        tryAgainCount++
                        tryAgainNs += System.nanoTime() - t2
                        if (++spins > MAX_SPINS) throw IllegalStateException("probe stalled at $idx")
                    }
                }
            }
        }
        val wallNs = System.nanoTime() - wall0
        val readAfter = procSelfIoReadBytes()

        fun med(v: List<Long>): Double {
            if (v.isEmpty()) return 0.0
            val s = v.sorted(); val m = s.size / 2
            return (if (s.size % 2 == 1) s[m].toDouble() else (s[m - 1] + s[m]) / 2.0) / 1e6
        }
        fun mean(v: List<Long>) = if (v.isEmpty()) 0.0 else v.sum() / 1e6 / v.size

        return linkedMapOf(
            "keyframes" to decoded,
            "wall_ms_per_keyframe" to wallNs / 1e6 / maxOf(1, decoded),
            "seek_ms_median" to med(seekNs),
            "seek_ms_mean" to mean(seekNs),
            "flush_ms_median" to med(flushNs),
            "flush_ms_mean" to mean(flushNs),
            "flush_ms_max" to (flushNs.maxOrNull() ?: 0L) / 1e6,
            "queue_to_first_output_ms_median" to med(queueToOutNs),
            "queue_to_first_output_ms_mean" to mean(queueToOutNs),
            "try_again_count_total" to tryAgainCount,
            "try_again_per_keyframe" to tryAgainCount.toDouble() / maxOf(1, decoded),
            "try_again_ms_total" to tryAgainNs / 1e6,
            "try_again_ms_per_keyframe" to tryAgainNs / 1e6 / maxOf(1, decoded),
            "timeout_us_used" to TIMEOUT_US,
            "read_bytes_delta" to (readAfter - readBefore),
            "read_mb_per_keyframe" to (readAfter - readBefore) / 1048576.0 / maxOf(1, decoded),
            "prediction_under_test" to
                "research §2 derives flush+drain ~= 25.7 ms/kf and real decode ~= 4.3 ms. " +
                "If flush_ms_median is NOT in 15-25 ms, the decomposition is refuted.",
        )
    }

    /**
     * `flush()` back-to-back on an otherwise idle codec, for contrast with the
     * in-loop figure. If the in-loop flush is expensive but the idle flush is
     * cheap, the cost is draining in-flight work rather than the HFI round trip
     * itself — a different fix.
     */
    fun flushOnlyProbe(reps: Int): Map<String, Any> {
        configureCodec()
        val c = codec!!
        val ns = ArrayList<Long>(reps)
        for (i in 0 until reps) {
            val t = System.nanoTime()
            flushCalls++; c.flush()
            ns.add(System.nanoTime() - t)
        }
        val s = ns.sorted()
        return linkedMapOf(
            "reps" to reps,
            "idle_flush_ms_median" to s[s.size / 2] / 1e6,
            "idle_flush_ms_mean" to ns.sum() / 1e6 / ns.size,
            "idle_flush_ms_max" to s.last() / 1e6,
        )
    }

    /** Bytes this process has actually read from storage. -1 if unreadable. */
    private fun procSelfIoReadBytes(): Long = try {
        java.io.File("/proc/self/io").readLines()
            .firstOrNull { it.startsWith("read_bytes:") }
            ?.substringAfter(':')?.trim()?.toLong() ?: -1L
    } catch (t: Throwable) { -1L }

    /**
     * The keyframe PTS list, built with ABSOLUTE `SEEK_TO_CLOSEST_SYNC` seeks.
     *
     * MEASURED on this device: `SEEK_TO_CLOSEST_SYNC` with an absolute target is
     * correct and costs ~2.9 ms, while the incremental
     * `SEEK_TO_NEXT_SYNC(lastPts + 1)` pattern stops advancing after the second
     * sync sample. So seeking is not broken — that ONE pattern is.
     *
     * The GOP is estimated from the first two keyframes and then stepped. Any
     * step that fails to advance is treated as the end of a REGULAR GOP
     * assumption, not as the end of the file: the caller still asserts the
     * resulting count against the ground-truth sample-table scan, so an irregular
     * GOP shows up as a mismatch rather than as silently-missing keyframes.
     */
    fun syncSamplePtsListBySeek(maxCount: Int = 100_000): LongArray {
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
        val first = extractor.sampleTime
        if (first < 0) return LongArray(0)
        // Probe the second keyframe to learn the GOP rather than assuming one.
        var gop = -1L
        var probe = 100_000L
        while (probe < 60_000_000L) {
            extractor.seekTo(first + probe, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            val t = extractor.sampleTime
            if (t > first) { gop = t - first; break }
            probe *= 2
        }
        if (gop <= 0) return longArrayOf(first)

        val out = ArrayList<Long>()
        out.add(first)
        var last = first
        var k = 1L
        while (out.size < maxCount) {
            // Seek to the MIDPOINT past the last keyframe: CLOSEST_SYNC then
            // resolves to the next one even if the GOP drifts by up to half a
            // period, which a naive exact-multiple step would not tolerate.
            extractor.seekTo(first + k * gop, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            val t = extractor.sampleTime
            if (t < 0 || t <= last) break
            out.add(t)
            last = t
            k++
        }
        return out.toLongArray()
    }

    /**
     * STRATEGY A — decode by SEEKING to each keyframe. **THE BOUND PATH**
     * (architecture.md Decision #13, 32.937 ms/kf against A-prime's 62.820).
     *
     * 🔴 RESTRUCTURED 2026-09-17 BY STORY 12.4a (AC2). It used to be, per keyframe:
     * `seekTo` -> `flush()` -> queue sample -> queue `END_OF_STREAM` -> drain.
     * **`flush()` alone was MEASURED at 14.11 ms/kf in that loop against 3.59 ms on
     * an idle codec** (`device_probe_flush.json` + `idle_flush_probe`, 100 kf x 3),
     * so the cost was the `END_OF_STREAM` -> flush state transition, not the HFI
     * round trip — i.e. it was ours, and it was ~34% of a 42.2 ms wall.
     *
     * It is now PIPELINED: [PIPELINE_DEPTH] keyframes are kept in flight, and no
     * `flush()` happens at all. An IDR resets the DPB **by definition**, and every
     * sample here is reached by an absolute `SEEK_TO_CLOSEST_SYNC` and verified
     * `SAMPLE_FLAG_SYNC`, so each is self-contained and needs no reset between it
     * and the next.
     *
     * 🔴 OUTPUTS ARE MATCHED TO REQUESTS BY PTS, NEVER BY ARRIVAL ORDER. That is
     * not defensive styling — it is the one failure mode pipelining introduces
     * (Story 12.4a AC5), and the in-flight set turns "the decoder handed back a
     * frame we never asked for, or handed the same one twice" from a silent
     * pixel-level parity drift into an exception at the point of the defect.
     *
     * 🔴 THE TAIL STILL NEEDS ONE `END_OF_STREAM` — ONCE PER RUN, NOT PER KEYFRAME.
     * Trap 2 has not gone away: a hardware decoder holds frames for reorder, so the
     * last few keyframes do not come out on their own. Removing the flush does not
     * remove that; it removes paying for it 1061 times.
     *
     * 🔴 THERE IS NO LONGER A SECOND LOOP. Until Story 12.4b this dispatched to
     * `decodeKeyframesBySeekSurfaceLegacy` whenever a Surface was supplied — the
     * pre-12.4a seek/flush/EOS/drain loop, retained because Path Z's
     * `WardenSurfaceTextureHost` consumed ONE posted frame at a time and could not
     * take a pipeline. 12.4b removed Path Z, so the branch, the legacy loop and
     * **the last `flush()` outside the two bench instruments** went with it.
     */
    fun decodeKeyframesBySeek(
        ptsList: LongArray,
        limit: Int = 0,
        onFrame: (WardenKeyframe) -> Unit,
    ): Int {
        val target = if (limit > 0) minOf(limit, ptsList.size) else ptsList.size
        if (target == 0) return 0
        return decodeKeyframesBySeekPipelined(ptsList, target, onFrame)
    }

    /**
     * Seek to [pts], and prove the extractor actually got there.
     *
     * 🔴 REVIEW 2026-09-15, PRESERVED THROUGH THE 12.4a RESTRUCTURE. The loop used
     * to queue whatever `extractor.sampleTime` happened to be and increment
     * `decoded`. If the seek landed on a different sync sample — or on the SAME one
     * as the previous iteration — the same frame was decoded N times and counted as
     * N distinct keyframes, inflating the divisor of every ms_per_keyframe figure
     * while the per-rule fire rows silently repeated under different `pts_us` keys.
     * `keyframe_count_matches` could never catch it, because a repeated landing
     * still increments `decoded` toward `syncCount`.
     */
    private fun seekToVerifiedSyncSample(idx: Int, pts: Long) {
        extractor.seekTo(pts, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
        val landed = extractor.sampleTime
        if (landed != pts) {
            throw IllegalStateException(
                "keyframe $idx: seekTo($pts, SEEK_TO_CLOSEST_SYNC) landed on " +
                    "sampleTime=$landed. The decode loop consumes a PTS list built " +
                    "by syncSamplePtsListBySeek, so a mismatch means the extractor " +
                    "is not addressing the sync sample that list names — every " +
                    "downstream per-keyframe figure would be computed over the " +
                    "wrong set of frames."
            )
        }
        if ((extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC) == 0) {
            throw IllegalStateException(
                "keyframe $idx (pts=$pts): the sample the extractor landed on is " +
                    "NOT flagged SAMPLE_FLAG_SYNC. Decoding a non-sync sample in " +
                    "isolation is undefined — it would reference frames the decoder " +
                    "never saw."
            )
        }
    }

    /** AC2 — the flush-free pipelined loop. Path P only. */
    private fun decodeKeyframesBySeekPipelined(
        ptsList: LongArray,
        target: Int,
        onFrame: (WardenKeyframe) -> Unit,
    ): Int {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        val t0 = System.nanoTime()

        // Queued into the codec but not yet delivered. The MATCHING SET for AC5.
        val inFlight = HashSet<Long>()
        var nextToQueue = 0
        var decoded = 0
        var eosQueued = false
        var spins = 0
        outputFormatChanges = 0

        while (decoded < target) {
            // (1) Top the pipeline up. Non-blocking: if the codec is holding every
            //     input buffer, that is not an error, it is backpressure — fall
            //     through and drain instead of waiting for a buffer.
            while (nextToQueue < target && inFlight.size < PIPELINE_DEPTH) {
                val inIdx = c.dequeueInputBuffer(0L)
                if (inIdx < 0) break
                val pts = ptsList[nextToQueue]
                // 🔴 REVIEW 2026-09-17 — A DUPLICATE PTS CORRUPTS THE MATCHING SET.
                // inFlight is a HashSet, so a repeated PTS queues two samples and
                // records one: the `inFlight.size < PIPELINE_DEPTH` throttle stops
                // bounding the pipeline, and when the second copy comes out the
                // `remove` below fails and blames the DECODER for a duplicate the
                // CALLER supplied. syncSamplePtsListBySeek is strictly increasing
                // so this cannot fire on the bound path, but decodeKeyframesBySeek
                // is public and takes an arbitrary LongArray.
                if (!inFlight.add(pts)) {
                    throw IllegalStateException(
                        "keyframe $nextToQueue (pts=$pts): that PTS is ALREADY IN FLIGHT, " +
                            "so ptsList contains it twice. Outputs are matched to requests " +
                            "by PTS, which makes a duplicate unresolvable — the caller must " +
                            "pass a list of DISTINCT sync-sample timestamps."
                    )
                }
                seekToVerifiedSyncSample(nextToQueue, pts)
                val buf = c.getInputBuffer(inIdx)!!
                val size = extractor.readSampleData(buf, 0)
                // `<= 0`, not `< 0`: a zero-length sample is queued with no EOS flag,
                // produces no output, and its PTS can then NEVER leave inFlight — the
                // run dies later at the EOS check below, misattributed to the decoder
                // "dropping queued IDRs" (review 2026-09-17).
                if (size <= 0) {
                    throw IllegalStateException(
                        "keyframe $nextToQueue (pts=$pts): readSampleData returned $size " +
                            "after a VERIFIED landing on that sync sample — the extractor " +
                            "has a sample time but no usable sample data."
                    )
                }
                c.queueInputBuffer(inIdx, 0, size, pts, MediaCodec.BUFFER_FLAG_KEY_FRAME)
                nextToQueue++
            }

            // (2) Every sample is in. ONE end-of-stream drains the reorder buffer —
            //     the whole saving is that this happens here and not 1061 times.
            //
            // 🔴 REVIEW 2026-09-17 — THE EOS PTS MUST NOT COLLIDE WITH A KEYFRAME'S.
            // This used to stamp the EOS input `0L`, which is EXACTLY keyframe 0's
            // PTS on this capture (and on any capture starting at zero). It survives
            // on c2.qti.avc.decoder only because that codec reports EOS on a
            // ZERO-SIZE buffer, which takes the `info.size == 0` branch below.
            // MediaCodec explicitly permits flagging EOS on the last DATA-BEARING
            // buffer, and such a codec would propagate this timestamp, fail
            // `inFlight.remove(0L)` after keyframe 0 was already delivered, and kill
            // a bit-perfect 1061-frame run at the finish line — blaming the decoder
            // for a timestamp we chose. [EOS_PTS] cannot collide: it is past any
            // real sample time.
            if (!eosQueued && nextToQueue >= target) {
                val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                if (inIdx >= 0) {
                    c.queueInputBuffer(inIdx, 0, 0, EOS_PTS, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                    eosQueued = true
                }
            }

            // (3) Drain.
            val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
            when {
                outIdx >= 0 -> {
                    val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                    // A data-bearing buffer whose PTS is the EOS marker is the drain
                    // signal, not a frame — never a keyframe we asked for.
                    if (info.size > 0 && info.presentationTimeUs != EOS_PTS) {
                        val pts = info.presentationTimeUs
                        if (!inFlight.remove(pts)) {
                            throw IllegalStateException(
                                "the decoder returned a frame with pts=$pts that is not in " +
                                    "flight. Three causes, in order of likelihood on an " +
                                    "untested codec: (1) it ALTERED the timestamp we queued " +
                                    "— outputs are matched by exact PTS equality, so a codec " +
                                    "that round-trips through a 90 kHz clock or re-bases the " +
                                    "first PTS breaks every frame; (2) it was already " +
                                    "delivered (a duplicate); (3) it was never queued. " +
                                    "decoded=$decoded/$target, queued=$nextToQueue, " +
                                    "inFlight(${inFlight.size})=${inFlight.sorted().take(8)}" +
                                    "${if (inFlight.size > 8) "…" else ""}. Matching by PTS " +
                                    "is what surfaces this here instead of as a parity drift " +
                                    "2666 frames later."
                            )
                        }
                        val kf = imageToKeyframe(c, outIdx, pts)
                        decodeNs = System.nanoTime() - t0
                        c.releaseOutputBuffer(outIdx, false)
                        onFrame(kf)
                        decoded++
                        spins = 0
                    } else {
                        c.releaseOutputBuffer(outIdx, false)
                        if (eos && decoded < target) {
                            throw IllegalStateException(
                                "END_OF_STREAM after $decoded of $target keyframes, with " +
                                    "${inFlight.size} still in flight " +
                                    "(${inFlight.sorted().take(8)}" +
                                    "${if (inFlight.size > 8) "…" else ""}). The decoder " +
                                    "dropped those queued IDRs rather than decoding them."
                            )
                        }
                    }
                }
                outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                    // 🔴 WHICH CAP APPLIES, AND WHY IT IS THE GENEROUS ONE FOR MOST OF
                    // THE RUN (review 2026-09-17). `eosQueued` only turns true once
                    // EVERY sample is in, so for ~1053 of 1061 keyframes this path is
                    // guarded by MAX_SPINS_BEFORE_EOS (20 s) and only the tail drain by
                    // MAX_SPINS (5 s). That is DELIBERATE and is not the A′ rationale in
                    // the companion object: here a stall before EOS IS the k-too-small
                    // failure (see [PIPELINE_DEPTH]), which deserves the generous budget
                    // because bailing early would report a device limit as a crash.
                    val cap = if (eosQueued) MAX_SPINS else MAX_SPINS_BEFORE_EOS
                    if (++spins > cap) {
                        throw IllegalStateException(
                            "no output for ${cap * TIMEOUT_US / 1000} ms " +
                                "($cap polls at ${TIMEOUT_US}us) " +
                                "(decoded=$decoded/$target, queued=$nextToQueue, " +
                                "inFlight=${inFlight.size}, eosQueued=$eosQueued). " +
                                if (!eosQueued && decoded == 0)
                                    "NOTHING has come out at all: the most likely cause is " +
                                    "that this codec needs MORE than PIPELINE_DEPTH=" +
                                    "$PIPELINE_DEPTH IDRs in flight before it emits. See " +
                                    "the PIPELINE_DEPTH KDoc — raise it and re-run the sweep."
                                else ""
                        )
                    }
                }
                // 🔴 REVIEW 2026-09-17 — EVERY OTHER SENTINEL MUST STILL BE COUNTED.
                // INFO_OUTPUT_FORMAT_CHANGED (-2) is returned by essentially every
                // decoder before its first frame, and INFO_OUTPUT_BUFFERS_CHANGED (-3)
                // on legacy paths. Both return IMMEDIATELY, consuming no timeout. With
                // no branch here they bypassed `spins` entirely, so a codec stuck
                // re-raising one spun this loop at 100% CPU with NO cap and NO timeout
                // — the one hang the wedge budget exists to prevent was the one it
                // could not catch.
                else -> {
                    if (outIdx == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED) {
                        outputFormatChanges++
                    }
                    if (++spins > MAX_SPINS) {
                        throw IllegalStateException(
                            "dequeueOutputBuffer returned $outIdx on $MAX_SPINS consecutive " +
                                "polls without producing a frame (decoded=$decoded/$target, " +
                                "eosQueued=$eosQueued). These sentinels do not consume the " +
                                "timeout, so this is a busy spin, not a slow decoder."
                        )
                    }
                }
            }
        }
        // 🔴 Same nesting caveat as decodeKeyframes: decodeNs is assigned from t0
        // (loop entry) and snapshotted BEFORE onFrame(), so every downstream stage
        // of frames 0..N-2 is inside it. Use timingRun's `decode_excluding_gl` /
        // `gl_total` for a disjoint split.
        return decoded
    }

    /**
     * AC0a — the *k* sweep, so [PIPELINE_DEPTH] is MEASURED rather than picked.
     *
     * Runs the pipelined structure at a given depth over the same keyframes the
     * [decodeProbe] baseline used, releasing outputs without copying planes so the
     * two walls are comparable. `depth = 1` is the degenerate case and is included
     * on purpose: it is the same loop with no pipelining, so it separates "removing
     * the flush helped" from "keeping k frames in flight helped".
     */
    fun pipelineProbe(ptsList: LongArray, n: Int, depth: Int): Map<String, Any> {
        // 🔴 REVIEW 2026-09-17 — VALIDATE THE ARGUMENT THAT IS THE WHOLE POINT OF
        // THIS FUNCTION. `depth = 0` never queues anything, so `nextToQueue >= target`
        // is never true, EOS is never sent, and it spun for 20 s before throwing
        // "wedged at depth=0" — blaming the codec for a caller's argument.
        require(depth >= 1) { "pipelineProbe: depth must be >= 1, got $depth" }
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        val target = minOf(n, ptsList.size)

        val inFlight = HashSet<Long>()
        var nextToQueue = 0
        var decoded = 0
        var eosQueued = false
        var spins = 0
        var tryAgainCount = 0L
        var tryAgainNs = 0L
        var seekNs = 0L
        var mismatches = 0
        var unmatchedDeliveries = 0
        flushCalls = 0
        // 🔴 Does `depth` actually reach the codec? dequeueInputBuffer(0L) breaks on
        // -1, so the effective depth is min(depth, available input buffers). Without
        // this, a flat k=8/k=16 result cannot be told from a hardware ceiling.
        var maxObservedInFlight = 0
        var shortDecodeReason: String? = null

        val readBefore = procSelfIoReadBytes()
        val wall0 = System.nanoTime()
        while (decoded < target) {
            while (nextToQueue < target && inFlight.size < depth) {
                val inIdx = c.dequeueInputBuffer(0L)
                if (inIdx < 0) break
                val pts = ptsList[nextToQueue]
                val ts = System.nanoTime()
                seekToVerifiedSyncSample(nextToQueue, pts)
                seekNs += System.nanoTime() - ts
                val buf = c.getInputBuffer(inIdx)!!
                val size = extractor.readSampleData(buf, 0)
                if (size <= 0) throw IllegalStateException("no sample data at pts=$pts (size=$size)")
                c.queueInputBuffer(inIdx, 0, size, pts, MediaCodec.BUFFER_FLAG_KEY_FRAME)
                if (!inFlight.add(pts)) {
                    throw IllegalStateException("duplicate pts=$pts in ptsList at index $nextToQueue")
                }
                if (inFlight.size > maxObservedInFlight) maxObservedInFlight = inFlight.size
                nextToQueue++
            }
            if (!eosQueued && nextToQueue >= target) {
                val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                if (inIdx >= 0) {
                    // Same non-colliding marker as the bound loop — see [EOS_PTS].
                    c.queueInputBuffer(inIdx, 0, 0, EOS_PTS, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                    eosQueued = true
                }
            }
            val t2 = System.nanoTime()
            val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
            when {
                outIdx >= 0 -> {
                    val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                    if (info.size > 0 && info.presentationTimeUs != EOS_PTS) {
                        // 🔴 REVIEW 2026-09-17 — ONLY A MATCHED FRAME COUNTS.
                        // `decoded` is the DIVISOR of every headline below, and it
                        // used to be incremented even when the PTS was one we never
                        // queued. A depth that mis-delivered therefore reported a
                        // BETTER ms/kf than one that did not — the metric improved as
                        // correctness degraded, in the instrument that chose k=8.
                        if (inFlight.remove(info.presentationTimeUs)) {
                            decoded++
                        } else {
                            mismatches++
                            unmatchedDeliveries++
                        }
                        c.releaseOutputBuffer(outIdx, false)
                        spins = 0
                    } else {
                        c.releaseOutputBuffer(outIdx, false)
                        if (eos && decoded < target) {
                            // Was a SILENT `break`: the returned map carried no error
                            // key, so the bench's catch never fired and a depth that
                            // decoded 3 of 100 landed in the sweep table looking like a
                            // measurement, directly comparable to full runs.
                            shortDecodeReason =
                                "END_OF_STREAM after $decoded of $target decoded " +
                                    "(${inFlight.size} still in flight, " +
                                    "$unmatchedDeliveries unmatched deliveries)"
                            break
                        }
                    }
                }
                outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                    tryAgainCount++
                    tryAgainNs += System.nanoTime() - t2
                    val cap = if (eosQueued) MAX_SPINS else MAX_SPINS_BEFORE_EOS
                    if (++spins > cap) throw IllegalStateException(
                        "pipelineProbe wedged at depth=$depth after " +
                            "${cap * TIMEOUT_US / 1000} ms without output " +
                            "(decoded=$decoded/$target, queued=$nextToQueue, " +
                            "inFlight=${inFlight.size}, maxInFlight=$maxObservedInFlight, " +
                            "eosQueued=$eosQueued)"
                    )
                }
                else -> {
                    if (++spins > MAX_SPINS) throw IllegalStateException(
                        "pipelineProbe at depth=$depth: dequeueOutputBuffer returned " +
                            "$outIdx on $MAX_SPINS consecutive polls (decoded=$decoded/$target)"
                    )
                }
            }
        }
        val wallNs = System.nanoTime() - wall0
        val readAfter = procSelfIoReadBytes()
        val complete = decoded == target && mismatches == 0 && shortDecodeReason == null
        return linkedMapOf(
            "pipeline_depth" to depth,
            "keyframes_requested" to target,
            "keyframes_decoded" to decoded,
            // 🔴 `all_decoded` alone was tautologically true on every non-break exit,
            // because the loop condition IS `decoded < target`. `comparable` is the
            // field a reader should gate on before putting a row in a table.
            "all_decoded" to (decoded == target),
            "comparable" to complete,
            "pts_mismatches" to mismatches,
            "unmatched_deliveries" to unmatchedDeliveries,
            "max_observed_in_flight" to maxObservedInFlight,
            "depth_actually_reached" to (maxObservedInFlight >= depth),
            "wall_ms_per_keyframe" to wallNs / 1e6 / maxOf(1, decoded),
            "wall_ms_total" to wallNs / 1e6,
            "seek_ms_per_keyframe" to seekNs / 1e6 / maxOf(1, decoded),
            "try_again_count_total" to tryAgainCount,
            "try_again_per_keyframe" to tryAgainCount.toDouble() / maxOf(1, decoded),
            "try_again_ms_per_keyframe" to tryAgainNs / 1e6 / maxOf(1, decoded),
            // OBSERVED, not asserted: this loop calls flush() nowhere, and counting it
            // means a reintroduced flush() cannot silently keep reporting zero.
            "flush_calls" to flushCalls,
            "timeout_us_used" to TIMEOUT_US,
            "read_mb_per_keyframe" to (readAfter - readBefore) / 1048576.0 / maxOf(1, decoded),
        ).apply {
            val reason = shortDecodeReason
            if (reason != null) put("error", reason)
        }
    }

    private fun configureCodec() {
        // 🔴 STORY 12.4c — RELEASE BEFORE REPLACE (deferred item from the 12.4a
        // review, homed here because this file now serves a SHIPPING path).
        // This used to overwrite `codec` unconditionally, leaking the previous
        // MediaCodec on any instance that decodes twice — and the pipelined loop
        // ends in end-of-stream state, so a reused codec would also produce no
        // output and then wedge for 5 s. Nothing in production reaches it twice
        // (the analyzer builds one decoder per session inside `use {}`), but the
        // bench modes do run several probes per instance.
        codec?.let { stale ->
            try { stale.stop() } catch (_: Throwable) {}
            stale.release()
            codec = null
        }
        val mime = format.getString(MediaFormat.KEY_MIME)!!
        val c = MediaCodec.createDecoderByType(mime)
        // 🔴 PATH P, AND NOW THE ONLY PATH. Flexible YUV 4:2:0 so getOutputImage()
        // hands back planes with device-reported strides — which is exactly what
        // WardenColorConvert reads. NEVER assume rowStride == width.
        //
        // Story 12.4b removed the `toSurface` alternative (Path Z: decode straight
        // into a SurfaceTexture for the GPU shader). It was never bound; it existed
        // only to feed the mega-shader architecture.md Decision #13 rejected, and
        // its zero-copy conversion was DRIVER-DEFINED — it diverged from bit-parity
        // on 0.888% of decisions, including 44 of the 69 low-saturation rules.
        // Removing the choice is how the CPU arm got a predictable colour path.
        format.setInteger(
            MediaFormat.KEY_COLOR_FORMAT,
            MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible
        )
        c.configure(format, null, null, 0)
        c.start()
        codec = c
    }

    /**
     * Decode every keyframe, invoking [onFrame] for each.
     *
     * Returns the number of keyframes decoded. The caller asserts it against
     * [WardenDecoderProfile.syncSampleCount].
     *
     * @param limit stop after this many keyframes (0 = all). Used for warm-up
     *   runs and for the AC3 single-frame diff.
     */
    fun decodeKeyframes(limit: Int = 0, onFrame: (WardenKeyframe) -> Unit): Int {
        // SINGLE FORWARD PASS, sync-filtered — the true `-skip_frame nokey`
        // analogue, and a closer one than the seek loop it replaces.
        //
        // FFmpeg's `-skip_frame nokey` does NOT seek: it demuxes every packet and
        // instructs the decoder to skip non-keyframes. This does exactly that —
        // `advance()` walks past non-sync samples without decoding them, and only
        // sync samples are queued. Consecutive IDR frames decode back-to-back
        // with no flush, so the per-keyframe seek + flush + END_OF_STREAM
        // round-trip disappears entirely.
        //
        // It also sidesteps the measured `seekTo` defect (see
        // countSyncSamplesByScan): correctness here does not depend on seeking
        // working at all.
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        var decoded = 0
        var inputDone = false
        var spins = 0

        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        val t0 = System.nanoTime()

        while (true) {
            if (limit > 0 && decoded >= limit) break

            if (!inputDone) {
                val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                if (inIdx >= 0) {
                    // Skip forward to the next sync sample.
                    // 🔴 `advance()` is NOT metadata-only: NuMediaExtractor reads
                    // sample DATA on each call (up to 8 samples at a time). That
                    // is why this single-pass strategy measured 62.8 ms/keyframe
                    // against the seek strategy's 32.9 — it drags the whole file
                    // through the extractor to reach 1 sample in 250.
                    // 🔴 REVIEW 2026-09-15: `if (!advance()) break` used to exit
                    // this skip loop with a NON-SYNC sample still current, which
                    // was then queued tagged BUFFER_FLAG_KEY_FRAME; `advance()`
                    // failed again on the next pass and the SAME sample was
                    // re-queued forever. `exhausted` turns that into the
                    // end-of-stream it actually is.
                    var exhausted = false
                    while (extractor.sampleTime >= 0 &&
                        extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC == 0
                    ) {
                        if (!extractor.advance()) { exhausted = true; break }
                    }
                    if (exhausted || extractor.sampleTime < 0) {
                        c.queueInputBuffer(
                            inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM
                        )
                        inputDone = true
                    } else {
                        val buf = c.getInputBuffer(inIdx)!!
                        val size = extractor.readSampleData(buf, 0)
                        if (size < 0) {
                            c.queueInputBuffer(
                                inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM
                            )
                            inputDone = true
                        } else {
                            c.queueInputBuffer(
                                inIdx, 0, size, extractor.sampleTime,
                                MediaCodec.BUFFER_FLAG_KEY_FRAME
                            )
                            extractor.advance()
                        }
                    }
                }
            }

            val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
            when {
                outIdx >= 0 -> {
                    spins = 0
                    val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                    if (info.size > 0) {
                        val kf = imageToKeyframe(c, outIdx, info.presentationTimeUs)
                        decodeNs = System.nanoTime() - t0
                        c.releaseOutputBuffer(outIdx, false)
                        onFrame(kf)
                        decoded++
                    } else {
                        c.releaseOutputBuffer(outIdx, false)
                    }
                    if (eos) break
                }
                outIdx == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED ->
                    Log.i(TAG, "output format changed: ${c.outputFormat}")
                outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                    // 🔴 REVIEW 2026-09-15: the spin budget used to be checked ONLY
                    // once `inputDone`, so a codec holding every input buffer
                    // (dequeueInputBuffer returning -1) while producing no output
                    // span forever at 10 ms a turn, with nothing to break the loop.
                    // decodeKeyframesBySeek already checked unconditionally.
                    if (++spins > MAX_SPINS_BEFORE_EOS && !inputDone) {
                        throw IllegalStateException(
                            "decoder produced no output for $MAX_SPINS_BEFORE_EOS " +
                                "consecutive polls with input still pending ($decoded " +
                                "keyframes so far). Input buffers are all in flight and " +
                                "nothing is coming back — the pipeline is wedged."
                        )
                    }
                    if (inputDone && spins > MAX_SPINS) {
                        throw IllegalStateException(
                            "decoder stalled after end-of-stream with $decoded keyframes " +
                                "decoded and no further output after $MAX_SPINS polls."
                        )
                    }
                }
            }
        }
        // 🔴 decodeNs accumulates the WALL time spent inside this loop up to the
        // last delivered frame. The caller's per-stage GL timings are taken in
        // onFrame(), which runs INSIDE that window, so they are NESTED in
        // decodeNs — it is not a disjoint stage. That is why a naive
        // `decode + upload + resolve + shader + readback` sum EXCEEDS the wall it
        // claims to decompose (measured: stage_total 35.125 vs wall 33.428 on
        // Path Z). WardenEngineBench.timingRun now also emits
        // `decode_excluding_gl` / `gl_total` / `gl_share_of_wall`; quote THOSE.
        // The engine's real share of the wall is ~6% (Path Z) / ~7% (Path P),
        // NOT the ~1% that the nested figures implied.
        return decoded
    }

    private fun profileWidth() = format.getInteger(MediaFormat.KEY_WIDTH)
    private fun profileHeight() = format.getInteger(MediaFormat.KEY_HEIGHT)

    /**
     * Coded frame geometry, from the format rather than from a buffer.
     *
     * Kept for callers that need the geometry before the first frame arrives. The
     * per-frame assertion now lives with the pixels, in
     * [WardenYuvFrame.requireGeometry] — which is the right place for it, because a
     * frame that lies about its size is only detectable where its planes are.
     */
    val frameWidth: Int get() = profileWidth()
    val frameHeight: Int get() = profileHeight()

    /**
     * Path P — copy the three planes out of the codec's Image.
     *
     * The copy is REAL and is exactly what Path P costs relative to Path Z; it is
     * timed inside decodeNs and reported, not hidden.
     */
    private fun imageToKeyframe(c: MediaCodec, outIdx: Int, ptsUs: Long): WardenKeyframe {
        val img = c.getOutputImage(outIdx)
            ?: throw IllegalStateException(
                "getOutputImage returned null — the codec is not in a flexible YUV " +
                    "colour format, so Path P cannot read planes."
            )
        // Path P is now the ONLY colour path, and WardenYuvFrame reads one byte
        // per sample. A 10-bit stream can come back as P010 (two bytes per
        // sample, same three-plane shape) and would be read as 8-bit garbage
        // with no error, so anything but 8-bit 4:2:0 is refused here.
        if (img.format != ImageFormat.YUV_420_888) {
            val fmt = img.format
            img.close()
            throw IllegalStateException(
                "codec output image format is $fmt, not YUV_420_888 " +
                    "(${ImageFormat.YUV_420_888}) — WardenColorConvert reads 8-bit 4:2:0 only."
            )
        }
        // 🔴 STORY 12.4c — THE CROP RECT IS NO LONGER IGNORED (deferred item from
        // the 12.4b review). `img.width/height` can be the CODED geometry, which
        // for a 1080p stream is legitimately 1920x1088 on some codecs: the rules
        // are packed for 1920x1080, so `requireGeometry` would fail on EVERY frame
        // with a message about the config rather than about the buffer. The crop
        // rect is the displayed region, and that is what the zone coordinates mean.
        //
        // A non-zero crop ORIGIN is refused rather than honoured: `bgrAt` indexes
        // planes from 0, so every rule would silently shift by the origin. No
        // capture we have seen does this, which is exactly why it must throw
        // instead of being handled by a translation nothing has ever tested.
        val crop = img.cropRect
        val planes = img.planes
        var w = img.width
        var h = img.height
        if (crop != null && !crop.isEmpty) {
            if (crop.left != 0 || crop.top != 0) {
                img.close()
                throw IllegalStateException(
                    "codec output image has a non-zero crop origin " +
                        "(${crop.left},${crop.top}) ${crop.width()}x${crop.height()} in a " +
                        "${img.width}x${img.height} buffer. Rule rects are absolute at the " +
                        "reference resolution and the planes are indexed from 0, so every " +
                        "rule would be offset by the crop origin — plausible-looking wrong " +
                        "detections rather than an error."
                )
            }
            w = crop.width()
            h = crop.height()
        }
        val out = Array(3) { i ->
            val src = planes[i].buffer
            val copy = ByteBuffer.allocateDirect(src.remaining())
            copy.put(src); copy.position(0)
            copy
        }
        val rowStrides = IntArray(3) { planes[it].rowStride }
        val pixelStrides = IntArray(3) { planes[it].pixelStride }
        img.close()
        return WardenKeyframe(ptsUs, w, h, out, rowStrides, pixelStrides)
    }

    override fun close() {
        try { codec?.stop() } catch (_: Throwable) {}
        codec?.release(); codec = null
        extractor.release()
    }

    companion object {
        /**
         * 🔴 STORY 12.4a AC1 — WAS `10_000L`. DO NOT READ THIS AS "THE TIMEOUT WAS
         * 10.6 ms OF SLEEP PER KEYFRAME" — THAT IS THE TRAP, NOT THE FINDING.
         *
         * The AC was written on a projection about *where* the 10.6 ms went, and the
         * projection was wrong. **MEASURED before and after, median of 3
         * (`bench/12-4a/{baseline,after}_flushprobe_run{1,2,3}.json`):**
         *
         * ```
         * try_again_ms_per_keyframe   10.697 -> 9.772   (-0.9 ms — did NOT move)
         * try_again_count_per_kf        1.03 -> 7.39    (we poll ~7x as often)
         * decode_probe wall           41.982 -> 33.442  (-8.540)
         * queue_to_first_output       21.891 -> 13.389  (-8.502)  <- the real win
         * ```
         *
         * **The named counter barely moved and the fix is good anyway. Both facts
         * matter.** At 1 ms we poll ~7x where we polled ~1x, so time accumulated
         * *inside* try-again calls is ~the decoder's real latency either way.
         *
         * THE MECHANISM IS NOT "POLLING IS SLOW", AND GETTING THIS WRONG SENDS THE
         * NEXT READER AT THE CODEC INSTEAD OF AT THE LOOP. In the EOS-terminated
         * structure the loop queues the IDR, polls output once, gets TRY_AGAIN,
         * and then **sleeps a whole timeout before coming back round to queue the
         * `END_OF_STREAM` the decoder is waiting for** (trap 2: one queued sample
         * decodes to nothing). The sleep does not wait for slow hardware — it
         * WITHHOLDS the input that hardware needs. The −8.5 ms/kf is the blocking
         * `dequeue*` calls getting 10x finer granularity, and it lands in
         * `queue_to_first_output` — exactly where a withheld-EOS effect belongs.
         *
         * ⚠️ SCOPE: this constant is class-wide, but the measurement above is of the
         * EOS-terminated structure only. `decodeKeyframes` (A′) and `decodeProbe`
         * inherit the 10x finer poll without the analysis — on A′, whose own KDoc
         * says it can go a while without output while the extractor skips non-sync
         * samples, that is a 1000 Hz poll doing nothing.
         *
         * 🔴 STORY 12.4b VERDICT (the decision the 2026-09-17 review deferred here):
         * **A′ KEEPS THE SHARED TIMEOUT.** A′ exists for exactly one purpose — to be
         * compared against A on the same frames — and the delivered pair is
         * 32.937 vs 62.820 ms/kf measured with BOTH loops polling identically.
         * Giving A′ its own timeout would make that pair incomparable to any re-run
         * while improving a path nothing ships. The poll is wasteful and it is
         * wasteful EQUALLY, which is what a control is for.
         */
        private const val TIMEOUT_US = 1_000L

        /**
         * Wedge caps, declared in TIME and converted to polls.
         *
         * 🔴 They used to be raw poll counts (`500` / `2000`), which silently
         * derived their real budget from [TIMEOUT_US]: changing the timeout by 10x
         * changed how long a wedged run takes to bail by 10x, turning a 20 s guard
         * into either a 2 s FALSE FAILURE or a 200 s hang. Expressed this way the
         * budget is invariant under a timeout change — 5 s and 20 s before, 5 s and
         * 20 s after.
         *
         * [MAX_SPINS_BEFORE_EOS] stays the generous one because the single-pass
         * strategy ([decodeKeyframes]) can legitimately go a while without output
         * while the extractor skips hundreds of non-sync samples.
         */
        private const val WEDGE_CAP_MS = 5_000L
        private const val WEDGE_CAP_BEFORE_EOS_MS = 20_000L

        /**
         * 🔴 THE CONVERSION IS GUARDED (review 2026-09-17) — BOTH ENDS BITE.
         *
         * `TIMEOUT_US = 0L` is an entirely plausible next tuning step, since this
         * story's whole thesis is that the timeout was a self-inflicted sleep — and
         * unguarded it divides by zero in `<clinit>`, i.e. `ExceptionInInitializerError`
         * on first touch of the CLASS, killing every path in this file rather than
         * one loop. At the other end, `TIMEOUT_US > 5_000_000` makes [MAX_SPINS] `0`
         * so `++spins > 0` fires on the FIRST `INFO_TRY_AGAIN_LATER` — an instant
         * false failure, precisely what the duration framing exists to prevent.
         *
         * ⚠️ AND THE BUDGET IS STILL *ENFORCED* IN POLLS. The "5 s / 20 s" invariant
         * assumes every spin costs a full `TIMEOUT_US`. `dequeueOutputBuffer` may
         * return early, and the non-`TRY_AGAIN` sentinels return immediately (which
         * is why the pipelined drain counts them against [MAX_SPINS] separately).
         * Treat these as ORDER-OF-MAGNITUDE guards, not deadlines.
         */
        private val MAX_SPINS =
            (WEDGE_CAP_MS * 1_000L / maxOf(1L, TIMEOUT_US)).toInt().coerceAtLeast(1)
        private val MAX_SPINS_BEFORE_EOS =
            (WEDGE_CAP_BEFORE_EOS_MS * 1_000L / maxOf(1L, TIMEOUT_US)).toInt().coerceAtLeast(1)

        /**
         * The presentation timestamp stamped on the single end-of-stream input
         * buffer. **It MUST NOT collide with any real sample time**, because
         * outputs are matched to requests by exact PTS equality.
         *
         * 🔴 This was `0L` until the 2026-09-17 review, and keyframe 0's PTS on the
         * reference capture is EXACTLY `0` — see any `*_timing_fires_*.json`, whose
         * first row is `"pts_us": 0`. Nothing failed only because
         * `c2.qti.avc.decoder` reports end-of-stream on a zero-size buffer. A codec
         * that flags EOS on the last data-bearing buffer instead — which MediaCodec
         * permits — would have propagated `0`, failed the in-flight match after
         * keyframe 0 had already been delivered, and killed a bit-perfect run.
         */
        private const val EOS_PTS = Long.MAX_VALUE

        /**
         * AC0a / AC2 — how many keyframes are kept in flight by
         * [decodeKeyframesBySeek], which is what lets the per-keyframe `flush()`
         * go away entirely.
         *
         * MEASURED, not chosen: `pipelineProbe` sweeps k in {1, 2, 4, 8, 16} over
         * the same 100 keyframes in one run. See the Story 12.4a Dev Agent Record
         * and `apps/mobile/bench/12-4a/`.
         *
         * 🔴 IT IS MEASURED ON EXACTLY ONE CODEC, AND THE LOOP HAS NO ESCAPE IF A
         * DEVICE NEEDS MORE (review 2026-09-17; accepted as a documented constraint
         * by Stephane rather than papered over with an untested fallback branch).
         *
         * The end-of-stream that drains the tail is queued only once EVERY sample is
         * in, and the fill loop is capped by `inFlight.size < PIPELINE_DEPTH`. So on
         * a codec whose output latency exceeds k IDRs — or one that simply holds all
         * its input buffers without emitting — fill blocks, EOS never lands, and the
         * run dies at the wedge cap. **This is not hypothetical: `k = 1` WEDGES on
         * the reference device itself**, 3 runs of 3, which is the same mechanism at
         * its smallest. k = 8 was measured on `c2.qti.avc.decoder` (SM7325 /
         * Android 14) and nothing else.
         *
         * **The failure signature, so the next reader recognises it in one line:**
         * ```
         * IllegalStateException: no output for 20000 ms (20000 polls at 1000us)
         *   (decoded=0/1061, queued=8, inFlight=8, eosQueued=false)
         * ```
         * `decoded=0` with `queued == inFlight == PIPELINE_DEPTH` and
         * `eosQueued=false` means the codec wants more in flight than we allow.
         * **Raise this constant and re-run the `flushprobe` sweep** — do not reach
         * for the timeout or the wedge caps, which are not the cause.
         *
         * ⚠️ Also unresolved: the sweep cannot currently tell k = 8 from the codec's
         * own input-buffer count. `dequeueInputBuffer(0L)` `break`s on `-1`, so the
         * effective depth is `min(PIPELINE_DEPTH, available input buffers)`. If this
         * codec exposes 6, then k = 8 and k = 16 were the same run and the flat
         * result is a ceiling, not a knee. `pipelineProbe` now records
         * `max_observed_in_flight` so the next sweep can settle it.
         */
        private const val PIPELINE_DEPTH = 8
    }
}
