package team.warden.mobile

import android.graphics.SurfaceTexture
import android.media.MediaCodec
import android.media.MediaCodecInfo
import android.media.MediaExtractor
import android.media.MediaFormat
import android.os.Handler
import android.os.HandlerThread
import android.util.Log
import android.view.Surface
import java.nio.ByteBuffer

// Story 12.2 AC0b — keyframe-only decode. `-skip_frame nokey` has NO MediaCodec
// equivalent flag; this is the analogue, and it is the largest NEW engineering
// surface in the story (everything else is a port).
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// 🔴 WHAT IS ACTUALLY BOUND — CORRECTED 2026-09-17 BY STORY 12.4a (AC8).
//
// This header used to say A' was "what shipped". **IT IS NOT, AND IT NEVER WAS
// THE FASTER PATH.** architecture.md Decision #13 binds **STRATEGY A**, and the
// two were measured head to head on the same frames:
//
//   A  — **SHIPPED AND BOUND: 32.937 ms/kf.** ABSOLUTE
//        `MediaExtractor.seekTo(pts, SEEK_TO_CLOSEST_SYNC)` per keyframe, over
//        the PTS list built by [syncSamplePtsListBySeek]. Implemented by
//        [decodeKeyframesBySeek]. **This is the function to change.**
//   A' — **RETAINED FOR COMPARISON ONLY: 62.820 ms/kf — the SLOWER path.**
//        A single forward pass over the sample table, queueing only samples
//        flagged SAMPLE_FLAG_SYNC and skipping the rest with `advance()`.
//        Implemented by [decodeKeyframes]. It has no flush and no per-keyframe
//        EOS and is STILL ~2x slower, because `advance()` is NOT free and is NOT
//        metadata-only: `NuMediaExtractor::fetchTrackSamples` reads sample DATA
//        on every advance(), in batches of up to 8, so A' drags the whole 2.3 GB
//        through the extractor to reach one sample in 250. See
//        [countSyncSamplesByScan]. **Do not "simplify" toward A'.**
//   C  — the ffmpeg-kit control (WardenEngineBench), running 12.1's LITERAL
//        `-skip_frame nokey` on device for a directly comparable decode number.
//   B  — full decode + BUFFER_FLAG_KEY_FRAME filtering was NOT taken: it decodes
//        everything, which is the `select='eq(pict_type,I)'` mistake 12.1
//        measured at 5.4x slower on PC for zero decode saving.
//
// Carry **32.937 / 62.820**, NOT the 33.68 / 116.45 pair that was corrected
// during 12.2's delivery.
//
// A SEPARATE, NARROWER CLAIM THAT REMAINS TRUE: the *incremental* seek pattern
// `seekTo(lastPts + 1, SEEK_TO_NEXT_SYNC)` in a loop IS broken on this device —
// MEASURED at 2 sync samples against a ground truth of 1061
// (`device_seektest.json` -> `ac0b_prescribed_incremental_scan`). Absolute
// `SEEK_TO_CLOSEST_SYNC` is fine. Seeking is not broken; that ONE pattern is.
//
// 🔴 THE COUNT ASSERTION EARNED ITS KEEP. The decoded keyframe count is asserted
// against a ground-truth sample-table scan (NOT against the seek scan, which is
// the thing that was wrong). Had the loop trusted the seek scan, the bench would
// have reported a perfectly self-consistent `2 == 2` and a beautiful
// ms/keyframe figure computed over two frames. 12.1's analogue caught a
// CFR-duplication regression the same way.

private const val TAG = "WardenDecoder"

/** One decoded keyframe's payload, in whichever form the colour path needs. */
class WardenKeyframe(
    val presentationTimeUs: Long,
    val width: Int,
    val height: Int,
    /** Path P only: Y/U/V planes + their strides. Null on the Surface path. */
    val planes: Array<ByteBuffer>? = null,
    val rowStrides: IntArray? = null,
    val pixelStrides: IntArray? = null,
)

data class WardenDecoderProfile(
    val codecName: String,
    val isHardwareAccelerated: Boolean,
    val mime: String,
    val width: Int,
    val height: Int,
    val durationUs: Long,
    val syncSampleCount: Int,
    val supportedColorFormats: List<Int>,
)

class WardenKeyframeDecoder(
    private val path: String,
    private val toSurface: Surface?,
) : AutoCloseable {

    private val extractor = MediaExtractor()
    private var codec: MediaCodec? = null
    private var trackIndex = -1
    private lateinit var format: MediaFormat

    var profile: WardenDecoderProfile? = null
        private set

    /** Accumulated nanoseconds spent inside decode, for the AC11 stage split. */
    var decodeNs: Long = 0
        private set

    init {
        extractor.setDataSource(path)
        for (i in 0 until extractor.trackCount) {
            val f = extractor.getTrackFormat(i)
            if (f.getString(MediaFormat.KEY_MIME)?.startsWith("video/") == true) {
                trackIndex = i
                format = f
                break
            }
        }
        require(trackIndex >= 0) { "no video track in $path" }
        extractor.selectTrack(trackIndex)
    }

    /**
     * AC0b's binding assertion + AC1's decoder profile.
     *
     * Walks the sync-sample index WITHOUT decoding anything, which is both the
     * ground truth for the keyframe count and the PTS list the decode loop
     * consumes.
     *
     * 🔴 REVIEW 2026-09-15: that walk is a **62 s full-file read**, not an index
     * scan (see [countSyncSamplesByScan]). It used to run unconditionally, so an
     * `all` run paid it TWICE — once here via `deviceProfile`, once in the timing
     * block — and only the second was timed and reported, silently under-reporting
     * ~62 s of a run whose headline deliverable is 35 s. Callers that already hold
     * the ground truth now pass it in via [knownSyncCount]; callers that want the
     * profile WITHOUT the scan pass [scanSyncSamples] = false.
     *
     * 🔴 STORY 12.4a AC3 — [scanSyncSamples] DEFAULTS TO `false` AS OF 2026-09-17.
     * It used to default to `true`, so the 62 s walk was what you got unless you
     * knew to ask for anything else. Today nothing in production reaches it only
     * because [WardenDetectionEngineModule.describeDevice] happens to pass a null
     * video path — that is a coincidence, not a guarantee, and Story 12.4c wires a
     * real path in. Opting IN is now the only way to pay 62 s.
     *
     * @param scanSyncSamples run the 62 s ground-truth walk. **BENCH ONLY.** When
     *   false, [WardenDecoderProfile.syncSampleCount] carries [knownSyncCount]
     *   verbatim.
     * @param knownSyncCount a previously measured ground truth, or -1 for unknown.
     */
    fun probe(
        scanSyncSamples: Boolean = false,
        knownSyncCount: Int = -1,
    ): WardenDecoderProfile {
        val syncCount = if (scanSyncSamples) countSyncSamplesByScan() else knownSyncCount
        val mime = format.getString(MediaFormat.KEY_MIME)!!
        val codecName: String
        val hw: Boolean
        val colorFormats: List<Int>
        // Instantiating the codec is the only way to learn its NAME and whether
        // it is hardware-accelerated; MediaCodecList's "preferred" answer can
        // differ from what createDecoderByType actually hands back.
        val probeCodec = MediaCodec.createDecoderByType(mime)
        try {
            codecName = probeCodec.name
            val info: MediaCodecInfo = probeCodec.codecInfo
            hw = if (android.os.Build.VERSION.SDK_INT >= 29) info.isHardwareAccelerated else
                // Pre-29 heuristic: AOSP software decoders carry these prefixes.
                !(codecName.startsWith("OMX.google.") || codecName.startsWith("c2.android."))
            colorFormats = info.getCapabilitiesForType(mime).colorFormats.toList()
        } finally {
            probeCodec.release()
        }
        val p = WardenDecoderProfile(
            codecName = codecName,
            isHardwareAccelerated = hw,
            mime = mime,
            width = format.getInteger(MediaFormat.KEY_WIDTH),
            height = format.getInteger(MediaFormat.KEY_HEIGHT),
            durationUs = if (format.containsKey(MediaFormat.KEY_DURATION))
                format.getLong(MediaFormat.KEY_DURATION) else -1L,
            syncSampleCount = syncCount,
            supportedColorFormats = colorFormats,
        )
        profile = p
        Log.i(TAG, "decoder=$codecName hw=$hw sync samples=$syncCount")
        return p
    }

    /**
     * 🔴 Ground-truth sync-sample count, by walking the sample table.
     *
     * The seek-based scan AC0b Option A prescribes — `seekTo(t + 1,
     * SEEK_TO_NEXT_SYNC)` in a loop — is NOT reliable on this file/device.
     * MEASURED: it terminates after **2** sync samples on the 2.3 GB / 4419 s
     * capture, against an ffprobe ground truth of **1061** at a dead-regular
     * 4.1667 s GOP. `MediaExtractor.seekTo` simply stops advancing past the
     * second sync point here.
     *
     * That is precisely why AC0b made the count assertion binding rather than
     * decorative: had the decode loop trusted the seek scan, the bench would have
     * reported a perfectly self-consistent `2 == 2` and a beautiful ms/keyframe
     * figure computed over two frames.
     *
     * 🔴 CORRECTED 2026-09-15 — THIS WALK IS **NOT** CHEAP AND **NOT**
     * METADATA-ONLY. An earlier version of this comment claimed `advance()`
     * merely parses the sample table. That is false:
     * `NuMediaExtractor::fetchTrackSamples` READS SAMPLE DATA on every
     * `advance()` as well as on every `seekTo`, in batches of up to
     * `mMaxFetchCount = 8` for video tracks. So this walk pulls the whole 2.3 GB
     * through the extractor.
     *
     * MEASURED COST: **62 s**. It is a bench-time correctness assertion and
     * **MUST NEVER RUN IN PRODUCTION** — it alone would cost nearly twice the
     * entire 35 s analysis. Story 12.4 must take the keyframe index from
     * [syncSamplePtsListBySeek] (2.3 s) or from a direct `stss` read, never from
     * here.
     */
    // 🔴🔴 BENCH-ONLY GROUND TRUTH. 62 SECONDS. NEVER CALL THIS FROM A SHIPPING
    // PATH — Story 12.4a AC3, architecture.md Decision #13. It is reachable from
    // `all` / `timing` / `seektest` in WardenEngineBench and from NOWHERE ELSE;
    // [probe] will not run it unless you explicitly pass scanSyncSamples = true.
    // The production keyframe index is [syncSamplePtsListBySeek] (2.290 s).
    fun countSyncSamplesByScan(): Int {
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        var n = 0
        while (extractor.sampleTime >= 0) {
            if (extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC != 0) n++
            if (!extractor.advance()) break
        }
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        return n
    }

    /**
     * DIAGNOSTIC — does `seekTo` work when given ABSOLUTE targets?
     *
     * The incremental form (`seekTo(lastPts + 1, SEEK_TO_NEXT_SYNC)`) stops
     * advancing after the second sync sample on this file. Before accepting the
     * much more expensive single-pass demux as the only option, this checks
     * whether seeking is broken outright or only in that incremental pattern —
     * the difference is worth ~an order of magnitude on the headline decode
     * number, so it is worth one experiment rather than an assumption.
     */
    fun seekProbe(gopUs: Long, n: Int): List<Long> {
        val out = ArrayList<Long>(n)
        for (k in 0 until n) {
            extractor.seekTo(k * gopUs, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            out.add(extractor.sampleTime)
        }
        return out
    }

    /**
     * 🔴 AC0b OPTION A **EXACTLY AS THE STORY PRESCRIBES IT**, so the amendment
     * that rejected it finally has evidence.
     *
     * Story 12.2 amended AC0b on the claim that the incremental scan —
     * `seekTo(lastPts + 1, SEEK_TO_NEXT_SYNC)` in a loop — "stops advancing after
     * the second sync sample, reporting 2 keyframes against a ground truth of
     * 1061". That claim drove the shipped decode strategy and is inherited by
     * Story 12.4, and it had **no archived artifact**: `keyframe-decode-perf-
     * research.md` records it as *"Non résolu"*, and [seekProbe] — the mode
     * REPORT.md §10 advertised as covering this — measures ABSOLUTE
     * `SEEK_TO_CLOSEST_SYNC` seeks, i.e. the strategy that works, not the one
     * under dispute. Archiving that would have looked like evidence and been none.
     *
     * This runs the disputed pattern and nothing else. Whatever it returns is the
     * answer: a short list vindicates the amendment, a full one means AC0b Option
     * A was fine and the shipped strategy was chosen on a misdiagnosis. Both are
     * worth knowing before 12.4 inherits the decision.
     *
     * @param maxSteps hard cap so a pathological file cannot hang the probe.
     */
    fun incrementalNextSyncScan(maxSteps: Int = 4000): List<Long> {
        val out = ArrayList<Long>()
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_NEXT_SYNC)
        var last = -1L
        var steps = 0
        while (steps++ < maxSteps) {
            val t = extractor.sampleTime
            // The AC's own termination rule: "verify the seek loop terminates
            // (advance past the returned sampleTime)".
            if (t < 0 || t <= last) break
            out.add(t)
            last = t
            extractor.seekTo(last + 1, MediaExtractor.SEEK_TO_NEXT_SYNC)
        }
        return out
    }

    /**
     * DIAGNOSTIC (§6 of the keyframe-decode-perf research) — where do the 33 ms go?
     *
     * The research derives, WITHOUT instrumentation, that ~25.7 ms of the 32.9 ms
     * seek-strategy cost is `flush()` + the `END_OF_STREAM` drain + pipeline
     * restart, and only ~4.3 ms is actual decoding. That derivation rests on
     * `250 x 0.234 ms` of demux in strategy A-prime, which in turn rests on the
     * 62.1 s full sample-table walk. It is arithmetic on two measurements, not a
     * measurement — so it is falsifiable, and this falsifies or confirms it
     * before a single line of the decode loop is rewritten.
     *
     * Runs the CURRENT strategy-A loop unchanged in structure, timing each stage
     * separately. The prediction under test: **flush alone lands in 15-25 ms.**
     * If it does not, the decomposition is wrong and the rewrite is unjustified.
     */
    fun decodeProbe(ptsList: LongArray, n: Int): Map<String, Any> {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()

        val seekNs = ArrayList<Long>(n)
        val flushNs = ArrayList<Long>(n)
        val queueToOutNs = ArrayList<Long>(n)
        var tryAgainCount = 0L
        var tryAgainNs = 0L
        var decoded = 0

        val readBefore = procSelfIoReadBytes()
        val target = minOf(n, ptsList.size)
        val wall0 = System.nanoTime()

        for (idx in 0 until target) {
            val pts = ptsList[idx]

            var t = System.nanoTime()
            extractor.seekTo(pts, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            seekNs.add(System.nanoTime() - t)

            // (1) flush() ALONE — the headline number this probe exists for.
            t = System.nanoTime()
            c.flush()
            flushNs.add(System.nanoTime() - t)

            var sampleQueued = false
            var eosQueued = false
            var got = false
            var spins = 0
            var queuedAt = 0L

            while (!got) {
                if (!eosQueued) {
                    val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                    if (inIdx >= 0) {
                        if (!sampleQueued) {
                            val buf = c.getInputBuffer(inIdx)!!
                            val size = extractor.readSampleData(buf, 0)
                            if (size < 0) {
                                c.queueInputBuffer(inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                                eosQueued = true
                            } else {
                                // (2) clock starts when the IDR enters the codec.
                                queuedAt = System.nanoTime()
                                c.queueInputBuffer(
                                    inIdx, 0, size, extractor.sampleTime,
                                    MediaCodec.BUFFER_FLAG_KEY_FRAME
                                )
                                sampleQueued = true
                            }
                        } else {
                            c.queueInputBuffer(inIdx, 0, 0, pts, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                            eosQueued = true
                        }
                    }
                }
                // (3) every INFO_TRY_AGAIN_LATER is a potential TIMEOUT_US-long sleep.
                val t2 = System.nanoTime()
                val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
                when {
                    outIdx >= 0 -> {
                        val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                        if (info.size > 0 || (toSurface != null && !eos)) {
                            if (queuedAt != 0L) queueToOutNs.add(System.nanoTime() - queuedAt)
                            c.releaseOutputBuffer(outIdx, false)
                            decoded++
                            got = true
                        } else {
                            c.releaseOutputBuffer(outIdx, false)
                            if (eos) got = true
                        }
                    }
                    outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                        tryAgainCount++
                        tryAgainNs += System.nanoTime() - t2
                        if (++spins > MAX_SPINS) throw IllegalStateException("probe stalled at $idx")
                    }
                }
            }
        }
        val wallNs = System.nanoTime() - wall0
        val readAfter = procSelfIoReadBytes()

        fun med(v: List<Long>): Double {
            if (v.isEmpty()) return 0.0
            val s = v.sorted(); val m = s.size / 2
            return (if (s.size % 2 == 1) s[m].toDouble() else (s[m - 1] + s[m]) / 2.0) / 1e6
        }
        fun mean(v: List<Long>) = if (v.isEmpty()) 0.0 else v.sum() / 1e6 / v.size

        return linkedMapOf(
            "keyframes" to decoded,
            "wall_ms_per_keyframe" to wallNs / 1e6 / maxOf(1, decoded),
            "seek_ms_median" to med(seekNs),
            "seek_ms_mean" to mean(seekNs),
            "flush_ms_median" to med(flushNs),
            "flush_ms_mean" to mean(flushNs),
            "flush_ms_max" to (flushNs.maxOrNull() ?: 0L) / 1e6,
            "queue_to_first_output_ms_median" to med(queueToOutNs),
            "queue_to_first_output_ms_mean" to mean(queueToOutNs),
            "try_again_count_total" to tryAgainCount,
            "try_again_per_keyframe" to tryAgainCount.toDouble() / maxOf(1, decoded),
            "try_again_ms_total" to tryAgainNs / 1e6,
            "try_again_ms_per_keyframe" to tryAgainNs / 1e6 / maxOf(1, decoded),
            "timeout_us_used" to TIMEOUT_US,
            "read_bytes_delta" to (readAfter - readBefore),
            "read_mb_per_keyframe" to (readAfter - readBefore) / 1048576.0 / maxOf(1, decoded),
            "prediction_under_test" to
                "research §2 derives flush+drain ~= 25.7 ms/kf and real decode ~= 4.3 ms. " +
                "If flush_ms_median is NOT in 15-25 ms, the decomposition is refuted.",
        )
    }

    /**
     * `flush()` back-to-back on an otherwise idle codec, for contrast with the
     * in-loop figure. If the in-loop flush is expensive but the idle flush is
     * cheap, the cost is draining in-flight work rather than the HFI round trip
     * itself — a different fix.
     */
    fun flushOnlyProbe(reps: Int): Map<String, Any> {
        configureCodec()
        val c = codec!!
        val ns = ArrayList<Long>(reps)
        for (i in 0 until reps) {
            val t = System.nanoTime()
            c.flush()
            ns.add(System.nanoTime() - t)
        }
        val s = ns.sorted()
        return linkedMapOf(
            "reps" to reps,
            "idle_flush_ms_median" to s[s.size / 2] / 1e6,
            "idle_flush_ms_mean" to ns.sum() / 1e6 / ns.size,
            "idle_flush_ms_max" to s.last() / 1e6,
        )
    }

    /** Bytes this process has actually read from storage. -1 if unreadable. */
    private fun procSelfIoReadBytes(): Long = try {
        java.io.File("/proc/self/io").readLines()
            .firstOrNull { it.startsWith("read_bytes:") }
            ?.substringAfter(':')?.trim()?.toLong() ?: -1L
    } catch (t: Throwable) { -1L }

    /**
     * The keyframe PTS list, built with ABSOLUTE `SEEK_TO_CLOSEST_SYNC` seeks.
     *
     * MEASURED on this device: `SEEK_TO_CLOSEST_SYNC` with an absolute target is
     * correct and costs ~2.9 ms, while the incremental
     * `SEEK_TO_NEXT_SYNC(lastPts + 1)` pattern stops advancing after the second
     * sync sample. So seeking is not broken — that ONE pattern is.
     *
     * The GOP is estimated from the first two keyframes and then stepped. Any
     * step that fails to advance is treated as the end of a REGULAR GOP
     * assumption, not as the end of the file: the caller still asserts the
     * resulting count against the ground-truth sample-table scan, so an irregular
     * GOP shows up as a mismatch rather than as silently-missing keyframes.
     */
    fun syncSamplePtsListBySeek(maxCount: Int = 100_000): LongArray {
        extractor.seekTo(0L, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
        val first = extractor.sampleTime
        if (first < 0) return LongArray(0)
        // Probe the second keyframe to learn the GOP rather than assuming one.
        var gop = -1L
        var probe = 100_000L
        while (probe < 60_000_000L) {
            extractor.seekTo(first + probe, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            val t = extractor.sampleTime
            if (t > first) { gop = t - first; break }
            probe *= 2
        }
        if (gop <= 0) return longArrayOf(first)

        val out = ArrayList<Long>()
        out.add(first)
        var last = first
        var k = 1L
        while (out.size < maxCount) {
            // Seek to the MIDPOINT past the last keyframe: CLOSEST_SYNC then
            // resolves to the next one even if the GOP drifts by up to half a
            // period, which a naive exact-multiple step would not tolerate.
            extractor.seekTo(first + k * gop, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
            val t = extractor.sampleTime
            if (t < 0 || t <= last) break
            out.add(t)
            last = t
            k++
        }
        return out.toLongArray()
    }

    /**
     * STRATEGY A — decode by SEEKING to each keyframe. **THE BOUND PATH**
     * (architecture.md Decision #13, 32.937 ms/kf against A-prime's 62.820).
     *
     * 🔴 RESTRUCTURED 2026-09-17 BY STORY 12.4a (AC2). It used to be, per keyframe:
     * `seekTo` -> `flush()` -> queue sample -> queue `END_OF_STREAM` -> drain.
     * **`flush()` alone was MEASURED at 14.11 ms/kf in that loop against 3.59 ms on
     * an idle codec** (`device_probe_flush.json` + `idle_flush_probe`, 100 kf x 3),
     * so the cost was the `END_OF_STREAM` -> flush state transition, not the HFI
     * round trip — i.e. it was ours, and it was ~34% of a 42.2 ms wall.
     *
     * It is now PIPELINED: [PIPELINE_DEPTH] keyframes are kept in flight, and no
     * `flush()` happens at all. An IDR resets the DPB **by definition**, and every
     * sample here is reached by an absolute `SEEK_TO_CLOSEST_SYNC` and verified
     * `SAMPLE_FLAG_SYNC`, so each is self-contained and needs no reset between it
     * and the next.
     *
     * 🔴 OUTPUTS ARE MATCHED TO REQUESTS BY PTS, NEVER BY ARRIVAL ORDER. That is
     * not defensive styling — it is the one failure mode pipelining introduces
     * (Story 12.4a AC5), and the in-flight set turns "the decoder handed back a
     * frame we never asked for, or handed the same one twice" from a silent
     * pixel-level parity drift into an exception at the point of the defect.
     *
     * 🔴 THE TAIL STILL NEEDS ONE `END_OF_STREAM` — ONCE PER RUN, NOT PER KEYFRAME.
     * Trap 2 has not gone away: a hardware decoder holds frames for reorder, so the
     * last few keyframes do not come out on their own. Removing the flush does not
     * remove that; it removes paying for it 1061 times.
     *
     * 🔴 THE SURFACE PATH (Path Z) DELIBERATELY KEEPS THE OLD LOOP — see
     * [decodeKeyframesBySeekSurfaceLegacy]. Not caution: [WardenSurfaceTextureHost]
     * consumes ONE posted frame at a time and already treats `pendingFrames > 1` as
     * an anomaly, so k frames in flight would coalesce in the `SurfaceTexture` and
     * mis-bind. Path Z is not bound (it exists only to feed the rejected shader) and
     * **Story 12.4b deletes it**, taking this branch with it.
     */
    fun decodeKeyframesBySeek(
        ptsList: LongArray,
        limit: Int = 0,
        onFrame: (WardenKeyframe) -> Unit,
    ): Int {
        val target = if (limit > 0) minOf(limit, ptsList.size) else ptsList.size
        if (target == 0) return 0
        return if (toSurface != null) {
            decodeKeyframesBySeekSurfaceLegacy(ptsList, target, onFrame)
        } else {
            decodeKeyframesBySeekPipelined(ptsList, target, onFrame)
        }
    }

    /**
     * Seek to [pts], and prove the extractor actually got there.
     *
     * 🔴 REVIEW 2026-09-15, PRESERVED THROUGH THE 12.4a RESTRUCTURE. The loop used
     * to queue whatever `extractor.sampleTime` happened to be and increment
     * `decoded`. If the seek landed on a different sync sample — or on the SAME one
     * as the previous iteration — the same frame was decoded N times and counted as
     * N distinct keyframes, inflating the divisor of every ms_per_keyframe figure
     * while the per-rule fire rows silently repeated under different `pts_us` keys.
     * `keyframe_count_matches` could never catch it, because a repeated landing
     * still increments `decoded` toward `syncCount`.
     */
    private fun seekToVerifiedSyncSample(idx: Int, pts: Long) {
        extractor.seekTo(pts, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
        val landed = extractor.sampleTime
        if (landed != pts) {
            throw IllegalStateException(
                "keyframe $idx: seekTo($pts, SEEK_TO_CLOSEST_SYNC) landed on " +
                    "sampleTime=$landed. The decode loop consumes a PTS list built " +
                    "by syncSamplePtsListBySeek, so a mismatch means the extractor " +
                    "is not addressing the sync sample that list names — every " +
                    "downstream per-keyframe figure would be computed over the " +
                    "wrong set of frames."
            )
        }
        if ((extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC) == 0) {
            throw IllegalStateException(
                "keyframe $idx (pts=$pts): the sample the extractor landed on is " +
                    "NOT flagged SAMPLE_FLAG_SYNC. Decoding a non-sync sample in " +
                    "isolation is undefined — it would reference frames the decoder " +
                    "never saw."
            )
        }
    }

    /** AC2 — the flush-free pipelined loop. Path P only. */
    private fun decodeKeyframesBySeekPipelined(
        ptsList: LongArray,
        target: Int,
        onFrame: (WardenKeyframe) -> Unit,
    ): Int {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        val t0 = System.nanoTime()

        // Queued into the codec but not yet delivered. The MATCHING SET for AC5.
        val inFlight = HashSet<Long>()
        var nextToQueue = 0
        var decoded = 0
        var eosQueued = false
        var spins = 0

        while (decoded < target) {
            // (1) Top the pipeline up. Non-blocking: if the codec is holding every
            //     input buffer, that is not an error, it is backpressure — fall
            //     through and drain instead of waiting for a buffer.
            while (nextToQueue < target && inFlight.size < PIPELINE_DEPTH) {
                val inIdx = c.dequeueInputBuffer(0L)
                if (inIdx < 0) break
                val pts = ptsList[nextToQueue]
                seekToVerifiedSyncSample(nextToQueue, pts)
                val buf = c.getInputBuffer(inIdx)!!
                val size = extractor.readSampleData(buf, 0)
                if (size < 0) {
                    throw IllegalStateException(
                        "keyframe $nextToQueue (pts=$pts): readSampleData returned $size " +
                            "after a VERIFIED landing on that sync sample — the extractor " +
                            "has a sample time but no sample data."
                    )
                }
                c.queueInputBuffer(inIdx, 0, size, pts, MediaCodec.BUFFER_FLAG_KEY_FRAME)
                inFlight.add(pts)
                nextToQueue++
            }

            // (2) Every sample is in. ONE end-of-stream drains the reorder buffer —
            //     the whole saving is that this happens here and not 1061 times.
            if (!eosQueued && nextToQueue >= target) {
                val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                if (inIdx >= 0) {
                    c.queueInputBuffer(inIdx, 0, 0, 0L, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                    eosQueued = true
                }
            }

            // (3) Drain.
            val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
            when {
                outIdx >= 0 -> {
                    val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                    if (info.size > 0) {
                        val pts = info.presentationTimeUs
                        if (!inFlight.remove(pts)) {
                            throw IllegalStateException(
                                "the decoder returned a frame with pts=$pts that is not in " +
                                    "flight. Either it was already delivered (a duplicate) or " +
                                    "it was never queued. Outputs are matched to requests BY " +
                                    "PTS precisely so this surfaces here instead of as a " +
                                    "parity drift 2666 frames later."
                            )
                        }
                        val kf = imageToKeyframe(c, outIdx, pts)
                        decodeNs = System.nanoTime() - t0
                        c.releaseOutputBuffer(outIdx, false)
                        onFrame(kf)
                        decoded++
                        spins = 0
                    } else {
                        c.releaseOutputBuffer(outIdx, false)
                        if (eos && decoded < target) {
                            throw IllegalStateException(
                                "END_OF_STREAM after $decoded of $target keyframes, with " +
                                    "${inFlight.size} still in flight. The decoder dropped " +
                                    "queued IDRs rather than decoding them."
                            )
                        }
                    }
                }
                outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                    val cap = if (eosQueued) MAX_SPINS else MAX_SPINS_BEFORE_EOS
                    if (++spins > cap) {
                        throw IllegalStateException(
                            "no output after $cap polls at ${TIMEOUT_US}us " +
                                "(decoded=$decoded/$target, queued=$nextToQueue, " +
                                "inFlight=${inFlight.size}, eosQueued=$eosQueued)"
                        )
                    }
                }
            }
        }
        // 🔴 Same nesting caveat as decodeKeyframes: decodeNs is assigned from t0
        // (loop entry) and snapshotted BEFORE onFrame(), so every downstream stage
        // of frames 0..N-2 is inside it. Use timingRun's `decode_excluding_gl` /
        // `gl_total` for a disjoint split.
        return decoded
    }

    /**
     * The PRE-12.4a loop — seek, `flush()`, queue, `END_OF_STREAM`, drain, per
     * keyframe. **Retained ONLY for the Surface path**, whose one-frame-at-a-time
     * consumer cannot take a pipeline (see [decodeKeyframesBySeek]). Path Z is not
     * bound and Story 12.4b removes it; this goes with it.
     */
    private fun decodeKeyframesBySeekSurfaceLegacy(
        ptsList: LongArray,
        target: Int,
        onFrame: (WardenKeyframe) -> Unit,
    ): Int {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        var decoded = 0
        val t0 = System.nanoTime()

        for (idx in 0 until target) {
            val pts = ptsList[idx]
            seekToVerifiedSyncSample(idx, pts)
            c.flush()
            // NB: no start() after flush() — see decodeKeyframes.
            var sampleQueued = false
            var eosQueued = false
            var got = false
            var spins = 0
            while (!got) {
                if (!eosQueued) {
                    val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                    if (inIdx >= 0) {
                        if (!sampleQueued) {
                            val buf = c.getInputBuffer(inIdx)!!
                            val size = extractor.readSampleData(buf, 0)
                            if (size < 0) {
                                c.queueInputBuffer(inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                                eosQueued = true
                            } else {
                                c.queueInputBuffer(
                                    inIdx, 0, size, extractor.sampleTime,
                                    MediaCodec.BUFFER_FLAG_KEY_FRAME
                                )
                                sampleQueued = true
                            }
                        } else {
                            c.queueInputBuffer(inIdx, 0, 0, pts, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                            eosQueued = true
                        }
                    }
                }
                val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
                when {
                    outIdx >= 0 -> {
                        val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                        if (info.size > 0 || !eos) {
                            val kf = WardenKeyframe(info.presentationTimeUs, profileWidth(), profileHeight())
                            decodeNs = System.nanoTime() - t0
                            c.releaseOutputBuffer(outIdx, true)
                            onFrame(kf)
                            decoded++
                            got = true
                        } else {
                            c.releaseOutputBuffer(outIdx, false)
                            throw IllegalStateException(
                                "keyframe $idx (pts=$pts) drained to END_OF_STREAM with no " +
                                    "decoded frame — that sync point did not decode standalone."
                            )
                        }
                    }
                    outIdx == MediaCodec.INFO_TRY_AGAIN_LATER ->
                        if (++spins > MAX_SPINS) throw IllegalStateException(
                            "no output for keyframe $idx (pts=$pts) after $MAX_SPINS polls"
                        )
                }
            }
        }
        return decoded
    }

    /**
     * AC0a — the *k* sweep, so [PIPELINE_DEPTH] is MEASURED rather than picked.
     *
     * Runs the pipelined structure at a given depth over the same keyframes the
     * [decodeProbe] baseline used, releasing outputs without copying planes so the
     * two walls are comparable. `depth = 1` is the degenerate case and is included
     * on purpose: it is the same loop with no pipelining, so it separates "removing
     * the flush helped" from "keeping k frames in flight helped".
     */
    fun pipelineProbe(ptsList: LongArray, n: Int, depth: Int): Map<String, Any> {
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        val target = minOf(n, ptsList.size)

        val inFlight = HashSet<Long>()
        var nextToQueue = 0
        var decoded = 0
        var eosQueued = false
        var spins = 0
        var tryAgainCount = 0L
        var tryAgainNs = 0L
        var seekNs = 0L
        var mismatches = 0

        val readBefore = procSelfIoReadBytes()
        val wall0 = System.nanoTime()
        while (decoded < target) {
            while (nextToQueue < target && inFlight.size < depth) {
                val inIdx = c.dequeueInputBuffer(0L)
                if (inIdx < 0) break
                val pts = ptsList[nextToQueue]
                val ts = System.nanoTime()
                seekToVerifiedSyncSample(nextToQueue, pts)
                seekNs += System.nanoTime() - ts
                val buf = c.getInputBuffer(inIdx)!!
                val size = extractor.readSampleData(buf, 0)
                if (size < 0) throw IllegalStateException("no sample data at pts=$pts")
                c.queueInputBuffer(inIdx, 0, size, pts, MediaCodec.BUFFER_FLAG_KEY_FRAME)
                inFlight.add(pts)
                nextToQueue++
            }
            if (!eosQueued && nextToQueue >= target) {
                val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                if (inIdx >= 0) {
                    c.queueInputBuffer(inIdx, 0, 0, 0L, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                    eosQueued = true
                }
            }
            val t2 = System.nanoTime()
            val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
            when {
                outIdx >= 0 -> {
                    val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                    if (info.size > 0) {
                        if (!inFlight.remove(info.presentationTimeUs)) mismatches++
                        c.releaseOutputBuffer(outIdx, false)
                        decoded++
                        spins = 0
                    } else {
                        c.releaseOutputBuffer(outIdx, false)
                        if (eos && decoded < target) break
                    }
                }
                outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                    tryAgainCount++
                    tryAgainNs += System.nanoTime() - t2
                    val cap = if (eosQueued) MAX_SPINS else MAX_SPINS_BEFORE_EOS
                    if (++spins > cap) throw IllegalStateException("pipelineProbe wedged at depth=$depth")
                }
            }
        }
        val wallNs = System.nanoTime() - wall0
        val readAfter = procSelfIoReadBytes()
        return linkedMapOf(
            "pipeline_depth" to depth,
            "keyframes_requested" to target,
            "keyframes_decoded" to decoded,
            "all_decoded" to (decoded == target),
            "pts_mismatches" to mismatches,
            "wall_ms_per_keyframe" to wallNs / 1e6 / maxOf(1, decoded),
            "wall_ms_total" to wallNs / 1e6,
            "seek_ms_per_keyframe" to seekNs / 1e6 / maxOf(1, decoded),
            "try_again_count_total" to tryAgainCount,
            "try_again_per_keyframe" to tryAgainCount.toDouble() / maxOf(1, decoded),
            "try_again_ms_per_keyframe" to tryAgainNs / 1e6 / maxOf(1, decoded),
            "flush_calls" to 0,
            "timeout_us_used" to TIMEOUT_US,
            "read_mb_per_keyframe" to (readAfter - readBefore) / 1048576.0 / maxOf(1, decoded),
        )
    }

    private fun configureCodec() {
        val mime = format.getString(MediaFormat.KEY_MIME)!!
        val c = MediaCodec.createDecoderByType(mime)
        if (toSurface == null) {
            // Path P — flexible YUV 4:2:0 so getOutputImage() hands back planes
            // with device-reported strides. NEVER assume rowStride == width.
            format.setInteger(
                MediaFormat.KEY_COLOR_FORMAT,
                MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible
            )
        }
        c.configure(format, toSurface, null, 0)
        c.start()
        codec = c
    }

    /**
     * Decode every keyframe, invoking [onFrame] for each.
     *
     * Returns the number of keyframes decoded. The caller asserts it against
     * [WardenDecoderProfile.syncSampleCount].
     *
     * @param limit stop after this many keyframes (0 = all). Used for warm-up
     *   runs and for the AC3 single-frame diff.
     */
    fun decodeKeyframes(limit: Int = 0, onFrame: (WardenKeyframe) -> Unit): Int {
        // SINGLE FORWARD PASS, sync-filtered — the true `-skip_frame nokey`
        // analogue, and a closer one than the seek loop it replaces.
        //
        // FFmpeg's `-skip_frame nokey` does NOT seek: it demuxes every packet and
        // instructs the decoder to skip non-keyframes. This does exactly that —
        // `advance()` walks past non-sync samples without decoding them, and only
        // sync samples are queued. Consecutive IDR frames decode back-to-back
        // with no flush, so the per-keyframe seek + flush + END_OF_STREAM
        // round-trip disappears entirely.
        //
        // It also sidesteps the measured `seekTo` defect (see
        // countSyncSamplesByScan): correctness here does not depend on seeking
        // working at all.
        configureCodec()
        val c = codec!!
        val info = MediaCodec.BufferInfo()
        var decoded = 0
        var inputDone = false
        var spins = 0

        extractor.seekTo(0L, MediaExtractor.SEEK_TO_PREVIOUS_SYNC)
        val t0 = System.nanoTime()

        while (true) {
            if (limit > 0 && decoded >= limit) break

            if (!inputDone) {
                val inIdx = c.dequeueInputBuffer(TIMEOUT_US)
                if (inIdx >= 0) {
                    // Skip forward to the next sync sample.
                    // 🔴 `advance()` is NOT metadata-only: NuMediaExtractor reads
                    // sample DATA on each call (up to 8 samples at a time). That
                    // is why this single-pass strategy measured 62.8 ms/keyframe
                    // against the seek strategy's 32.9 — it drags the whole file
                    // through the extractor to reach 1 sample in 250.
                    // 🔴 REVIEW 2026-09-15: `if (!advance()) break` used to exit
                    // this skip loop with a NON-SYNC sample still current, which
                    // was then queued tagged BUFFER_FLAG_KEY_FRAME; `advance()`
                    // failed again on the next pass and the SAME sample was
                    // re-queued forever. `exhausted` turns that into the
                    // end-of-stream it actually is.
                    var exhausted = false
                    while (extractor.sampleTime >= 0 &&
                        extractor.sampleFlags and MediaExtractor.SAMPLE_FLAG_SYNC == 0
                    ) {
                        if (!extractor.advance()) { exhausted = true; break }
                    }
                    if (exhausted || extractor.sampleTime < 0) {
                        c.queueInputBuffer(
                            inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM
                        )
                        inputDone = true
                    } else {
                        val buf = c.getInputBuffer(inIdx)!!
                        val size = extractor.readSampleData(buf, 0)
                        if (size < 0) {
                            c.queueInputBuffer(
                                inIdx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM
                            )
                            inputDone = true
                        } else {
                            c.queueInputBuffer(
                                inIdx, 0, size, extractor.sampleTime,
                                MediaCodec.BUFFER_FLAG_KEY_FRAME
                            )
                            extractor.advance()
                        }
                    }
                }
            }

            val outIdx = c.dequeueOutputBuffer(info, TIMEOUT_US)
            when {
                outIdx >= 0 -> {
                    spins = 0
                    val eos = info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0
                    if (info.size > 0 || (toSurface != null && !eos)) {
                        val kf = if (toSurface != null) {
                            WardenKeyframe(info.presentationTimeUs, profileWidth(), profileHeight())
                        } else {
                            imageToKeyframe(c, outIdx, info.presentationTimeUs)
                        }
                        decodeNs = System.nanoTime() - t0
                        c.releaseOutputBuffer(outIdx, toSurface != null)
                        onFrame(kf)
                        decoded++
                    } else {
                        c.releaseOutputBuffer(outIdx, false)
                    }
                    if (eos) break
                }
                outIdx == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED ->
                    Log.i(TAG, "output format changed: ${c.outputFormat}")
                outIdx == MediaCodec.INFO_TRY_AGAIN_LATER -> {
                    // 🔴 REVIEW 2026-09-15: the spin budget used to be checked ONLY
                    // once `inputDone`, so a codec holding every input buffer
                    // (dequeueInputBuffer returning -1) while producing no output
                    // span forever at 10 ms a turn, with nothing to break the loop.
                    // decodeKeyframesBySeek already checked unconditionally.
                    if (++spins > MAX_SPINS_BEFORE_EOS && !inputDone) {
                        throw IllegalStateException(
                            "decoder produced no output for $MAX_SPINS_BEFORE_EOS " +
                                "consecutive polls with input still pending ($decoded " +
                                "keyframes so far). Input buffers are all in flight and " +
                                "nothing is coming back — the pipeline is wedged."
                        )
                    }
                    if (inputDone && spins > MAX_SPINS) {
                        throw IllegalStateException(
                            "decoder stalled after end-of-stream with $decoded keyframes " +
                                "decoded and no further output after $MAX_SPINS polls."
                        )
                    }
                }
            }
        }
        // 🔴 decodeNs accumulates the WALL time spent inside this loop up to the
        // last delivered frame. The caller's per-stage GL timings are taken in
        // onFrame(), which runs INSIDE that window, so they are NESTED in
        // decodeNs — it is not a disjoint stage. That is why a naive
        // `decode + upload + resolve + shader + readback` sum EXCEEDS the wall it
        // claims to decompose (measured: stage_total 35.125 vs wall 33.428 on
        // Path Z). WardenEngineBench.timingRun now also emits
        // `decode_excluding_gl` / `gl_total` / `gl_share_of_wall`; quote THOSE.
        // The engine's real share of the wall is ~6% (Path Z) / ~7% (Path P),
        // NOT the ~1% that the nested figures implied.
        return decoded
    }

    private fun profileWidth() = format.getInteger(MediaFormat.KEY_WIDTH)
    private fun profileHeight() = format.getInteger(MediaFormat.KEY_HEIGHT)

    /**
     * Coded frame geometry, for callers that have no buffer to measure.
     *
     * Path Z never sees a plane or a pixel count, so this is the only thing its
     * AC7 geometry assertion can key on — see
     * [WardenDetectionEngine.requireZeroCopyGeometry].
     */
    val frameWidth: Int get() = profileWidth()
    val frameHeight: Int get() = profileHeight()

    /**
     * Path P — copy the three planes out of the codec's Image.
     *
     * The copy is REAL and is exactly what Path P costs relative to Path Z; it is
     * timed inside decodeNs and reported, not hidden.
     */
    private fun imageToKeyframe(c: MediaCodec, outIdx: Int, ptsUs: Long): WardenKeyframe {
        val img = c.getOutputImage(outIdx)
            ?: throw IllegalStateException(
                "getOutputImage returned null — the codec is not in a flexible YUV " +
                    "colour format, so Path P cannot read planes."
            )
        val planes = img.planes
        val w = img.width
        val h = img.height
        val out = Array(3) { i ->
            val src = planes[i].buffer
            val copy = ByteBuffer.allocateDirect(src.remaining())
            copy.put(src); copy.position(0)
            copy
        }
        val rowStrides = IntArray(3) { planes[it].rowStride }
        val pixelStrides = IntArray(3) { planes[it].pixelStride }
        img.close()
        return WardenKeyframe(ptsUs, w, h, out, rowStrides, pixelStrides)
    }

    override fun close() {
        try { codec?.stop() } catch (_: Throwable) {}
        codec?.release(); codec = null
        extractor.release()
    }

    companion object {
        /**
         * 🔴 STORY 12.4a AC1 — WAS `10_000L`, AND THAT COST 10.6 ms PER KEYFRAME.
         *
         * MEASURED at 10 ms (`device_probe_flush.json{,_run2,_run3}`, 100 kf x 3):
         * **1.02 `INFO_TRY_AGAIN_LATER` per keyframe costing 10.59 ms/kf — 25% of
         * the 42.2 ms wall, spent asleep in a timeout we chose ourselves.**
         *
         * THE MECHANISM IS NOT "POLLING IS SLOW", AND GETTING THIS WRONG SENDS THE
         * NEXT READER AT THE CODEC INSTEAD OF AT THE LOOP. In the EOS-terminated
         * structure the loop queues the IDR, polls output once, gets TRY_AGAIN,
         * and then **sleeps a whole timeout before coming back round to queue the
         * `END_OF_STREAM` the decoder is waiting for** (trap 2: one queued sample
         * decodes to nothing). The sleep does not wait for slow hardware — it
         * WITHHOLDS the input that hardware needs. At 1 ms the EOS lands ~9 ms
         * earlier.
         */
        private const val TIMEOUT_US = 1_000L

        /**
         * Wedge caps, declared in TIME and converted to polls.
         *
         * 🔴 They used to be raw poll counts (`500` / `2000`), which silently
         * derived their real budget from [TIMEOUT_US]: changing the timeout by 10x
         * changed how long a wedged run takes to bail by 10x, turning a 20 s guard
         * into either a 2 s FALSE FAILURE or a 200 s hang. Expressed this way the
         * budget is invariant under a timeout change — 5 s and 20 s before, 5 s and
         * 20 s after.
         *
         * [MAX_SPINS_BEFORE_EOS] stays the generous one because the single-pass
         * strategy ([decodeKeyframes]) can legitimately go a while without output
         * while the extractor skips hundreds of non-sync samples.
         */
        private const val WEDGE_CAP_MS = 5_000L
        private const val WEDGE_CAP_BEFORE_EOS_MS = 20_000L
        private val MAX_SPINS = (WEDGE_CAP_MS * 1_000L / TIMEOUT_US).toInt()
        private val MAX_SPINS_BEFORE_EOS = (WEDGE_CAP_BEFORE_EOS_MS * 1_000L / TIMEOUT_US).toInt()

        /**
         * AC0a / AC2 — how many keyframes are kept in flight by
         * [decodeKeyframesBySeek], which is what lets the per-keyframe `flush()`
         * go away entirely.
         *
         * MEASURED, not chosen: `pipelineProbe` sweeps k in {1, 2, 4, 8, 16} over
         * the same 100 keyframes in one run. See the Story 12.4a Dev Agent Record
         * and `apps/mobile/bench/12-4a/`.
         */
        private const val PIPELINE_DEPTH = 8
    }
}

/**
 * Path Z's SurfaceTexture host.
 *
 * AC16 — SurfaceTexture.updateTexImage() has THREAD AFFINITY: it must be called
 * on the thread that owns the EGL context the texture belongs to. That is the
 * concrete constraint amendment 5d needs re-derived, and it is a property of the
 * GL context, not of the JS context.
 */
class WardenSurfaceTextureHost(texId: Int) : AutoCloseable {
    private val lock = Object()
    private var pendingFrames = 0
    val surfaceTexture = SurfaceTexture(texId)
    val surface: Surface
    private val stMatrix = FloatArray(16)

    /**
     * Dedicated Looper thread for the frame-available callback.
     *
     * 🔴 REVIEW 2026-09-15: `setOnFrameAvailableListener(listener)` with no
     * Handler binds to `Looper.myLooper()`, falling back to
     * `Looper.getMainLooper()` when the calling thread has none. The bench runs on
     * a plain `Thread` with no Looper, so EVERY frame notification was
     * round-tripping through the **main** thread — contended when `runBench()` is
     * called from JS with a live RN UI, idle when launched from the bench
     * Activity, so the two entry points were not measuring the same
     * `upload_or_bind`. That figure (0.367 ms) is the base of AC13(a). The old
     * timeout message asserted the opposite ("the listener fires on the thread
     * that created the SurfaceTexture"), which would have sent the next debugger
     * the wrong way.
     */
    private val callbackThread = HandlerThread("warden-st-frame").apply { start() }

    val surfaceTextureTimestampNs: Long get() = surfaceTexture.timestamp

    init {
        surfaceTexture.setOnFrameAvailableListener(
            { synchronized(lock) { pendingFrames++; lock.notifyAll() } },
            Handler(callbackThread.looper)
        )
        surface = Surface(surfaceTexture)
    }

    fun setDefaultBufferSize(w: Int, h: Int) = surfaceTexture.setDefaultBufferSize(w, h)

    /**
     * Blocks until the decoder has posted a frame, then binds it. Returns the ST
     * matrix.
     *
     * @param expectPtsUs the presentation timestamp of the keyframe this bind is
     *   supposed to deliver, or null to skip the check. REVIEW 2026-09-15:
     *   `frameAvailable` used to be a LATCH rather than a counter, and
     *   `getTimestamp()` was never compared against anything — so a coalesced or
     *   dropped frame was undetectable, and on Path Z there was no independent
     *   signal at all that the bound texture was the keyframe being timed.
     */
    fun awaitAndBind(timeoutMs: Long = 2000, expectPtsUs: Long? = null): FloatArray {
        synchronized(lock) {
            val deadline = System.currentTimeMillis() + timeoutMs
            while (pendingFrames == 0) {
                val remaining = deadline - System.currentTimeMillis()
                if (remaining <= 0) {
                    throw IllegalStateException(
                        "SurfaceTexture frame did not arrive within ${timeoutMs}ms. The " +
                            "listener runs on this host's own Looper thread " +
                            "(warden-st-frame), so the producer — MediaCodec — is what " +
                            "did not deliver."
                    )
                }
                lock.wait(remaining)
            }
            if (pendingFrames > 1) {
                // BufferQueue coalescing: updateTexImage() takes the NEWEST buffer,
                // so the frames in between are dropped and the timing attributed to
                // this bind covers more than one decode.
                Log.w(
                    TAG, "SurfaceTexture coalesced $pendingFrames frames before this bind; " +
                        "the bound texture is the newest, not the oldest"
                )
            }
            pendingFrames = 0
        }
        surfaceTexture.updateTexImage()
        if (expectPtsUs != null) {
            // SurfaceTexture timestamps are nanoseconds in the producer's
            // timebase, which for MediaCodec is the sample presentation time.
            val gotUs = surfaceTexture.timestamp / 1000L
            if (gotUs != expectPtsUs) {
                throw IllegalStateException(
                    "Path Z bound the WRONG frame: expected pts ${expectPtsUs}us but " +
                        "SurfaceTexture.getTimestamp() reports ${gotUs}us. Every per-rule " +
                        "decision and every ms/keyframe figure from this run would be " +
                        "attributed to a keyframe that is not the one that was decoded."
                )
            }
        }
        surfaceTexture.getTransformMatrix(stMatrix)
        return stMatrix
    }

    override fun close() {
        surface.release()
        surfaceTexture.release()
        callbackThread.quitSafely()
    }

    private companion object {
        const val TAG = "WardenStHost"
    }
}
