package team.warden.mobile

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.util.concurrent.atomic.AtomicBoolean

// Story 12.2 — the RN bridge. A THIN TRIGGER, nothing else.
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// AC0a's closing clause: "the engine Kotlin MUST be written RN-agnostic (a plain
// class plus a thin trigger), so the measurement code and the future runtime
// module are the same code." Every line of engine logic lives in
// WardenDetectionEngine / WardenRulePacker / WardenKeyframeDecoder /
// WardenCpuBaseline / WardenEngineBench, none of which import React Native. This
// file only marshals arguments and hands back JSON.
//
// Legacy bridge ReactPackage + @ReactMethod + Promise, matching the Story 1.2
// precedent (WardenProcessingModule). NOT a TurboModule: there is no codegen spec
// anywhere in the repo, and amendment 5d's real constraint is THREAD affinity,
// not the module system (AC16). Recorded as an explicit decision per Dev Notes.
//
// AC18b — sole access is via apps/mobile/src/shared/services/detectionEngine.ts.
// No feature module imports NativeModules.WardenDetectionEngine directly.
class WardenDetectionEngineModule(
    private val reactContext: ReactApplicationContext,
) : ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String = "WardenDetectionEngine"

    /**
     * Runs the bench off the JS thread and resolves with the report JSON.
     *
     * The engine's EGL context is created on THIS worker thread and never
     * touches the RN thread — which is precisely the AC16 finding: the binding
     * shape is governed by thread affinity, not by which JS context is alive.
     */
    @ReactMethod
    fun runBench(mode: String, video: String?, limit: Int, cpuFrames: Int, promise: Promise) {
        // 🔴 REVIEW 2026-09-15: two overlapping runs each spawned their own EGL
        // context and both wrote report_<mode>.json, parity_fires.json,
        // rules_lut_device.f32 and timing_fires_*.json into the same directory —
        // interleaved artifacts, and two runs contending for the GPU while each
        // claims to measure sustained clocks. A bench is a singleton by nature.
        if (!benchInFlight.compareAndSet(false, true)) {
            promise.reject(
                "WARDEN_BENCH_BUSY",
                "a bench run is already in flight; its artifacts and its GPU timings " +
                    "would both be corrupted by a second concurrent run"
            )
            return
        }
        Thread({
            try {
                val report = WardenEngineBench(reactContext.applicationContext)
                    .runAll(mode, video, limit, cpuFrames)
                promise.resolve(report.toString())
            } catch (t: Throwable) {
                promise.reject("WARDEN_BENCH_FAILED", t.message, t)
            } finally {
                benchInFlight.set(false)
            }
        }, "warden-bench-bridge").start()
    }

    /**
     * AC1/AC2 only — cheap enough to call from JS without a full bench run.
     * Creates and releases its own context, so it is safe to call repeatedly.
     */
    @ReactMethod
    fun describeDevice(promise: Promise) {
        Thread({
            var egl: WardenEglContext? = null
            try {
                egl = WardenEglContext.createOffscreen()
                val bench = WardenEngineBench(reactContext.applicationContext)
                promise.resolve(bench.deviceProfile(egl, null).toString())
            } catch (t: Throwable) {
                promise.reject("WARDEN_DEVICE_PROBE_FAILED", t.message, t)
            } finally {
                egl?.release()
            }
        }, "warden-device-probe").start()
    }

    companion object {
        /**
         * Process-wide guard: the bench owns the GPU, the EGL context and a fixed
         * set of artifact filenames, so exactly one run may be in flight.
         * [WardenEngineBenchActivity] takes the same latch.
         */
        @JvmStatic
        val benchInFlight = AtomicBoolean(false)
    }
}
