package team.warden.mobile

import android.opengl.GLES11Ext
import android.opengl.GLES30
import android.util.Log
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.FloatBuffer

// Story 12.2 — the GLES 3.0 mega-shader engine, ported from Tool 12 (Story 12.1).
// Generated by with-detection-engine.js; tracked source is plugins/kotlin/.
//
// RN-agnostic (AC0a): no React Native imports. The bench and the future runtime
// module drive the SAME class.
//
// ===========================================================================
// AC4 / AC13 — WHY BOTH COLOUR PATHS GO THROUGH A "RESOLVE" PASS
//
// keyframe_engine_bench.frag declares `uniform sampler2D uFrame` and is COPIED
// VERBATIM (AC4). MediaCodec's zero-copy output is a `samplerExternalOES`, which
// a `sampler2D` uniform cannot sample. There were only two ways out:
//
//   (a) change the frag to take a samplerExternalOES  -> TWO shader bodies,
//       breaking E2 ("same GLSL source of truth") and AC4 outright; or
//   (b) a small RESOLVE pass that reads the path-specific source and writes one
//       common RGBA8 texture, which the UNMODIFIED mega-shader then samples.
//
// (b) is taken. It preserves AC4 exactly and gives AC0c its "one seam": Path Z
// and Path P differ ONLY in their resolve shader, so everything downstream —
// program, LUT, FBO, readback, scoring — is bit-identically shared and the two
// are measured on identical everything-else.
//
// 🔴 THE COST IS A REAL FINDING FOR 12.3, NOT AN IMPLEMENTATION DETAIL. Path Z
// does NOT reduce to "the upload disappears". It removes the 6.2 MB HOST->DEVICE
// bus transfer (the thing that cost 12.1's PC run ~2.4 ms and lost it the
// CPU-vs-GPU comparison), but it leaves an on-GPU full-frame resolve. The
// resolve is timed SEPARATELY and reported as its own stage so the report can
// state honestly what zero-copy bought and what it did not.
//
// CHANNEL ORDER: the mega-shader documents uFrame as OpenCV BGR memory order
// (.r == blue, .g == green, .b == red) because hsv_cv() takes (b, g, r)
// POSITIONALLY. Every resolve shader therefore writes vec4(b, g, r, 1.0). Get
// this backwards and hue is mirrored about the red axis while S and V stay
// perfect — which reads as "the shader is subtly wrong", not "the channels are
// swapped".
// ===========================================================================

private const val TAG = "WardenEngine"

/** Which colour path feeds the mega-shader (AC0c). */
enum class WardenColorPath {
    /** MediaCodec -> SurfaceTexture -> samplerExternalOES. Fast, colour DRIVER-DEFINED. */
    ZERO_COPY,

    /** COLOR_FormatYUV420Flexible -> three R8 planes -> our own bt709 limited-range math. Colour-EXACT. */
    BIT_PARITY,

    /** A CPU-side RGB bitmap (the PNG parity corpus). Isolates SHADER parity from DECODE colour. */
    DIRECT_RGB,
}

/** Per-stage nanosecond timings for one keyframe. */
data class WardenStageTimings(
    var decodeNs: Long = 0,
    var uploadOrBindNs: Long = 0,
    var resolveNs: Long = 0,
    var shaderNs: Long = 0,
    var readbackNs: Long = 0,
) {
    val totalNs: Long get() = decodeNs + uploadOrBindNs + resolveNs + shaderNs + readbackNs
}

class WardenDetectionEngine(
    fragBody: String,
    private val packed: WardenPackedRules,
    private val frameWidth: Int,
    private val frameHeight: Int,
    private val colorPath: WardenColorPath,
    /** Set false only for the AC2 probe, which wants a compile result, not a run. */
    private val runSelfTest: Boolean = true,
) {
    private var megaProgram = 0
    private var resolveProgram = 0
    private var fbo = 0
    private var resultTex = 0
    private var rulesTex = 0
    /** The common BGR-ordered RGBA8 frame texture every path resolves into. */
    private var frameTex = 0
    private var frameFbo = 0
    private var vao = 0

    /** Path P textures: [0] = Y as R8, [1] = chroma as RG8 (.r = Cb, .g = Cr). */
    private var planeTex = IntArray(2)

    /** Path P plane textures get their storage once, at the first upload. */
    private var planeStorageReady = false
    /** Path Z external texture name; owned by the caller's SurfaceTexture. */
    var externalTexId = 0
        private set

    private val readbackBuf: ByteBuffer =
        ByteBuffer.allocateDirect(MAX_RULES * 4).order(ByteOrder.nativeOrder())

    /** One-off construction cost, reported separately from ms_per_keyframe (AC11). */
    var setupNs: Long = 0
        private set

    init {
        val t0 = System.nanoTime()
        try {
            buildPrograms(fragBody)
            buildTargets()
            uploadRules()
            if (runSelfTest) selfTest()
        } catch (t: Throwable) {
            // AC7 — release on a FAILED construction. Leaking ~6 MB and an EGL
            // context on the very path the self-test exists to catch would turn
            // a clear diagnostic into a second, unrelated failure.
            release()
            throw t
        }
        setupNs = System.nanoTime() - t0
    }

    // -----------------------------------------------------------------------
    // Programs
    // -----------------------------------------------------------------------

    /**
     * The ONLY difference between what ran on the PC and what runs here is the
     * `#version` line — exactly as shader.py::build_source does it (E2/AC4).
     */
    private fun buildPrograms(fragBody: String) {
        val vert = ES_VERSION + "\n" + VERT_BODY
        megaProgram = WardenGlUtil.linkProgram(vert, ES_VERSION + "\n" + fragBody)
        // DIRECT_RGB has NO resolve pass: the BGR reorder is done CPU-side and the
        // bytes go straight into frameTex. Resolving in place (frameTex as both
        // source and target) is undefined in GL, and the PNG corpus exists to
        // isolate SHADER parity — adding a resolve would inject the very variable
        // the corpus is designed to exclude.
        resolveFragmentSource()?.let {
            resolveProgram = WardenGlUtil.linkProgram(vert, it)
        }
        WardenGlUtil.checkGl("buildPrograms")
    }

    private fun resolveFragmentSource(): String? = when (colorPath) {
        WardenColorPath.ZERO_COPY -> RESOLVE_OES_FRAG
        WardenColorPath.BIT_PARITY -> RESOLVE_YUV_FRAG
        WardenColorPath.DIRECT_RGB -> null
    }

    // -----------------------------------------------------------------------
    // Targets and textures
    // -----------------------------------------------------------------------

    private fun buildTargets() {
        val ids = IntArray(1)

        // AC6 — the result target is RGBA8, NEVER RGBA32F. RGBA32F is not
        // colour-renderable in ES 3.0 core, and glReadPixels guarantees only
        // GL_RGBA/GL_UNSIGNED_BYTE. Texturing a 32F LUT is fine; RENDERING to one
        // is not. (12.1 lost a full accuracy run to exactly this distinction.)
        GLES30.glGenTextures(1, ids, 0); resultTex = ids[0]
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, resultTex)
        GLES30.glTexStorage2D(GLES30.GL_TEXTURE_2D, 1, GLES30.GL_RGBA8, MAX_RULES, 1)
        setNearestClamp()

        GLES30.glGenFramebuffers(1, ids, 0); fbo = ids[0]
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, fbo)
        GLES30.glFramebufferTexture2D(
            GLES30.GL_FRAMEBUFFER, GLES30.GL_COLOR_ATTACHMENT0,
            GLES30.GL_TEXTURE_2D, resultTex, 0
        )
        requireFramebufferComplete("result FBO")

        // The common BGR-ordered frame texture + its FBO (the resolve target).
        GLES30.glGenTextures(1, ids, 0); frameTex = ids[0]
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, frameTex)
        GLES30.glTexStorage2D(GLES30.GL_TEXTURE_2D, 1, GLES30.GL_RGBA8, frameWidth, frameHeight)
        setNearestClamp()

        GLES30.glGenFramebuffers(1, ids, 0); frameFbo = ids[0]
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, frameFbo)
        GLES30.glFramebufferTexture2D(
            GLES30.GL_FRAMEBUFFER, GLES30.GL_COLOR_ATTACHMENT0,
            GLES30.GL_TEXTURE_2D, frameTex, 0
        )
        requireFramebufferComplete("resolve FBO")

        when (colorPath) {
            WardenColorPath.ZERO_COPY -> {
                GLES30.glGenTextures(1, ids, 0); externalTexId = ids[0]
                GLES30.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, externalTexId)
                GLES30.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES30.GL_TEXTURE_MIN_FILTER, GLES30.GL_NEAREST)
                GLES30.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES30.GL_TEXTURE_MAG_FILTER, GLES30.GL_NEAREST)
                GLES30.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES30.GL_TEXTURE_WRAP_S, GLES30.GL_CLAMP_TO_EDGE)
                GLES30.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES30.GL_TEXTURE_WRAP_T, GLES30.GL_CLAMP_TO_EDGE)
            }
            WardenColorPath.BIT_PARITY -> {
                // planeTex[0] = Y (R8), planeTex[1] = chroma (RG8, .r=Cb .g=Cr).
                GLES30.glGenTextures(2, planeTex, 0)
                // Y is full-res; U and V are half-res for 4:2:0. Storage is
                // allocated lazily by ensurePlaneStorage() on the first upload,
                // where the ACTUAL chroma geometry is known — MediaCodec row/pixel
                // strides are device-specific and assuming width == rowStride is a
                // classic silent corruption. (Before the 2026-09-15 review this
                // comment described behaviour the code did not have: the upload
                // path re-specified storage on EVERY frame.)
                for (t in planeTex) {
                    GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, t)
                    setNearestClamp()
                }
            }
            WardenColorPath.DIRECT_RGB -> { /* uploads straight into frameTex */ }
        }

        // The LUT: 150x3 RGBA32F. Texture-only use, sampled with texelFetch.
        GLES30.glGenTextures(1, ids, 0); rulesTex = ids[0]
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, rulesTex)
        GLES30.glTexStorage2D(GLES30.GL_TEXTURE_2D, 1, GLES30.GL_RGBA32F, MAX_RULES, 3)
        setNearestClamp()

        GLES30.glGenVertexArrays(1, ids, 0); vao = ids[0]

        WardenGlUtil.checkGl("buildTargets")
    }

    private fun setNearestClamp() {
        GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_MIN_FILTER, GLES30.GL_NEAREST)
        GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_MAG_FILTER, GLES30.GL_NEAREST)
        GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_WRAP_S, GLES30.GL_CLAMP_TO_EDGE)
        GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_WRAP_T, GLES30.GL_CLAMP_TO_EDGE)
    }

    private fun requireFramebufferComplete(what: String) {
        val status = GLES30.glCheckFramebufferStatus(GLES30.GL_FRAMEBUFFER)
        if (status != GLES30.GL_FRAMEBUFFER_COMPLETE) {
            throw WardenGlException("$what incomplete: 0x%04X".format(status))
        }
    }

    /**
     * 🔴 THE LUT MUST BE TRANSPOSED ON UPLOAD. This cost a full parity run.
     *
     * `WardenPackedRules.texture` is laid out **rule-major** — `[rule][row][ch]`,
     * the same shape `lut.py` produces — because that is the order the CPU
     * baseline indexes. A GL texture is **row-major**: row 0 must hold all 150
     * rules' FIRST texel, then row 1 all their second, then row 2. Uploading the
     * rule-major array verbatim puts rule 0's three rows in the first three
     * texels of row 0, so `texelFetch(uRules, ivec2(i, 0))` reads rule i/3's row
     * i%3 — every bound scrambled.
     *
     * `shader.py:203` does exactly this transpose (`.transpose(1, 0, 2)`) and it
     * is easy to miss, because **the byte-for-byte LUT cross-check still passes**:
     * that check validates the PACKING, which was correct, while the defect is in
     * the UPLOAD LAYOUT. MEASURED symptom: the device CPU baseline and the PC GPU
     * agreed, while the device GPU disagreed on 37% of all rule-frame decisions —
     * across full-circle rules too, which ignore hue entirely, which is what
     * ruled out every hue-related hypothesis and pointed here.
     */
    private fun uploadRules() {
        val fb: FloatBuffer = ByteBuffer
            .allocateDirect(packed.texture.size * 4).order(ByteOrder.nativeOrder())
            .asFloatBuffer()
        for (row in 0 until 3) {
            for (rule in 0 until MAX_RULES) {
                val base = (rule * 3 + row) * 4
                fb.put(packed.texture[base])
                fb.put(packed.texture[base + 1])
                fb.put(packed.texture[base + 2])
                fb.put(packed.texture[base + 3])
            }
        }
        fb.position(0)
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, rulesTex)
        GLES30.glPixelStorei(GLES30.GL_UNPACK_ALIGNMENT, 1)
        GLES30.glTexSubImage2D(
            GLES30.GL_TEXTURE_2D, 0, 0, 0, MAX_RULES, 3,
            GLES30.GL_RGBA, GLES30.GL_FLOAT, fb
        )
        WardenGlUtil.checkGl("uploadRules")
    }

    // -----------------------------------------------------------------------
    // AC7 — construction-time self-test. NO NUMBER IS TRUSTED BEFORE THIS PASSES.
    // -----------------------------------------------------------------------

    /**
     * 12.1's most expensive lesson, encoded. A GL_RGBA8UI-vs-GL_RGBA8 mismatch
     * returned UNINITIALIZED MEMORY that looked like plausible detections
     * (0.35/0.31/0.05), raised nothing, and read as "the port is broken" rather
     * than "the format is wrong". It cost a full accuracy run.
     *
     * So: clear the FBO to a known value, read it back, assert the VALUE and
     * `glGetError() == GL_NO_ERROR`. GL failures are silent by nature.
     */
    private fun selfTest() {
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, fbo)
        GLES30.glViewport(0, 0, MAX_RULES, 1)
        // 0.25 quantizes to 64, 0.75 to 191 — both far from 0 and 255, so a
        // target that is silently uninitialized, integer-formatted or
        // wrongly-normalized cannot accidentally produce them.
        GLES30.glClearColor(0.25f, 0.75f, 0.25f, 1.0f)
        GLES30.glClear(GLES30.GL_COLOR_BUFFER_BIT)
        val probe = readResultTexels()
        val r = probe[0].toInt() and 0xFF
        val g = probe[1].toInt() and 0xFF
        if (r !in 63..65 || g !in 190..192) {
            throw WardenGlException(
                "AC7 self-test FAILED: cleared the 150x1 RGBA8 target to (0.25, 0.75) " +
                    "and read back r=$r g=$g (expected ~64 / ~191). The render target " +
                    "format or the readback is wrong. DO NOT trust any number from this " +
                    "context — 12.1 lost a full accuracy run to exactly this class of " +
                    "silent failure."
            )
        }
        WardenGlUtil.checkGl("AC7 self-test")
        selfTestRulesTexture()
        Log.i(TAG, "AC7 self-test passed (r=$r g=$g), colorPath=$colorPath")
    }

    /**
     * AC7, second half — prove the GPU reads the SAME rule bounds the CPU packed.
     *
     * The original self-test only cleared and read the result FBO, so it proved
     * the render target was sane and nothing else. It sailed straight past a
     * transposed `uRules` upload, which produced plausible-looking detections
     * from completely scrambled bounds — the *exact* failure mode 12.1 paid a
     * full accuracy run to learn, reappearing in a new place.
     *
     * So: a probe pass samples `uRules` on the GPU and compares it, ON THE GPU,
     * against the same values re-uploaded through an INDEPENDENT layout path. If
     * the GPU's view of the LUT differs from the CPU's in any texel, NOTHING
     * downstream is trustworthy.
     *
     * 🔴 REVIEW 2026-09-15 — the first version of this check had two holes, both
     * of which reproduce the very failure class it exists to catch:
     *
     *  1. **It never sampled row 1.** It fetched rows 0 and 2 and compared only
     *     `w`, `h` and `mode`. Row 1 is `(h_lo, h_hi, s_lo, s_hi)` — the HSV
     *     bounds themselves — and `x`, `y`, `v_lo`, `v_hi` and `min_ratio` were
     *     never read GPU-side either. A corruption confined to row 1 passed the
     *     self-test and produced plausible-looking detections from wrong bounds.
     *  2. **It round-tripped w/h through 8 bits.** `packRules` caps rule AREA at
     *     `MAX_RECT_TEXELS`, not width, so a 1920x2 strip packs fine; the RGBA8
     *     target then clamped 300 to 255 and the check threw
     *     *"the classic cause is uploading the rule-major array without
     *     transposing it"* — pointing at a transpose bug that is not there.
     *
     * Both are fixed by comparing on the GPU instead of reading values back: three
     * reference textures are built by extracting each LUT row separately (a
     * different traversal from [uploadRules]' transpose, so a layout bug cannot
     * cancel out), the shader emits one 0/1 mismatch flag per row, and the RGBA8
     * target only ever has to carry a boolean. All 12 floats per rule are now
     * checked, bit-exactly, whatever their magnitude.
     */
    private fun selfTestRulesTexture() {
        val probe = WardenGlUtil.linkProgram(
            ES_VERSION + "\n" + VERT_BODY, RULES_PROBE_FRAG
        )
        val refTex = IntArray(3)
        try {
            // Reference textures: one per LUT row, each MAX_RULES x 1 RGBA32F,
            // filled by walking the rule-major array row-by-row. Deliberately NOT
            // the same traversal uploadRules() uses.
            GLES30.glGenTextures(3, refTex, 0)
            for (row in 0 until 3) {
                val fb: FloatBuffer = ByteBuffer
                    .allocateDirect(MAX_RULES * 4 * 4).order(ByteOrder.nativeOrder())
                    .asFloatBuffer()
                for (rule in 0 until MAX_RULES) {
                    val base = (rule * 3 + row) * 4
                    fb.put(packed.texture[base])
                    fb.put(packed.texture[base + 1])
                    fb.put(packed.texture[base + 2])
                    fb.put(packed.texture[base + 3])
                }
                fb.position(0)
                GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, refTex[row])
                GLES30.glTexStorage2D(GLES30.GL_TEXTURE_2D, 1, GLES30.GL_RGBA32F, MAX_RULES, 1)
                setNearestClamp()
                GLES30.glPixelStorei(GLES30.GL_UNPACK_ALIGNMENT, 1)
                GLES30.glTexSubImage2D(
                    GLES30.GL_TEXTURE_2D, 0, 0, 0, MAX_RULES, 1,
                    GLES30.GL_RGBA, GLES30.GL_FLOAT, fb
                )
            }
            WardenGlUtil.checkGl("rules-probe reference upload")

            GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, fbo)
            GLES30.glViewport(0, 0, MAX_RULES, 1)
            GLES30.glUseProgram(probe)
            GLES30.glBindVertexArray(vao)
            GLES30.glActiveTexture(GLES30.GL_TEXTURE0)
            GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, rulesTex)
            GLES30.glUniform1i(GLES30.glGetUniformLocation(probe, "uRules"), 0)
            for (row in 0 until 3) {
                GLES30.glActiveTexture(GLES30.GL_TEXTURE1 + row)
                GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, refTex[row])
                GLES30.glUniform1i(GLES30.glGetUniformLocation(probe, "uRef$row"), 1 + row)
            }
            GLES30.glDrawArrays(GLES30.GL_TRIANGLES, 0, 3)
            WardenGlUtil.checkGl("rules-texture probe draw")

            val raw = readResultTexels()
            for (i in 0 until packed.nRules) {
                for (row in 0 until 3) {
                    if ((raw[i * 4 + row].toInt() and 0xFF) == 0) continue
                    val base = (i * 3 + row) * 4
                    val expected = (0 until 4).joinToString(", ") { packed.texture[base + it].toString() }
                    throw WardenGlException(
                        "AC7 rules-texture self-test FAILED: rule $i, LUT row $row. The " +
                            "GPU's texelFetch(uRules, ivec2($i, $row)) does not equal the " +
                            "CPU-packed ($expected). Row 0 is (x, y, w, h), row 1 is " +
                            "(h_lo, h_hi, s_lo, s_hi), row 2 is (v_lo, v_hi, min_ratio, " +
                            "mode). A mismatch on EVERY row points at the upload layout " +
                            "(the rule-major array must be transposed to the texture's " +
                            "row-major order — see uploadRules); a mismatch on ONE row " +
                            "points at that row's packing. Either way, every number from " +
                            "this engine would be garbage that LOOKS like plausible " +
                            "detections."
                    )
                }
            }
            Log.i(
                TAG,
                "AC7 rules-texture self-test passed (${packed.nRules} rules x 3 rows " +
                    "x 4 components verified bit-exactly on GPU)"
            )
        } finally {
            if (refTex.any { it != 0 }) GLES30.glDeleteTextures(3, refTex, 0)
            if (probe != 0) GLES30.glDeleteProgram(probe)
        }
    }

    /**
     * AC7 — validate texture GEOMETRY on every upload, not just byte count. A
     * same-byte-count / different-geometry frame yields silently TRANSPOSED
     * pixels, which produces plausible-looking wrong detections.
     */
    private fun requireGeometry(w: Int, h: Int, what: String) {
        if (w != frameWidth || h != frameHeight) {
            throw WardenGlException(
                "$what geometry is ${w}x$h but the engine was built for " +
                    "${frameWidth}x$frameHeight. A same-byte-count frame of different " +
                    "geometry uploads without error and silently transposes the image."
            )
        }
    }

    /**
     * AC7 for Path Z, which has no upload to hang a geometry check on.
     *
     * 🔴 REVIEW 2026-09-15: [requireGeometry] was called only from
     * [uploadRgbaFrame] and [uploadYuvPlanes]. Path Z uploads nothing, so it had
     * NO geometry assertion at all — and `SurfaceTexture.setDefaultBufferSize` is
     * ignored once MediaCodec, the producer, sets the buffer size. A capture that
     * is not `frameWidth x frameHeight` was therefore nearest-neighbour rescaled
     * into the fixed-size target by `RESOLVE_OES_FRAG` (which samples with
     * normalised uv scaled by `uSize`), every rect evaluating against resampled
     * pixels, while Path P threw `WardenGlException` on exactly the same input.
     * AC13's Path Z vs Path P comparison would then be a rescaled frame against a
     * crash.
     */
    fun requireZeroCopyGeometry(w: Int, h: Int) {
        if (colorPath != WardenColorPath.ZERO_COPY) return
        requireGeometry(w, h, "zero-copy (SurfaceTexture) frame")
    }

    // -----------------------------------------------------------------------
    // Frame ingestion — one per colour path, all resolving into frameTex
    // -----------------------------------------------------------------------

    /**
     * Path DIRECT_RGB: a CPU-side RGBA bitmap (AC14a's PNG corpus).
     * `pixels` is ARGB_8888 as Android delivers it; the resolve shader performs
     * the BGR reorder so no CPU-side channel shuffling can drift from the
     * GPU paths.
     */
    fun uploadRgbaFrame(pixels: ByteBuffer, w: Int, h: Int): Long {
        requireGeometry(w, h, "RGBA frame")
        val t0 = System.nanoTime()
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, frameTex)
        GLES30.glPixelStorei(GLES30.GL_UNPACK_ALIGNMENT, 1)
        pixels.position(0)
        GLES30.glTexSubImage2D(
            GLES30.GL_TEXTURE_2D, 0, 0, 0, w, h,
            GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, pixels
        )
        WardenGlUtil.checkGl("uploadRgbaFrame")
        return System.nanoTime() - t0
    }

    /**
     * Path BIT_PARITY: Y as R8 + chroma as ONE RG8 texture (.r = Cb, .g = Cr).
     *
     * 🔴 `pixelStride` IS LOAD-BEARING AND WAS THE BUG.
     *
     * `COLOR_FormatYUV420Flexible` is a FAMILY, not a layout. Qualcomm's
     * `c2.qti.avc.decoder` hands back **semi-planar NV12**: the U and V planes
     * share one interleaved buffer with `pixelStride == 2`, and `planes[2]` is
     * `planes[1]` offset by one byte. Uploading that as a tightly-packed R8
     * texture reads `UVUVUV…` as if it were `UUU…` — which corrupts BOTH chroma
     * channels across the whole frame while Y stays perfect. MEASURED
     * consequence: 98.7% of pixels wrong, mean |dBGR| 7.49, error spread evenly
     * rather than concentrated on edges (the signature that ruled out chroma
     * interpolation and pointed here).
     *
     * Using an RG8 chroma texture handles the common case with ZERO CPU work:
     * `GL_UNPACK_ROW_LENGTH` is counted in PIXELS, and an RG8 pixel is exactly
     * the 2 bytes an NV12 chroma pair occupies, so the decoder's own buffer
     * uploads verbatim. Fully-planar output (pixelStride 1) is also supported,
     * at the cost of a CPU interleave — reported separately, since that cost is
     * real and device-dependent.
     */
    fun uploadYuvPlanes(
        y: ByteBuffer, yStride: Int,
        u: ByteBuffer, uStride: Int, uPixelStride: Int,
        v: ByteBuffer, vStride: Int, vPixelStride: Int,
        w: Int, h: Int,
    ): Long {
        requireGeometry(w, h, "YUV frame")
        val t0 = System.nanoTime()
        val cw = (w + 1) / 2
        val ch = (h + 1) / 2
        ensurePlaneStorage(cw, ch)
        GLES30.glPixelStorei(GLES30.GL_UNPACK_ALIGNMENT, 1)

        // Row stride via GL_UNPACK_ROW_LENGTH (ES 3.0 core). Uploading `width`
        // bytes per row from a buffer whose rows are `rowStride` apart shears the
        // image progressively — which reads as a colour bug, not a layout bug.
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, planeTex[0])
        GLES30.glPixelStorei(GLES30.GL_UNPACK_ROW_LENGTH, yStride)
        y.position(0)
        GLES30.glTexSubImage2D(
            GLES30.GL_TEXTURE_2D, 0, 0, 0, w, h,
            GLES30.GL_RED, GLES30.GL_UNSIGNED_BYTE, y
        )

        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, planeTex[1])
        if (isSemiPlanarNv12(u, uStride, uPixelStride, v, vPixelStride, cw, ch)) {
            // NV12 proper: upload the decoder's interleaved buffer directly as RG8.
            // ROW_LENGTH is in PIXELS and an RG8 pixel is 2 bytes, so the byte
            // stride divides exactly — asserted above, not assumed.
            GLES30.glPixelStorei(GLES30.GL_UNPACK_ROW_LENGTH, uStride / 2)
            u.position(0)
            GLES30.glTexSubImage2D(
                GLES30.GL_TEXTURE_2D, 0, 0, 0, cw, ch,
                GLES30.GL_RG, GLES30.GL_UNSIGNED_BYTE, u
            )
        } else {
            // Everything else — fully planar I420, NV21, separate U/V buffers, an
            // odd chroma stride, or a final row too short for a verbatim RG8
            // upload. Interleave into a tight RG8 buffer. CPU cost, but it keeps
            // ONE resolve shader for every device layout, and it reads each plane
            // through its OWN stride/pixelStride so no ordering is assumed.
            val packed = ByteBuffer.allocateDirect(cw * ch * 2).order(ByteOrder.nativeOrder())
            for (row in 0 until ch) {
                for (col in 0 until cw) {
                    packed.put(u.get(row * uStride + col * uPixelStride))
                    packed.put(v.get(row * vStride + col * vPixelStride))
                }
            }
            packed.position(0)
            GLES30.glPixelStorei(GLES30.GL_UNPACK_ROW_LENGTH, 0)
            GLES30.glTexSubImage2D(
                GLES30.GL_TEXTURE_2D, 0, 0, 0, cw, ch,
                GLES30.GL_RG, GLES30.GL_UNSIGNED_BYTE, packed
            )
        }
        GLES30.glPixelStorei(GLES30.GL_UNPACK_ROW_LENGTH, 0)
        WardenGlUtil.checkGl("uploadYuvPlanes")
        return System.nanoTime() - t0
    }

    /**
     * Is this chroma layout a verbatim-uploadable **NV12**?
     *
     * 🔴 REVIEW 2026-09-15 — three separate defects lived in the old
     * `uPixelStride == 2 && vPixelStride == 2` test:
     *
     *  1. **NV21 took the same branch.** The check keyed only on pixel stride and
     *     then uploaded `planes[1]` (Cb) as the RG8 base, ignoring `planes[2]`
     *     entirely. On NV12 (`U V U V …`) the pairs are (U0,V0) — correct. On
     *     NV21 (`V U V U …`) `planes[1]` starts at chroma offset **1**, so every
     *     Cr came from the column to the RIGHT: a silent, frame-wide chroma shift
     *     on the path the report recommends shipping *because* it is exact. Two
     *     entirely separate U/V buffers with pixelStride 2 took the branch too,
     *     and read V data out of the U buffer. Fixed by requiring that V sit
     *     exactly one byte after U **in the same buffer**.
     *  2. **`uStride / 2` truncated.** An odd chroma row stride made ROW_LENGTH
     *     short by half a pixel per row — progressive horizontal chroma shear,
     *     no error raised. The old comment asserted the stride "divides exactly"
     *     without checking it.
     *  3. **A one-byte out-of-bounds read.** `MediaImage`'s semi-planar U plane
     *     ends at the last *U* byte, i.e. `(ch-1)*uStride + (cw-1)*2 + 1` bytes,
     *     while an RG8 upload of `cw x ch` needs one byte more. `glTexSubImage2D`
     *     does not bounds-check a direct buffer, so one OOB heap byte became the
     *     bottom-right Cr — inside the path AC3 asserts bit-exactness on.
     *
     * Anything that fails any of these falls to the interleaving path, which is
     * slower but correct for every layout.
     */
    private fun isSemiPlanarNv12(
        u: ByteBuffer, uStride: Int, uPixelStride: Int,
        v: ByteBuffer, vPixelStride: Int,
        cw: Int, ch: Int,
    ): Boolean {
        if (uPixelStride != 2 || vPixelStride != 2) return false
        if (uStride % 2 != 0) return false
        // Cr must be the byte immediately after Cb, in the same allocation.
        // `v.get(0)` and `u.get(1)` are the same byte exactly when the planes are
        // NV12-interleaved; on NV21 the ordering is reversed and this fails.
        if (u.remaining() < 2 || v.remaining() < 1) return false
        if (u.get(1) != v.get(0)) return false
        // A verbatim RG8 upload reads through the LAST Cr byte of the last row.
        if (u.remaining() < (ch - 1) * uStride + cw * 2) return false
        return true
    }

    /**
     * Allocate the Y and chroma plane textures ONCE, at the first upload, where
     * the real chroma geometry is known.
     *
     * 🔴 REVIEW 2026-09-15: [uploadYuvPlanes] used to call `glTexImage2D`, which
     * re-specifies STORAGE, on every one of 1061 keyframes — for a 1920x1080 R8
     * plus a 960x540 RG8. Every other texture in this class uses
     * `glTexStorage2D` + `glTexSubImage2D`, and `buildTargets()`'s own comment
     * already claimed these two were "allocated lazily on the first upload".
     * They were not. Path P's measured **1.720 ms** upload therefore carries a
     * driver-side storage re-spec that a steady state does not pay, which is one
     * half of AC13(a)'s "4.7x cheaper than a bind" comparison.
     */
    private fun ensurePlaneStorage(cw: Int, ch: Int) {
        if (planeStorageReady) return
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, planeTex[0])
        GLES30.glTexStorage2D(GLES30.GL_TEXTURE_2D, 1, GLES30.GL_R8, frameWidth, frameHeight)
        setNearestClamp()
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, planeTex[1])
        GLES30.glTexStorage2D(GLES30.GL_TEXTURE_2D, 1, GLES30.GL_RG8, cw, ch)
        setNearestClamp()
        WardenGlUtil.checkGl("ensurePlaneStorage")
        planeStorageReady = true
    }

    /**
     * Resolve whatever the path just ingested into the shared BGR RGBA8 frame
     * texture. For ZERO_COPY the source is the external texture the caller's
     * SurfaceTexture just updated; nothing is uploaded, which is the entire
     * point of the path — and the cost of THIS pass is what AC13 must report.
     */
    fun resolve(stMatrix: FloatArray? = null): Long {
        if (colorPath == WardenColorPath.DIRECT_RGB) return 0L
        val t0 = System.nanoTime()
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, frameFbo)
        GLES30.glViewport(0, 0, frameWidth, frameHeight)
        GLES30.glUseProgram(resolveProgram)
        GLES30.glBindVertexArray(vao)

        when (colorPath) {
            WardenColorPath.ZERO_COPY -> {
                GLES30.glActiveTexture(GLES30.GL_TEXTURE0)
                GLES30.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, externalTexId)
                GLES30.glUniform1i(GLES30.glGetUniformLocation(resolveProgram, "uExternal"), 0)
                val m = stMatrix ?: throw WardenGlException(
                    "Path Z resolve needs SurfaceTexture.getTransformMatrix(); without " +
                        "it the frame orientation and crop are guesses."
                )
                GLES30.glUniformMatrix4fv(
                    GLES30.glGetUniformLocation(resolveProgram, "uStMatrix"), 1, false, m, 0
                )
                GLES30.glUniform2f(
                    GLES30.glGetUniformLocation(resolveProgram, "uSize"),
                    frameWidth.toFloat(), frameHeight.toFloat()
                )
            }
            WardenColorPath.BIT_PARITY -> {
                GLES30.glActiveTexture(GLES30.GL_TEXTURE0)
                GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, planeTex[0])
                GLES30.glUniform1i(GLES30.glGetUniformLocation(resolveProgram, "uY"), 0)
                GLES30.glActiveTexture(GLES30.GL_TEXTURE1)
                GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, planeTex[1])
                GLES30.glUniform1i(GLES30.glGetUniformLocation(resolveProgram, "uUV"), 1)
            }
            WardenColorPath.DIRECT_RGB -> { /* unreachable — guarded above */ }
        }
        GLES30.glDrawArrays(GLES30.GL_TRIANGLES, 0, 3)
        WardenGlUtil.checkGl("resolve")
        return System.nanoTime() - t0
    }

    /**
     * DIRECT_RGB ingestion: bytes ALREADY in B,G,R,A order, straight into
     * frameTex with no resolve pass. Used only by the PNG parity corpus (AC14a),
     * where isolating SHADER parity from DECODE colour is the entire point.
     */
    fun uploadBgrDirect(bgra: ByteBuffer, w: Int, h: Int): Long = uploadRgbaFrame(bgra, w, h)

    // -----------------------------------------------------------------------
    // The mega-shader draw + readback
    // -----------------------------------------------------------------------

    /** One draw over the 150x1 target. Returns nanoseconds (naive, non-blocking). */
    fun evaluate(): Long {
        val t0 = System.nanoTime()
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, fbo)
        GLES30.glViewport(0, 0, MAX_RULES, 1)
        GLES30.glUseProgram(megaProgram)
        GLES30.glBindVertexArray(vao)

        GLES30.glActiveTexture(GLES30.GL_TEXTURE0)
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, frameTex)
        GLES30.glUniform1i(GLES30.glGetUniformLocation(megaProgram, "uFrame"), 0)

        GLES30.glActiveTexture(GLES30.GL_TEXTURE1)
        GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, rulesTex)
        GLES30.glUniform1i(GLES30.glGetUniformLocation(megaProgram, "uRules"), 1)

        GLES30.glDrawArrays(GLES30.GL_TRIANGLES, 0, 3)
        WardenGlUtil.checkGl("evaluate")
        return System.nanoTime() - t0
    }

    private fun readResultTexels(): ByteArray {
        // AC6 — GL_PACK_ALIGNMENT pinned to 1. 150*4 = 600 B is only ACCIDENTALLY
        // 4-aligned; a 149- or 151-rule engine would not be, and the failure is a
        // silent per-row shift.
        GLES30.glPixelStorei(GLES30.GL_PACK_ALIGNMENT, 1)
        readbackBuf.position(0)
        GLES30.glReadPixels(
            0, 0, MAX_RULES, 1, GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, readbackBuf
        )
        val out = ByteArray(MAX_RULES * 4)
        readbackBuf.position(0)
        readbackBuf.get(out)
        return out
    }

    /**
     * AC3 — read the RESOLVED frame texture back for the PC-vs-device diff.
     *
     * Deliberately NOT on the measurement path: this is a 8.3 MB device->host
     * readback, quoted nowhere in AC11/AC13. It exists so the colour of what the
     * mega-shader ACTUALLY sampled can be diffed against FFmpeg's rgb24 output in
     * OpenCV HSV units — sampling anything else would diff the wrong thing.
     */
    fun readFrameTexture(): ByteArray? {
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, frameFbo)
        val status = GLES30.glCheckFramebufferStatus(GLES30.GL_FRAMEBUFFER)
        if (status != GLES30.GL_FRAMEBUFFER_COMPLETE) return null
        GLES30.glPixelStorei(GLES30.GL_PACK_ALIGNMENT, 1)
        val buf = ByteBuffer
            .allocateDirect(frameWidth * frameHeight * 4).order(ByteOrder.nativeOrder())
        GLES30.glReadPixels(
            0, 0, frameWidth, frameHeight,
            GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, buf
        )
        WardenGlUtil.checkGl("readFrameTexture")
        val out = ByteArray(frameWidth * frameHeight * 4)
        buf.position(0); buf.get(out)
        return out
    }

    /** Reads back and decodes the per-rule fire bits. Returns (bits, nanoseconds). */
    fun readback(): Pair<BooleanArray, Long> {
        val t0 = System.nanoTime()
        GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, fbo)
        val raw = readResultTexels()
        val ns = System.nanoTime() - t0
        WardenGlUtil.checkGl("readback")
        return Pair(WardenRulePacker.decodeResults(raw, packed.nRules), ns)
    }

    /**
     * AC11 — forced-completion timing. 12.1 proved the naive per-stage split is
     * MISATTRIBUTED: GL work is asynchronous, the timer stops before the work
     * lands, and the blocking readback absorbs the tail. `glFinish()` makes each
     * stage's number mean what it says. Both profiles are reported, labelled.
     */
    fun finish() {
        GLES30.glFinish()
    }

    fun release() {
        val ids = IntArray(1)
        if (megaProgram != 0) { GLES30.glDeleteProgram(megaProgram); megaProgram = 0 }
        if (resolveProgram != 0) { GLES30.glDeleteProgram(resolveProgram); resolveProgram = 0 }
        if (fbo != 0) { ids[0] = fbo; GLES30.glDeleteFramebuffers(1, ids, 0); fbo = 0 }
        if (frameFbo != 0) { ids[0] = frameFbo; GLES30.glDeleteFramebuffers(1, ids, 0); frameFbo = 0 }
        if (resultTex != 0) { ids[0] = resultTex; GLES30.glDeleteTextures(1, ids, 0); resultTex = 0 }
        if (frameTex != 0) { ids[0] = frameTex; GLES30.glDeleteTextures(1, ids, 0); frameTex = 0 }
        if (rulesTex != 0) { ids[0] = rulesTex; GLES30.glDeleteTextures(1, ids, 0); rulesTex = 0 }
        if (externalTexId != 0) { ids[0] = externalTexId; GLES30.glDeleteTextures(1, ids, 0); externalTexId = 0 }
        if (planeTex[0] != 0) { GLES30.glDeleteTextures(2, planeTex, 0); planeTex = IntArray(2) }
        if (vao != 0) { ids[0] = vao; GLES30.glDeleteVertexArrays(1, ids, 0); vao = 0 }
    }

    companion object {
        const val ES_VERSION = "#version 300 es"

        /**
         * AC2 — `samplerExternalOES` is NOT core in ESSL 3.00. It requires this
         * OPTIONAL extension, which is absent on a small number of GLES 3 devices.
         * MEASURED on the Poco X5 Pro 5G (Adreno 642L, 2026-09-15): PRESENT.
         *
         * If it were missing, the answer is NOT a silent fall back to
         * `#version 100` + GL_OES_EGL_image_external — that breaks E2 ("same GLSL
         * source of truth") and turns the port into a rewrite. The answer is
         * Path P, reported as a first-class finding.
         */
        const val OES_ESSL3_EXTENSION = "GL_OES_EGL_image_external_essl3"

        /**
         * AC7 probe — reads `uRules` on the GPU and writes each rule's rect
         * width / height / mode into the RGBA8 target so the CPU can verify that
         * the GPU's view of the LUT matches what was packed.
         *
         * `/255.0` because the target is normalized RGBA8: the shader writes a
         * float in [0,1] which quantizes back to the original integer.
         */
        val RULES_PROBE_FRAG = """
$ES_VERSION
precision highp float;
precision highp int;
precision highp sampler2D;
uniform sampler2D uRules;
uniform sampler2D uRef0;
uniform sampler2D uRef1;
uniform sampler2D uRef2;
out vec4 fragColor;

// One 0/1 mismatch flag per LUT row, so the RGBA8 target only ever carries a
// boolean. Comparing HERE (rather than reading values back) is what lets all 12
// floats per rule be checked bit-exactly regardless of magnitude: the earlier
// version scaled w/h by 1/255 and silently clamped any rect wider than 255 px.
void main() {
    int i = int(gl_FragCoord.x);
    vec4 a0 = texelFetch(uRules, ivec2(i, 0), 0);
    vec4 a1 = texelFetch(uRules, ivec2(i, 1), 0);
    vec4 a2 = texelFetch(uRules, ivec2(i, 2), 0);
    vec4 b0 = texelFetch(uRef0,  ivec2(i, 0), 0);
    vec4 b1 = texelFetch(uRef1,  ivec2(i, 0), 0);
    vec4 b2 = texelFetch(uRef2,  ivec2(i, 0), 0);
    fragColor = vec4(
        any(notEqual(a0, b0)) ? 1.0 : 0.0,
        any(notEqual(a1, b1)) ? 1.0 : 0.0,
        any(notEqual(a2, b2)) ? 1.0 : 0.0,
        1.0
    );
}
""".trimIndent()

        /** Fullscreen triangle, no attributes — gl_VertexID only. Verbatim from shader.py. */
        val VERT_BODY = """
precision highp float;
precision highp int;

void main() {
    float x = (gl_VertexID == 1) ? 3.0 : -1.0;
    float y = (gl_VertexID == 2) ? 3.0 : -1.0;
    gl_Position = vec4(x, y, 0.0, 1.0);
}
""".trimIndent()

        /**
         * Path Z resolve. The implicit YUV->RGB here is DRIVER-DEFINED and
         * unspecified by AOSP — that is precisely the risk AC3 measures.
         */
        val RESOLVE_OES_FRAG = """
$ES_VERSION
#extension $OES_ESSL3_EXTENSION : require
precision highp float;
precision highp int;
uniform samplerExternalOES uExternal;
uniform mat4 uStMatrix;
uniform vec2 uSize;
out vec4 fragColor;
void main() {
    // SurfaceTexture.getTransformMatrix() is the ONLY correct way to orient an
    // external texture: it carries the decoder's vertical flip AND any crop the
    // codec applied (aligned widths mean the buffer is routinely WIDER than the
    // visible frame). Hardcoding a flip works on one device and silently shifts
    // every rect by the crop on the next.
    //
    // gl_FragCoord.xy sits at texel CENTRES (x+0.5), so dividing by the frame
    // size lands exactly on the source texel centre under GL_NEAREST.
    //
    // 🔴 THE Y FLIP IS MANDATORY AND IS *NOT* THE ST MATRIX'S JOB HERE.
    // Two conventions collide: (a) the ST matrix expects v=0 to mean the BOTTOM
    // of the displayed image (GL's window convention), while (b) frameTex row 0
    // must hold the image's TOP row, because the mega-shader indexes rects as
    // top-down absolute reference-resolution coordinates. Feeding gl_FragCoord.y
    // straight in satisfies the ST matrix and violates the shader: MEASURED, the
    // output matched flipud(PC) at mean |dBGR| 2.53 while matching PC as-is at
    // 32.36. Inverting v here reconciles the two, and the ST matrix still carries
    // the decoder's own orientation and crop on top.
    vec2 uv = vec2(gl_FragCoord.x / uSize.x, 1.0 - (gl_FragCoord.y / uSize.y));
    vec2 src = (uStMatrix * vec4(uv, 0.0, 1.0)).xy;
    vec3 rgb = texture(uExternal, src).rgb;
    fragColor = vec4(rgb.b, rgb.g, rgb.r, 1.0);
}
""".trimIndent()

        /**
         * Path P resolve — YUV->RGB with FFmpeg's EXACT bt709 limited-range
         * constants. AC3 requires this to diff to ZERO against FFmpeg's own
         * rgb24 output; "close" means the constants are wrong and every
         * downstream number is unanchored.
         *
         *   Y' = (Y - 16) / 219, C = (C - 128) / 224   (limited -> full range)
         *   R = Y' + 1.5748*Cr
         *   G = Y' - 0.1873*Cb - 0.4681*Cr             (bt709)
         *   B = Y' + 1.8556*Cb
         *
         * The 68 low-saturation rules (s_center <= 8, h_tol=180) are immune to a
         * MATRIX error and MAXIMALLY exposed to a RANGE error — the range term is
         * the one that shifts S by ~19.7 units mean. Getting the /219 and /224
         * right matters more here than the matrix does.
         */
        val RESOLVE_YUV_FRAG = """
$ES_VERSION
precision highp float;
precision highp int;
uniform sampler2D uY;
uniform sampler2D uUV;
out vec4 fragColor;
void main() {
    ivec2 p = ivec2(gl_FragCoord.xy);
    ivec2 pc = ivec2(p.x / 2, p.y / 2);
    float y = texelFetch(uY, p, 0).r * 255.0;
    // ONE RG8 chroma texture: .r = Cb, .g = Cr. See uploadYuvPlanes — the
    // decoder hands back interleaved NV12, and RG8 consumes that verbatim.
    vec2 c = texelFetch(uUV, pc, 0).rg * 255.0;
    float cb = c.r;
    float cr = c.g;

    float yn = (y - 16.0) / 219.0;
    float cbn = (cb - 128.0) / 224.0;
    float crn = (cr - 128.0) / 224.0;

    float r = yn + 1.5748 * crn;
    float g = yn - 0.1873 * cbn - 0.4681 * crn;
    float b = yn + 1.8556 * cbn;

    // Round to the nearest uint8 exactly as FFmpeg's rgb24 output does, then
    // renormalize: the mega-shader recovers integers with
    // floor(texel*255 + 0.5), so anything not already on an 8-bit lattice point
    // would be rounded a SECOND time and could land one unit off.
    vec3 bgr8 = floor(clamp(vec3(b, g, r), 0.0, 1.0) * 255.0 + 0.5);
    fragColor = vec4(bgr8 / 255.0, 1.0);
}
""".trimIndent()

    }
}
